/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SenderPostBodySlack type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SenderPostBodySlack{}

// SenderPostBodySlack Inline Slack content (text, blocks, etc.).
type SenderPostBodySlack struct {
	// Fallback plain text (required when using blocks).
	Text string `json:"text"`
	// Slack Block Kit blocks.
	Blocks []map[string]interface{} `json:"blocks,omitempty"`
	// Override bot username.
	Username *string `json:"username,omitempty"`
	// Icon: emoji (e.g. \":smile:\") or URL. Default: bot's icon.
	Icon *string `json:"icon,omitempty"`
	// Parent message `ts` to post in a thread.
	ThreadTs *string `json:"thread_ts,omitempty"`
	// When true with thread_ts, broadcasts reply to channel. Default: false.
	ReplyBroadcast *bool `json:"reply_broadcast,omitempty"`
	// URL parsing: \"full\" (clickable links) or \"none\". Default: \"none\".
	Parse *string `json:"parse,omitempty"`
	// Convert channel and username refs to Slack links. Default: false.
	LinkNames *bool `json:"link_names,omitempty"`
	// Enable Slack markup (*bold*, _italic_, `code`). Default: true.
	Mrkdwn *bool `json:"mrkdwn,omitempty"`
	// Unfurl link previews. Default: true.
	UnfurlLinks *bool `json:"unfurl_links,omitempty"`
	// Unfurl media previews. Default: true.
	UnfurlMedia *bool                                        `json:"unfurl_media,omitempty"`
	Metadata    *GetTemplatesListResponseInnerAnyOf5Metadata `json:"metadata,omitempty"`
}

type _SenderPostBodySlack SenderPostBodySlack

// NewSenderPostBodySlack instantiates a new SenderPostBodySlack object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSenderPostBodySlack(text string) *SenderPostBodySlack {
	this := SenderPostBodySlack{}
	this.Text = text
	return &this
}

// NewSenderPostBodySlackWithDefaults instantiates a new SenderPostBodySlack object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSenderPostBodySlackWithDefaults() *SenderPostBodySlack {
	this := SenderPostBodySlack{}
	return &this
}

// GetText returns the Text field value
func (o *SenderPostBodySlack) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlack) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *SenderPostBodySlack) SetText(v string) {
	o.Text = v
}

// GetBlocks returns the Blocks field value if set, zero value otherwise.
func (o *SenderPostBodySlack) GetBlocks() []map[string]interface{} {
	if o == nil || IsNil(o.Blocks) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Blocks
}

// GetBlocksOk returns a tuple with the Blocks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlack) GetBlocksOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Blocks) {
		return nil, false
	}
	return o.Blocks, true
}

// HasBlocks returns a boolean if a field has been set.
func (o *SenderPostBodySlack) HasBlocks() bool {
	if o != nil && !IsNil(o.Blocks) {
		return true
	}

	return false
}

// SetBlocks gets a reference to the given []map[string]interface{} and assigns it to the Blocks field.
func (o *SenderPostBodySlack) SetBlocks(v []map[string]interface{}) {
	o.Blocks = v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *SenderPostBodySlack) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlack) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *SenderPostBodySlack) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *SenderPostBodySlack) SetUsername(v string) {
	o.Username = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *SenderPostBodySlack) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlack) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *SenderPostBodySlack) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *SenderPostBodySlack) SetIcon(v string) {
	o.Icon = &v
}

// GetThreadTs returns the ThreadTs field value if set, zero value otherwise.
func (o *SenderPostBodySlack) GetThreadTs() string {
	if o == nil || IsNil(o.ThreadTs) {
		var ret string
		return ret
	}
	return *o.ThreadTs
}

// GetThreadTsOk returns a tuple with the ThreadTs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlack) GetThreadTsOk() (*string, bool) {
	if o == nil || IsNil(o.ThreadTs) {
		return nil, false
	}
	return o.ThreadTs, true
}

// HasThreadTs returns a boolean if a field has been set.
func (o *SenderPostBodySlack) HasThreadTs() bool {
	if o != nil && !IsNil(o.ThreadTs) {
		return true
	}

	return false
}

// SetThreadTs gets a reference to the given string and assigns it to the ThreadTs field.
func (o *SenderPostBodySlack) SetThreadTs(v string) {
	o.ThreadTs = &v
}

// GetReplyBroadcast returns the ReplyBroadcast field value if set, zero value otherwise.
func (o *SenderPostBodySlack) GetReplyBroadcast() bool {
	if o == nil || IsNil(o.ReplyBroadcast) {
		var ret bool
		return ret
	}
	return *o.ReplyBroadcast
}

// GetReplyBroadcastOk returns a tuple with the ReplyBroadcast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlack) GetReplyBroadcastOk() (*bool, bool) {
	if o == nil || IsNil(o.ReplyBroadcast) {
		return nil, false
	}
	return o.ReplyBroadcast, true
}

// HasReplyBroadcast returns a boolean if a field has been set.
func (o *SenderPostBodySlack) HasReplyBroadcast() bool {
	if o != nil && !IsNil(o.ReplyBroadcast) {
		return true
	}

	return false
}

// SetReplyBroadcast gets a reference to the given bool and assigns it to the ReplyBroadcast field.
func (o *SenderPostBodySlack) SetReplyBroadcast(v bool) {
	o.ReplyBroadcast = &v
}

// GetParse returns the Parse field value if set, zero value otherwise.
func (o *SenderPostBodySlack) GetParse() string {
	if o == nil || IsNil(o.Parse) {
		var ret string
		return ret
	}
	return *o.Parse
}

// GetParseOk returns a tuple with the Parse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlack) GetParseOk() (*string, bool) {
	if o == nil || IsNil(o.Parse) {
		return nil, false
	}
	return o.Parse, true
}

// HasParse returns a boolean if a field has been set.
func (o *SenderPostBodySlack) HasParse() bool {
	if o != nil && !IsNil(o.Parse) {
		return true
	}

	return false
}

// SetParse gets a reference to the given string and assigns it to the Parse field.
func (o *SenderPostBodySlack) SetParse(v string) {
	o.Parse = &v
}

// GetLinkNames returns the LinkNames field value if set, zero value otherwise.
func (o *SenderPostBodySlack) GetLinkNames() bool {
	if o == nil || IsNil(o.LinkNames) {
		var ret bool
		return ret
	}
	return *o.LinkNames
}

// GetLinkNamesOk returns a tuple with the LinkNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlack) GetLinkNamesOk() (*bool, bool) {
	if o == nil || IsNil(o.LinkNames) {
		return nil, false
	}
	return o.LinkNames, true
}

// HasLinkNames returns a boolean if a field has been set.
func (o *SenderPostBodySlack) HasLinkNames() bool {
	if o != nil && !IsNil(o.LinkNames) {
		return true
	}

	return false
}

// SetLinkNames gets a reference to the given bool and assigns it to the LinkNames field.
func (o *SenderPostBodySlack) SetLinkNames(v bool) {
	o.LinkNames = &v
}

// GetMrkdwn returns the Mrkdwn field value if set, zero value otherwise.
func (o *SenderPostBodySlack) GetMrkdwn() bool {
	if o == nil || IsNil(o.Mrkdwn) {
		var ret bool
		return ret
	}
	return *o.Mrkdwn
}

// GetMrkdwnOk returns a tuple with the Mrkdwn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlack) GetMrkdwnOk() (*bool, bool) {
	if o == nil || IsNil(o.Mrkdwn) {
		return nil, false
	}
	return o.Mrkdwn, true
}

// HasMrkdwn returns a boolean if a field has been set.
func (o *SenderPostBodySlack) HasMrkdwn() bool {
	if o != nil && !IsNil(o.Mrkdwn) {
		return true
	}

	return false
}

// SetMrkdwn gets a reference to the given bool and assigns it to the Mrkdwn field.
func (o *SenderPostBodySlack) SetMrkdwn(v bool) {
	o.Mrkdwn = &v
}

// GetUnfurlLinks returns the UnfurlLinks field value if set, zero value otherwise.
func (o *SenderPostBodySlack) GetUnfurlLinks() bool {
	if o == nil || IsNil(o.UnfurlLinks) {
		var ret bool
		return ret
	}
	return *o.UnfurlLinks
}

// GetUnfurlLinksOk returns a tuple with the UnfurlLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlack) GetUnfurlLinksOk() (*bool, bool) {
	if o == nil || IsNil(o.UnfurlLinks) {
		return nil, false
	}
	return o.UnfurlLinks, true
}

// HasUnfurlLinks returns a boolean if a field has been set.
func (o *SenderPostBodySlack) HasUnfurlLinks() bool {
	if o != nil && !IsNil(o.UnfurlLinks) {
		return true
	}

	return false
}

// SetUnfurlLinks gets a reference to the given bool and assigns it to the UnfurlLinks field.
func (o *SenderPostBodySlack) SetUnfurlLinks(v bool) {
	o.UnfurlLinks = &v
}

// GetUnfurlMedia returns the UnfurlMedia field value if set, zero value otherwise.
func (o *SenderPostBodySlack) GetUnfurlMedia() bool {
	if o == nil || IsNil(o.UnfurlMedia) {
		var ret bool
		return ret
	}
	return *o.UnfurlMedia
}

// GetUnfurlMediaOk returns a tuple with the UnfurlMedia field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlack) GetUnfurlMediaOk() (*bool, bool) {
	if o == nil || IsNil(o.UnfurlMedia) {
		return nil, false
	}
	return o.UnfurlMedia, true
}

// HasUnfurlMedia returns a boolean if a field has been set.
func (o *SenderPostBodySlack) HasUnfurlMedia() bool {
	if o != nil && !IsNil(o.UnfurlMedia) {
		return true
	}

	return false
}

// SetUnfurlMedia gets a reference to the given bool and assigns it to the UnfurlMedia field.
func (o *SenderPostBodySlack) SetUnfurlMedia(v bool) {
	o.UnfurlMedia = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *SenderPostBodySlack) GetMetadata() GetTemplatesListResponseInnerAnyOf5Metadata {
	if o == nil || IsNil(o.Metadata) {
		var ret GetTemplatesListResponseInnerAnyOf5Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlack) GetMetadataOk() (*GetTemplatesListResponseInnerAnyOf5Metadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *SenderPostBodySlack) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given GetTemplatesListResponseInnerAnyOf5Metadata and assigns it to the Metadata field.
func (o *SenderPostBodySlack) SetMetadata(v GetTemplatesListResponseInnerAnyOf5Metadata) {
	o.Metadata = &v
}

func (o SenderPostBodySlack) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SenderPostBodySlack) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	if !IsNil(o.Blocks) {
		toSerialize["blocks"] = o.Blocks
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.ThreadTs) {
		toSerialize["thread_ts"] = o.ThreadTs
	}
	if !IsNil(o.ReplyBroadcast) {
		toSerialize["reply_broadcast"] = o.ReplyBroadcast
	}
	if !IsNil(o.Parse) {
		toSerialize["parse"] = o.Parse
	}
	if !IsNil(o.LinkNames) {
		toSerialize["link_names"] = o.LinkNames
	}
	if !IsNil(o.Mrkdwn) {
		toSerialize["mrkdwn"] = o.Mrkdwn
	}
	if !IsNil(o.UnfurlLinks) {
		toSerialize["unfurl_links"] = o.UnfurlLinks
	}
	if !IsNil(o.UnfurlMedia) {
		toSerialize["unfurl_media"] = o.UnfurlMedia
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *SenderPostBodySlack) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSenderPostBodySlack := _SenderPostBodySlack{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSenderPostBodySlack)

	if err != nil {
		return err
	}

	*o = SenderPostBodySlack(varSenderPostBodySlack)

	return err
}

type NullableSenderPostBodySlack struct {
	value *SenderPostBodySlack
	isSet bool
}

func (v NullableSenderPostBodySlack) Get() *SenderPostBodySlack {
	return v.value
}

func (v *NullableSenderPostBodySlack) Set(val *SenderPostBodySlack) {
	v.value = val
	v.isSet = true
}

func (v NullableSenderPostBodySlack) IsSet() bool {
	return v.isSet
}

func (v *NullableSenderPostBodySlack) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSenderPostBodySlack(val *SenderPostBodySlack) *NullableSenderPostBodySlack {
	return &NullableSenderPostBodySlack{value: val, isSet: true}
}

func (v NullableSenderPostBodySlack) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSenderPostBodySlack) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
