/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"encoding/json"
)

// checks if the IngishtsPostRequestMetricDataQueriesInnerMetricStat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IngishtsPostRequestMetricDataQueriesInnerMetricStat{}

// IngishtsPostRequestMetricDataQueriesInnerMetricStat <p>This structure defines the metric to be returned, along with the statistics, period,             and units.</p>
type IngishtsPostRequestMetricDataQueriesInnerMetricStat struct {
	Metric *IngishtsPostRequestMetricDataQueriesInnerMetricStatMetric `json:"Metric,omitempty"`
	// <p>The granularity, in seconds, of the returned data points. For metrics with regular             resolution, a period can be as short as one minute (60 seconds) and must be a multiple             of 60. For high-resolution metrics that are collected at intervals of less than one             minute, the period can be 1, 5, 10, 20, 30, 60, or any multiple of 60. High-resolution             metrics are those metrics stored by a <code>PutMetricData</code> call that includes a             <code>StorageResolution</code> of 1 second.</p>          <p>If the <code>StartTime</code> parameter specifies a time stamp that is greater than             3 hours ago, you must specify the period as follows or no data points in that time range             is returned:</p>          <ul>             <li>                <p>Start time between 3 hours and 15 days ago - Use a multiple of 60 seconds                     (1 minute).</p>             </li>             <li>                <p>Start time between 15 and 63 days ago - Use a multiple of 300 seconds (5                     minutes).</p>             </li>             <li>                <p>Start time greater than 63 days ago - Use a multiple of 3600 seconds (1                     hour).</p>             </li>          </ul>
	Period *float32 `json:"Period,omitempty"`
	// <p>The statistic to return. It can include any CloudWatch statistic or extended             statistic.</p>
	Stat *string `json:"Stat,omitempty"`
	Unit *string `json:"Unit,omitempty"`
}

// NewIngishtsPostRequestMetricDataQueriesInnerMetricStat instantiates a new IngishtsPostRequestMetricDataQueriesInnerMetricStat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIngishtsPostRequestMetricDataQueriesInnerMetricStat() *IngishtsPostRequestMetricDataQueriesInnerMetricStat {
	this := IngishtsPostRequestMetricDataQueriesInnerMetricStat{}
	return &this
}

// NewIngishtsPostRequestMetricDataQueriesInnerMetricStatWithDefaults instantiates a new IngishtsPostRequestMetricDataQueriesInnerMetricStat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIngishtsPostRequestMetricDataQueriesInnerMetricStatWithDefaults() *IngishtsPostRequestMetricDataQueriesInnerMetricStat {
	this := IngishtsPostRequestMetricDataQueriesInnerMetricStat{}
	return &this
}

// GetMetric returns the Metric field value if set, zero value otherwise.
func (o *IngishtsPostRequestMetricDataQueriesInnerMetricStat) GetMetric() IngishtsPostRequestMetricDataQueriesInnerMetricStatMetric {
	if o == nil || IsNil(o.Metric) {
		var ret IngishtsPostRequestMetricDataQueriesInnerMetricStatMetric
		return ret
	}
	return *o.Metric
}

// GetMetricOk returns a tuple with the Metric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IngishtsPostRequestMetricDataQueriesInnerMetricStat) GetMetricOk() (*IngishtsPostRequestMetricDataQueriesInnerMetricStatMetric, bool) {
	if o == nil || IsNil(o.Metric) {
		return nil, false
	}
	return o.Metric, true
}

// HasMetric returns a boolean if a field has been set.
func (o *IngishtsPostRequestMetricDataQueriesInnerMetricStat) HasMetric() bool {
	if o != nil && !IsNil(o.Metric) {
		return true
	}

	return false
}

// SetMetric gets a reference to the given IngishtsPostRequestMetricDataQueriesInnerMetricStatMetric and assigns it to the Metric field.
func (o *IngishtsPostRequestMetricDataQueriesInnerMetricStat) SetMetric(v IngishtsPostRequestMetricDataQueriesInnerMetricStatMetric) {
	o.Metric = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *IngishtsPostRequestMetricDataQueriesInnerMetricStat) GetPeriod() float32 {
	if o == nil || IsNil(o.Period) {
		var ret float32
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IngishtsPostRequestMetricDataQueriesInnerMetricStat) GetPeriodOk() (*float32, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *IngishtsPostRequestMetricDataQueriesInnerMetricStat) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given float32 and assigns it to the Period field.
func (o *IngishtsPostRequestMetricDataQueriesInnerMetricStat) SetPeriod(v float32) {
	o.Period = &v
}

// GetStat returns the Stat field value if set, zero value otherwise.
func (o *IngishtsPostRequestMetricDataQueriesInnerMetricStat) GetStat() string {
	if o == nil || IsNil(o.Stat) {
		var ret string
		return ret
	}
	return *o.Stat
}

// GetStatOk returns a tuple with the Stat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IngishtsPostRequestMetricDataQueriesInnerMetricStat) GetStatOk() (*string, bool) {
	if o == nil || IsNil(o.Stat) {
		return nil, false
	}
	return o.Stat, true
}

// HasStat returns a boolean if a field has been set.
func (o *IngishtsPostRequestMetricDataQueriesInnerMetricStat) HasStat() bool {
	if o != nil && !IsNil(o.Stat) {
		return true
	}

	return false
}

// SetStat gets a reference to the given string and assigns it to the Stat field.
func (o *IngishtsPostRequestMetricDataQueriesInnerMetricStat) SetStat(v string) {
	o.Stat = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *IngishtsPostRequestMetricDataQueriesInnerMetricStat) GetUnit() string {
	if o == nil || IsNil(o.Unit) {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IngishtsPostRequestMetricDataQueriesInnerMetricStat) GetUnitOk() (*string, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *IngishtsPostRequestMetricDataQueriesInnerMetricStat) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *IngishtsPostRequestMetricDataQueriesInnerMetricStat) SetUnit(v string) {
	o.Unit = &v
}

func (o IngishtsPostRequestMetricDataQueriesInnerMetricStat) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IngishtsPostRequestMetricDataQueriesInnerMetricStat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metric) {
		toSerialize["Metric"] = o.Metric
	}
	if !IsNil(o.Period) {
		toSerialize["Period"] = o.Period
	}
	if !IsNil(o.Stat) {
		toSerialize["Stat"] = o.Stat
	}
	if !IsNil(o.Unit) {
		toSerialize["Unit"] = o.Unit
	}
	return toSerialize, nil
}

type NullableIngishtsPostRequestMetricDataQueriesInnerMetricStat struct {
	value *IngishtsPostRequestMetricDataQueriesInnerMetricStat
	isSet bool
}

func (v NullableIngishtsPostRequestMetricDataQueriesInnerMetricStat) Get() *IngishtsPostRequestMetricDataQueriesInnerMetricStat {
	return v.value
}

func (v *NullableIngishtsPostRequestMetricDataQueriesInnerMetricStat) Set(val *IngishtsPostRequestMetricDataQueriesInnerMetricStat) {
	v.value = val
	v.isSet = true
}

func (v NullableIngishtsPostRequestMetricDataQueriesInnerMetricStat) IsSet() bool {
	return v.isSet
}

func (v *NullableIngishtsPostRequestMetricDataQueriesInnerMetricStat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIngishtsPostRequestMetricDataQueriesInnerMetricStat(val *IngishtsPostRequestMetricDataQueriesInnerMetricStat) *NullableIngishtsPostRequestMetricDataQueriesInnerMetricStat {
	return &NullableIngishtsPostRequestMetricDataQueriesInnerMetricStat{value: val, isSet: true}
}

func (v NullableIngishtsPostRequestMetricDataQueriesInnerMetricStat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIngishtsPostRequestMetricDataQueriesInnerMetricStat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
