/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LogsQueryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LogsQueryResponse{}

// LogsQueryResponse Response type for POST /logs/query
type LogsQueryResponse struct {
	QueryId string `json:"queryId"`
}

type _LogsQueryResponse LogsQueryResponse

// NewLogsQueryResponse instantiates a new LogsQueryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogsQueryResponse(queryId string) *LogsQueryResponse {
	this := LogsQueryResponse{}
	this.QueryId = queryId
	return &this
}

// NewLogsQueryResponseWithDefaults instantiates a new LogsQueryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogsQueryResponseWithDefaults() *LogsQueryResponse {
	this := LogsQueryResponse{}
	return &this
}

// GetQueryId returns the QueryId field value
func (o *LogsQueryResponse) GetQueryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QueryId
}

// GetQueryIdOk returns a tuple with the QueryId field value
// and a boolean to check if the value has been set.
func (o *LogsQueryResponse) GetQueryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QueryId, true
}

// SetQueryId sets field value
func (o *LogsQueryResponse) SetQueryId(v string) {
	o.QueryId = v
}

func (o LogsQueryResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LogsQueryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["queryId"] = o.QueryId
	return toSerialize, nil
}

func (o *LogsQueryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"queryId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLogsQueryResponse := _LogsQueryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLogsQueryResponse)

	if err != nil {
		return err
	}

	*o = LogsQueryResponse(varLogsQueryResponse)

	return err
}

type NullableLogsQueryResponse struct {
	value *LogsQueryResponse
	isSet bool
}

func (v NullableLogsQueryResponse) Get() *LogsQueryResponse {
	return v.value
}

func (v *NullableLogsQueryResponse) Set(val *LogsQueryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLogsQueryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLogsQueryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogsQueryResponse(val *LogsQueryResponse) *NullableLogsQueryResponse {
	return &NullableLogsQueryResponse{value: val, isSet: true}
}

func (v NullableLogsQueryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogsQueryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
