/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UnbindNumberResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnbindNumberResponse{}

// UnbindNumberResponse struct for UnbindNumberResponse
type UnbindNumberResponse struct {
	Agent BindNumberResponseAgent `json:"agent"`
}

type _UnbindNumberResponse UnbindNumberResponse

// NewUnbindNumberResponse instantiates a new UnbindNumberResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnbindNumberResponse(agent BindNumberResponseAgent) *UnbindNumberResponse {
	this := UnbindNumberResponse{}
	this.Agent = agent
	return &this
}

// NewUnbindNumberResponseWithDefaults instantiates a new UnbindNumberResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnbindNumberResponseWithDefaults() *UnbindNumberResponse {
	this := UnbindNumberResponse{}
	return &this
}

// GetAgent returns the Agent field value
func (o *UnbindNumberResponse) GetAgent() BindNumberResponseAgent {
	if o == nil {
		var ret BindNumberResponseAgent
		return ret
	}

	return o.Agent
}

// GetAgentOk returns a tuple with the Agent field value
// and a boolean to check if the value has been set.
func (o *UnbindNumberResponse) GetAgentOk() (*BindNumberResponseAgent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Agent, true
}

// SetAgent sets field value
func (o *UnbindNumberResponse) SetAgent(v BindNumberResponseAgent) {
	o.Agent = v
}

func (o UnbindNumberResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnbindNumberResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent"] = o.Agent
	return toSerialize, nil
}

func (o *UnbindNumberResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnbindNumberResponse := _UnbindNumberResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnbindNumberResponse)

	if err != nil {
		return err
	}

	*o = UnbindNumberResponse(varUnbindNumberResponse)

	return err
}

type NullableUnbindNumberResponse struct {
	value *UnbindNumberResponse
	isSet bool
}

func (v NullableUnbindNumberResponse) Get() *UnbindNumberResponse {
	return v.value
}

func (v *NullableUnbindNumberResponse) Set(val *UnbindNumberResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUnbindNumberResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUnbindNumberResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnbindNumberResponse(val *UnbindNumberResponse) *NullableUnbindNumberResponse {
	return &NullableUnbindNumberResponse{value: val, isSet: true}
}

func (v NullableUnbindNumberResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnbindNumberResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
