/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetKeysResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetKeysResponse{}

// GetKeysResponse Response body for GET /keys endpoint Lists all API keys for the authenticated account
type GetKeysResponse struct {
	// Array of API key metadata (does not include the actual key strings)
	Keys []GetKeysResponseKeysInner `json:"keys"`
}

type _GetKeysResponse GetKeysResponse

// NewGetKeysResponse instantiates a new GetKeysResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetKeysResponse(keys []GetKeysResponseKeysInner) *GetKeysResponse {
	this := GetKeysResponse{}
	this.Keys = keys
	return &this
}

// NewGetKeysResponseWithDefaults instantiates a new GetKeysResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetKeysResponseWithDefaults() *GetKeysResponse {
	this := GetKeysResponse{}
	return &this
}

// GetKeys returns the Keys field value
func (o *GetKeysResponse) GetKeys() []GetKeysResponseKeysInner {
	if o == nil {
		var ret []GetKeysResponseKeysInner
		return ret
	}

	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value
// and a boolean to check if the value has been set.
func (o *GetKeysResponse) GetKeysOk() ([]GetKeysResponseKeysInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Keys, true
}

// SetKeys sets field value
func (o *GetKeysResponse) SetKeys(v []GetKeysResponseKeysInner) {
	o.Keys = v
}

func (o GetKeysResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetKeysResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["keys"] = o.Keys
	return toSerialize, nil
}

func (o *GetKeysResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"keys",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetKeysResponse := _GetKeysResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetKeysResponse)

	if err != nil {
		return err
	}

	*o = GetKeysResponse(varGetKeysResponse)

	return err
}

type NullableGetKeysResponse struct {
	value *GetKeysResponse
	isSet bool
}

func (v NullableGetKeysResponse) Get() *GetKeysResponse {
	return v.value
}

func (v *NullableGetKeysResponse) Set(val *GetKeysResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetKeysResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetKeysResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetKeysResponse(val *GetKeysResponse) *NullableGetKeysResponse {
	return &NullableGetKeysResponse{value: val, isSet: true}
}

func (v NullableGetKeysResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetKeysResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
