/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ListBroadcastRecipientsResponseRecipientsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListBroadcastRecipientsResponseRecipientsInner{}

// ListBroadcastRecipientsResponseRecipientsInner struct for ListBroadcastRecipientsResponseRecipientsInner
type ListBroadcastRecipientsResponseRecipientsInner struct {
	TrackingId     string  `json:"trackingId"`
	UserId         string  `json:"userId"`
	Email          string  `json:"email"`
	SentAt         *string `json:"sentAt,omitempty"`
	DeliveredAt    *string `json:"deliveredAt,omitempty"`
	OpenedAt       *string `json:"openedAt,omitempty"`
	ClickedAt      *string `json:"clickedAt,omitempty"`
	BouncedAt      *string `json:"bouncedAt,omitempty"`
	BounceType     *string `json:"bounceType,omitempty"`
	ComplainedAt   *string `json:"complainedAt,omitempty"`
	UnsubscribedAt *string `json:"unsubscribedAt,omitempty"`
	SkippedAt      *string `json:"skippedAt,omitempty"`
	SkipReason     *string `json:"skipReason,omitempty"`
	FailedAt       *string `json:"failedAt,omitempty"`
	FailReason     *string `json:"failReason,omitempty"`
}

type _ListBroadcastRecipientsResponseRecipientsInner ListBroadcastRecipientsResponseRecipientsInner

// NewListBroadcastRecipientsResponseRecipientsInner instantiates a new ListBroadcastRecipientsResponseRecipientsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListBroadcastRecipientsResponseRecipientsInner(trackingId string, userId string, email string) *ListBroadcastRecipientsResponseRecipientsInner {
	this := ListBroadcastRecipientsResponseRecipientsInner{}
	this.TrackingId = trackingId
	this.UserId = userId
	this.Email = email
	return &this
}

// NewListBroadcastRecipientsResponseRecipientsInnerWithDefaults instantiates a new ListBroadcastRecipientsResponseRecipientsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListBroadcastRecipientsResponseRecipientsInnerWithDefaults() *ListBroadcastRecipientsResponseRecipientsInner {
	this := ListBroadcastRecipientsResponseRecipientsInner{}
	return &this
}

// GetTrackingId returns the TrackingId field value
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetTrackingId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TrackingId
}

// GetTrackingIdOk returns a tuple with the TrackingId field value
// and a boolean to check if the value has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetTrackingIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrackingId, true
}

// SetTrackingId sets field value
func (o *ListBroadcastRecipientsResponseRecipientsInner) SetTrackingId(v string) {
	o.TrackingId = v
}

// GetUserId returns the UserId field value
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ListBroadcastRecipientsResponseRecipientsInner) SetUserId(v string) {
	o.UserId = v
}

// GetEmail returns the Email field value
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ListBroadcastRecipientsResponseRecipientsInner) SetEmail(v string) {
	o.Email = v
}

// GetSentAt returns the SentAt field value if set, zero value otherwise.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetSentAt() string {
	if o == nil || IsNil(o.SentAt) {
		var ret string
		return ret
	}
	return *o.SentAt
}

// GetSentAtOk returns a tuple with the SentAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetSentAtOk() (*string, bool) {
	if o == nil || IsNil(o.SentAt) {
		return nil, false
	}
	return o.SentAt, true
}

// HasSentAt returns a boolean if a field has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) HasSentAt() bool {
	if o != nil && !IsNil(o.SentAt) {
		return true
	}

	return false
}

// SetSentAt gets a reference to the given string and assigns it to the SentAt field.
func (o *ListBroadcastRecipientsResponseRecipientsInner) SetSentAt(v string) {
	o.SentAt = &v
}

// GetDeliveredAt returns the DeliveredAt field value if set, zero value otherwise.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetDeliveredAt() string {
	if o == nil || IsNil(o.DeliveredAt) {
		var ret string
		return ret
	}
	return *o.DeliveredAt
}

// GetDeliveredAtOk returns a tuple with the DeliveredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetDeliveredAtOk() (*string, bool) {
	if o == nil || IsNil(o.DeliveredAt) {
		return nil, false
	}
	return o.DeliveredAt, true
}

// HasDeliveredAt returns a boolean if a field has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) HasDeliveredAt() bool {
	if o != nil && !IsNil(o.DeliveredAt) {
		return true
	}

	return false
}

// SetDeliveredAt gets a reference to the given string and assigns it to the DeliveredAt field.
func (o *ListBroadcastRecipientsResponseRecipientsInner) SetDeliveredAt(v string) {
	o.DeliveredAt = &v
}

// GetOpenedAt returns the OpenedAt field value if set, zero value otherwise.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetOpenedAt() string {
	if o == nil || IsNil(o.OpenedAt) {
		var ret string
		return ret
	}
	return *o.OpenedAt
}

// GetOpenedAtOk returns a tuple with the OpenedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetOpenedAtOk() (*string, bool) {
	if o == nil || IsNil(o.OpenedAt) {
		return nil, false
	}
	return o.OpenedAt, true
}

// HasOpenedAt returns a boolean if a field has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) HasOpenedAt() bool {
	if o != nil && !IsNil(o.OpenedAt) {
		return true
	}

	return false
}

// SetOpenedAt gets a reference to the given string and assigns it to the OpenedAt field.
func (o *ListBroadcastRecipientsResponseRecipientsInner) SetOpenedAt(v string) {
	o.OpenedAt = &v
}

// GetClickedAt returns the ClickedAt field value if set, zero value otherwise.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetClickedAt() string {
	if o == nil || IsNil(o.ClickedAt) {
		var ret string
		return ret
	}
	return *o.ClickedAt
}

// GetClickedAtOk returns a tuple with the ClickedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetClickedAtOk() (*string, bool) {
	if o == nil || IsNil(o.ClickedAt) {
		return nil, false
	}
	return o.ClickedAt, true
}

// HasClickedAt returns a boolean if a field has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) HasClickedAt() bool {
	if o != nil && !IsNil(o.ClickedAt) {
		return true
	}

	return false
}

// SetClickedAt gets a reference to the given string and assigns it to the ClickedAt field.
func (o *ListBroadcastRecipientsResponseRecipientsInner) SetClickedAt(v string) {
	o.ClickedAt = &v
}

// GetBouncedAt returns the BouncedAt field value if set, zero value otherwise.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetBouncedAt() string {
	if o == nil || IsNil(o.BouncedAt) {
		var ret string
		return ret
	}
	return *o.BouncedAt
}

// GetBouncedAtOk returns a tuple with the BouncedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetBouncedAtOk() (*string, bool) {
	if o == nil || IsNil(o.BouncedAt) {
		return nil, false
	}
	return o.BouncedAt, true
}

// HasBouncedAt returns a boolean if a field has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) HasBouncedAt() bool {
	if o != nil && !IsNil(o.BouncedAt) {
		return true
	}

	return false
}

// SetBouncedAt gets a reference to the given string and assigns it to the BouncedAt field.
func (o *ListBroadcastRecipientsResponseRecipientsInner) SetBouncedAt(v string) {
	o.BouncedAt = &v
}

// GetBounceType returns the BounceType field value if set, zero value otherwise.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetBounceType() string {
	if o == nil || IsNil(o.BounceType) {
		var ret string
		return ret
	}
	return *o.BounceType
}

// GetBounceTypeOk returns a tuple with the BounceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetBounceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BounceType) {
		return nil, false
	}
	return o.BounceType, true
}

// HasBounceType returns a boolean if a field has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) HasBounceType() bool {
	if o != nil && !IsNil(o.BounceType) {
		return true
	}

	return false
}

// SetBounceType gets a reference to the given string and assigns it to the BounceType field.
func (o *ListBroadcastRecipientsResponseRecipientsInner) SetBounceType(v string) {
	o.BounceType = &v
}

// GetComplainedAt returns the ComplainedAt field value if set, zero value otherwise.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetComplainedAt() string {
	if o == nil || IsNil(o.ComplainedAt) {
		var ret string
		return ret
	}
	return *o.ComplainedAt
}

// GetComplainedAtOk returns a tuple with the ComplainedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetComplainedAtOk() (*string, bool) {
	if o == nil || IsNil(o.ComplainedAt) {
		return nil, false
	}
	return o.ComplainedAt, true
}

// HasComplainedAt returns a boolean if a field has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) HasComplainedAt() bool {
	if o != nil && !IsNil(o.ComplainedAt) {
		return true
	}

	return false
}

// SetComplainedAt gets a reference to the given string and assigns it to the ComplainedAt field.
func (o *ListBroadcastRecipientsResponseRecipientsInner) SetComplainedAt(v string) {
	o.ComplainedAt = &v
}

// GetUnsubscribedAt returns the UnsubscribedAt field value if set, zero value otherwise.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetUnsubscribedAt() string {
	if o == nil || IsNil(o.UnsubscribedAt) {
		var ret string
		return ret
	}
	return *o.UnsubscribedAt
}

// GetUnsubscribedAtOk returns a tuple with the UnsubscribedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetUnsubscribedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UnsubscribedAt) {
		return nil, false
	}
	return o.UnsubscribedAt, true
}

// HasUnsubscribedAt returns a boolean if a field has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) HasUnsubscribedAt() bool {
	if o != nil && !IsNil(o.UnsubscribedAt) {
		return true
	}

	return false
}

// SetUnsubscribedAt gets a reference to the given string and assigns it to the UnsubscribedAt field.
func (o *ListBroadcastRecipientsResponseRecipientsInner) SetUnsubscribedAt(v string) {
	o.UnsubscribedAt = &v
}

// GetSkippedAt returns the SkippedAt field value if set, zero value otherwise.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetSkippedAt() string {
	if o == nil || IsNil(o.SkippedAt) {
		var ret string
		return ret
	}
	return *o.SkippedAt
}

// GetSkippedAtOk returns a tuple with the SkippedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetSkippedAtOk() (*string, bool) {
	if o == nil || IsNil(o.SkippedAt) {
		return nil, false
	}
	return o.SkippedAt, true
}

// HasSkippedAt returns a boolean if a field has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) HasSkippedAt() bool {
	if o != nil && !IsNil(o.SkippedAt) {
		return true
	}

	return false
}

// SetSkippedAt gets a reference to the given string and assigns it to the SkippedAt field.
func (o *ListBroadcastRecipientsResponseRecipientsInner) SetSkippedAt(v string) {
	o.SkippedAt = &v
}

// GetSkipReason returns the SkipReason field value if set, zero value otherwise.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetSkipReason() string {
	if o == nil || IsNil(o.SkipReason) {
		var ret string
		return ret
	}
	return *o.SkipReason
}

// GetSkipReasonOk returns a tuple with the SkipReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetSkipReasonOk() (*string, bool) {
	if o == nil || IsNil(o.SkipReason) {
		return nil, false
	}
	return o.SkipReason, true
}

// HasSkipReason returns a boolean if a field has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) HasSkipReason() bool {
	if o != nil && !IsNil(o.SkipReason) {
		return true
	}

	return false
}

// SetSkipReason gets a reference to the given string and assigns it to the SkipReason field.
func (o *ListBroadcastRecipientsResponseRecipientsInner) SetSkipReason(v string) {
	o.SkipReason = &v
}

// GetFailedAt returns the FailedAt field value if set, zero value otherwise.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetFailedAt() string {
	if o == nil || IsNil(o.FailedAt) {
		var ret string
		return ret
	}
	return *o.FailedAt
}

// GetFailedAtOk returns a tuple with the FailedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetFailedAtOk() (*string, bool) {
	if o == nil || IsNil(o.FailedAt) {
		return nil, false
	}
	return o.FailedAt, true
}

// HasFailedAt returns a boolean if a field has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) HasFailedAt() bool {
	if o != nil && !IsNil(o.FailedAt) {
		return true
	}

	return false
}

// SetFailedAt gets a reference to the given string and assigns it to the FailedAt field.
func (o *ListBroadcastRecipientsResponseRecipientsInner) SetFailedAt(v string) {
	o.FailedAt = &v
}

// GetFailReason returns the FailReason field value if set, zero value otherwise.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetFailReason() string {
	if o == nil || IsNil(o.FailReason) {
		var ret string
		return ret
	}
	return *o.FailReason
}

// GetFailReasonOk returns a tuple with the FailReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) GetFailReasonOk() (*string, bool) {
	if o == nil || IsNil(o.FailReason) {
		return nil, false
	}
	return o.FailReason, true
}

// HasFailReason returns a boolean if a field has been set.
func (o *ListBroadcastRecipientsResponseRecipientsInner) HasFailReason() bool {
	if o != nil && !IsNil(o.FailReason) {
		return true
	}

	return false
}

// SetFailReason gets a reference to the given string and assigns it to the FailReason field.
func (o *ListBroadcastRecipientsResponseRecipientsInner) SetFailReason(v string) {
	o.FailReason = &v
}

func (o ListBroadcastRecipientsResponseRecipientsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListBroadcastRecipientsResponseRecipientsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["trackingId"] = o.TrackingId
	toSerialize["userId"] = o.UserId
	toSerialize["email"] = o.Email
	if !IsNil(o.SentAt) {
		toSerialize["sentAt"] = o.SentAt
	}
	if !IsNil(o.DeliveredAt) {
		toSerialize["deliveredAt"] = o.DeliveredAt
	}
	if !IsNil(o.OpenedAt) {
		toSerialize["openedAt"] = o.OpenedAt
	}
	if !IsNil(o.ClickedAt) {
		toSerialize["clickedAt"] = o.ClickedAt
	}
	if !IsNil(o.BouncedAt) {
		toSerialize["bouncedAt"] = o.BouncedAt
	}
	if !IsNil(o.BounceType) {
		toSerialize["bounceType"] = o.BounceType
	}
	if !IsNil(o.ComplainedAt) {
		toSerialize["complainedAt"] = o.ComplainedAt
	}
	if !IsNil(o.UnsubscribedAt) {
		toSerialize["unsubscribedAt"] = o.UnsubscribedAt
	}
	if !IsNil(o.SkippedAt) {
		toSerialize["skippedAt"] = o.SkippedAt
	}
	if !IsNil(o.SkipReason) {
		toSerialize["skipReason"] = o.SkipReason
	}
	if !IsNil(o.FailedAt) {
		toSerialize["failedAt"] = o.FailedAt
	}
	if !IsNil(o.FailReason) {
		toSerialize["failReason"] = o.FailReason
	}
	return toSerialize, nil
}

func (o *ListBroadcastRecipientsResponseRecipientsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"trackingId",
		"userId",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListBroadcastRecipientsResponseRecipientsInner := _ListBroadcastRecipientsResponseRecipientsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListBroadcastRecipientsResponseRecipientsInner)

	if err != nil {
		return err
	}

	*o = ListBroadcastRecipientsResponseRecipientsInner(varListBroadcastRecipientsResponseRecipientsInner)

	return err
}

type NullableListBroadcastRecipientsResponseRecipientsInner struct {
	value *ListBroadcastRecipientsResponseRecipientsInner
	isSet bool
}

func (v NullableListBroadcastRecipientsResponseRecipientsInner) Get() *ListBroadcastRecipientsResponseRecipientsInner {
	return v.value
}

func (v *NullableListBroadcastRecipientsResponseRecipientsInner) Set(val *ListBroadcastRecipientsResponseRecipientsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListBroadcastRecipientsResponseRecipientsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListBroadcastRecipientsResponseRecipientsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListBroadcastRecipientsResponseRecipientsInner(val *ListBroadcastRecipientsResponseRecipientsInner) *NullableListBroadcastRecipientsResponseRecipientsInner {
	return &NullableListBroadcastRecipientsResponseRecipientsInner{value: val, isSet: true}
}

func (v NullableListBroadcastRecipientsResponseRecipientsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListBroadcastRecipientsResponseRecipientsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
