/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetTemplatesListResponseInnerAnyOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTemplatesListResponseInnerAnyOf2{}

// GetTemplatesListResponseInnerAnyOf2 struct for GetTemplatesListResponseInnerAnyOf2
type GetTemplatesListResponseInnerAnyOf2 struct {
	EnvId          string           `json:"envId"`
	NotificationId string           `json:"notificationId"`
	TemplateId     string           `json:"templateId"`
	Channel        ChannelsEnum     `json:"channel"`
	Default        bool             `json:"default"`
	IsDefaultFor   *map[string]bool `json:"isDefaultFor,omitempty"`
	Text           string           `json:"text"`
}

type _GetTemplatesListResponseInnerAnyOf2 GetTemplatesListResponseInnerAnyOf2

// NewGetTemplatesListResponseInnerAnyOf2 instantiates a new GetTemplatesListResponseInnerAnyOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTemplatesListResponseInnerAnyOf2(envId string, notificationId string, templateId string, channel ChannelsEnum, default_ bool, text string) *GetTemplatesListResponseInnerAnyOf2 {
	this := GetTemplatesListResponseInnerAnyOf2{}
	this.EnvId = envId
	this.NotificationId = notificationId
	this.TemplateId = templateId
	this.Channel = channel
	this.Default = default_
	this.Text = text
	return &this
}

// NewGetTemplatesListResponseInnerAnyOf2WithDefaults instantiates a new GetTemplatesListResponseInnerAnyOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTemplatesListResponseInnerAnyOf2WithDefaults() *GetTemplatesListResponseInnerAnyOf2 {
	this := GetTemplatesListResponseInnerAnyOf2{}
	return &this
}

// GetEnvId returns the EnvId field value
func (o *GetTemplatesListResponseInnerAnyOf2) GetEnvId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvId
}

// GetEnvIdOk returns a tuple with the EnvId field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf2) GetEnvIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvId, true
}

// SetEnvId sets field value
func (o *GetTemplatesListResponseInnerAnyOf2) SetEnvId(v string) {
	o.EnvId = v
}

// GetNotificationId returns the NotificationId field value
func (o *GetTemplatesListResponseInnerAnyOf2) GetNotificationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NotificationId
}

// GetNotificationIdOk returns a tuple with the NotificationId field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf2) GetNotificationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotificationId, true
}

// SetNotificationId sets field value
func (o *GetTemplatesListResponseInnerAnyOf2) SetNotificationId(v string) {
	o.NotificationId = v
}

// GetTemplateId returns the TemplateId field value
func (o *GetTemplatesListResponseInnerAnyOf2) GetTemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf2) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateId, true
}

// SetTemplateId sets field value
func (o *GetTemplatesListResponseInnerAnyOf2) SetTemplateId(v string) {
	o.TemplateId = v
}

// GetChannel returns the Channel field value
func (o *GetTemplatesListResponseInnerAnyOf2) GetChannel() ChannelsEnum {
	if o == nil {
		var ret ChannelsEnum
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf2) GetChannelOk() (*ChannelsEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *GetTemplatesListResponseInnerAnyOf2) SetChannel(v ChannelsEnum) {
	o.Channel = v
}

// GetDefault returns the Default field value
func (o *GetTemplatesListResponseInnerAnyOf2) GetDefault() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf2) GetDefaultOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Default, true
}

// SetDefault sets field value
func (o *GetTemplatesListResponseInnerAnyOf2) SetDefault(v bool) {
	o.Default = v
}

// GetIsDefaultFor returns the IsDefaultFor field value if set, zero value otherwise.
func (o *GetTemplatesListResponseInnerAnyOf2) GetIsDefaultFor() map[string]bool {
	if o == nil || IsNil(o.IsDefaultFor) {
		var ret map[string]bool
		return ret
	}
	return *o.IsDefaultFor
}

// GetIsDefaultForOk returns a tuple with the IsDefaultFor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf2) GetIsDefaultForOk() (*map[string]bool, bool) {
	if o == nil || IsNil(o.IsDefaultFor) {
		return nil, false
	}
	return o.IsDefaultFor, true
}

// HasIsDefaultFor returns a boolean if a field has been set.
func (o *GetTemplatesListResponseInnerAnyOf2) HasIsDefaultFor() bool {
	if o != nil && !IsNil(o.IsDefaultFor) {
		return true
	}

	return false
}

// SetIsDefaultFor gets a reference to the given map[string]bool and assigns it to the IsDefaultFor field.
func (o *GetTemplatesListResponseInnerAnyOf2) SetIsDefaultFor(v map[string]bool) {
	o.IsDefaultFor = &v
}

// GetText returns the Text field value
func (o *GetTemplatesListResponseInnerAnyOf2) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf2) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *GetTemplatesListResponseInnerAnyOf2) SetText(v string) {
	o.Text = v
}

func (o GetTemplatesListResponseInnerAnyOf2) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTemplatesListResponseInnerAnyOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["envId"] = o.EnvId
	toSerialize["notificationId"] = o.NotificationId
	toSerialize["templateId"] = o.TemplateId
	toSerialize["channel"] = o.Channel
	toSerialize["default"] = o.Default
	if !IsNil(o.IsDefaultFor) {
		toSerialize["isDefaultFor"] = o.IsDefaultFor
	}
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

func (o *GetTemplatesListResponseInnerAnyOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"envId",
		"notificationId",
		"templateId",
		"channel",
		"default",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetTemplatesListResponseInnerAnyOf2 := _GetTemplatesListResponseInnerAnyOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetTemplatesListResponseInnerAnyOf2)

	if err != nil {
		return err
	}

	*o = GetTemplatesListResponseInnerAnyOf2(varGetTemplatesListResponseInnerAnyOf2)

	return err
}

type NullableGetTemplatesListResponseInnerAnyOf2 struct {
	value *GetTemplatesListResponseInnerAnyOf2
	isSet bool
}

func (v NullableGetTemplatesListResponseInnerAnyOf2) Get() *GetTemplatesListResponseInnerAnyOf2 {
	return v.value
}

func (v *NullableGetTemplatesListResponseInnerAnyOf2) Set(val *GetTemplatesListResponseInnerAnyOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTemplatesListResponseInnerAnyOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTemplatesListResponseInnerAnyOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTemplatesListResponseInnerAnyOf2(val *GetTemplatesListResponseInnerAnyOf2) *NullableGetTemplatesListResponseInnerAnyOf2 {
	return &NullableGetTemplatesListResponseInnerAnyOf2{value: val, isSet: true}
}

func (v NullableGetTemplatesListResponseInnerAnyOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTemplatesListResponseInnerAnyOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
