/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the GetSendersResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSendersResponseInner{}

// GetSendersResponseInner struct for GetSendersResponseInner
type GetSendersResponseInner struct {
	Sender               string    `json:"sender"`
	Status               string    `json:"status"`
	LastSync             time.Time `json:"lastSync"`
	VerificationTokens   []string  `json:"verificationTokens,omitempty"`
	MailFromDomainStatus *string   `json:"mailFromDomainStatus,omitempty"`
	CreatedAt            string    `json:"createdAt"`
	PrivateDKIMKey       *string   `json:"privateDKIMKey,omitempty"`
	ReminderSentAt       *string   `json:"reminderSentAt,omitempty"`
	Selector             string    `json:"selector"`
}

type _GetSendersResponseInner GetSendersResponseInner

// NewGetSendersResponseInner instantiates a new GetSendersResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSendersResponseInner(sender string, status string, lastSync time.Time, createdAt string, selector string) *GetSendersResponseInner {
	this := GetSendersResponseInner{}
	this.Sender = sender
	this.Status = status
	this.LastSync = lastSync
	this.CreatedAt = createdAt
	this.Selector = selector
	return &this
}

// NewGetSendersResponseInnerWithDefaults instantiates a new GetSendersResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSendersResponseInnerWithDefaults() *GetSendersResponseInner {
	this := GetSendersResponseInner{}
	return &this
}

// GetSender returns the Sender field value
func (o *GetSendersResponseInner) GetSender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sender
}

// GetSenderOk returns a tuple with the Sender field value
// and a boolean to check if the value has been set.
func (o *GetSendersResponseInner) GetSenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sender, true
}

// SetSender sets field value
func (o *GetSendersResponseInner) SetSender(v string) {
	o.Sender = v
}

// GetStatus returns the Status field value
func (o *GetSendersResponseInner) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetSendersResponseInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetSendersResponseInner) SetStatus(v string) {
	o.Status = v
}

// GetLastSync returns the LastSync field value
func (o *GetSendersResponseInner) GetLastSync() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastSync
}

// GetLastSyncOk returns a tuple with the LastSync field value
// and a boolean to check if the value has been set.
func (o *GetSendersResponseInner) GetLastSyncOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastSync, true
}

// SetLastSync sets field value
func (o *GetSendersResponseInner) SetLastSync(v time.Time) {
	o.LastSync = v
}

// GetVerificationTokens returns the VerificationTokens field value if set, zero value otherwise.
func (o *GetSendersResponseInner) GetVerificationTokens() []string {
	if o == nil || IsNil(o.VerificationTokens) {
		var ret []string
		return ret
	}
	return o.VerificationTokens
}

// GetVerificationTokensOk returns a tuple with the VerificationTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendersResponseInner) GetVerificationTokensOk() ([]string, bool) {
	if o == nil || IsNil(o.VerificationTokens) {
		return nil, false
	}
	return o.VerificationTokens, true
}

// HasVerificationTokens returns a boolean if a field has been set.
func (o *GetSendersResponseInner) HasVerificationTokens() bool {
	if o != nil && !IsNil(o.VerificationTokens) {
		return true
	}

	return false
}

// SetVerificationTokens gets a reference to the given []string and assigns it to the VerificationTokens field.
func (o *GetSendersResponseInner) SetVerificationTokens(v []string) {
	o.VerificationTokens = v
}

// GetMailFromDomainStatus returns the MailFromDomainStatus field value if set, zero value otherwise.
func (o *GetSendersResponseInner) GetMailFromDomainStatus() string {
	if o == nil || IsNil(o.MailFromDomainStatus) {
		var ret string
		return ret
	}
	return *o.MailFromDomainStatus
}

// GetMailFromDomainStatusOk returns a tuple with the MailFromDomainStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendersResponseInner) GetMailFromDomainStatusOk() (*string, bool) {
	if o == nil || IsNil(o.MailFromDomainStatus) {
		return nil, false
	}
	return o.MailFromDomainStatus, true
}

// HasMailFromDomainStatus returns a boolean if a field has been set.
func (o *GetSendersResponseInner) HasMailFromDomainStatus() bool {
	if o != nil && !IsNil(o.MailFromDomainStatus) {
		return true
	}

	return false
}

// SetMailFromDomainStatus gets a reference to the given string and assigns it to the MailFromDomainStatus field.
func (o *GetSendersResponseInner) SetMailFromDomainStatus(v string) {
	o.MailFromDomainStatus = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetSendersResponseInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetSendersResponseInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetSendersResponseInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetPrivateDKIMKey returns the PrivateDKIMKey field value if set, zero value otherwise.
func (o *GetSendersResponseInner) GetPrivateDKIMKey() string {
	if o == nil || IsNil(o.PrivateDKIMKey) {
		var ret string
		return ret
	}
	return *o.PrivateDKIMKey
}

// GetPrivateDKIMKeyOk returns a tuple with the PrivateDKIMKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendersResponseInner) GetPrivateDKIMKeyOk() (*string, bool) {
	if o == nil || IsNil(o.PrivateDKIMKey) {
		return nil, false
	}
	return o.PrivateDKIMKey, true
}

// HasPrivateDKIMKey returns a boolean if a field has been set.
func (o *GetSendersResponseInner) HasPrivateDKIMKey() bool {
	if o != nil && !IsNil(o.PrivateDKIMKey) {
		return true
	}

	return false
}

// SetPrivateDKIMKey gets a reference to the given string and assigns it to the PrivateDKIMKey field.
func (o *GetSendersResponseInner) SetPrivateDKIMKey(v string) {
	o.PrivateDKIMKey = &v
}

// GetReminderSentAt returns the ReminderSentAt field value if set, zero value otherwise.
func (o *GetSendersResponseInner) GetReminderSentAt() string {
	if o == nil || IsNil(o.ReminderSentAt) {
		var ret string
		return ret
	}
	return *o.ReminderSentAt
}

// GetReminderSentAtOk returns a tuple with the ReminderSentAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendersResponseInner) GetReminderSentAtOk() (*string, bool) {
	if o == nil || IsNil(o.ReminderSentAt) {
		return nil, false
	}
	return o.ReminderSentAt, true
}

// HasReminderSentAt returns a boolean if a field has been set.
func (o *GetSendersResponseInner) HasReminderSentAt() bool {
	if o != nil && !IsNil(o.ReminderSentAt) {
		return true
	}

	return false
}

// SetReminderSentAt gets a reference to the given string and assigns it to the ReminderSentAt field.
func (o *GetSendersResponseInner) SetReminderSentAt(v string) {
	o.ReminderSentAt = &v
}

// GetSelector returns the Selector field value
func (o *GetSendersResponseInner) GetSelector() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Selector
}

// GetSelectorOk returns a tuple with the Selector field value
// and a boolean to check if the value has been set.
func (o *GetSendersResponseInner) GetSelectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Selector, true
}

// SetSelector sets field value
func (o *GetSendersResponseInner) SetSelector(v string) {
	o.Selector = v
}

func (o GetSendersResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSendersResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sender"] = o.Sender
	toSerialize["status"] = o.Status
	toSerialize["lastSync"] = o.LastSync
	if !IsNil(o.VerificationTokens) {
		toSerialize["verificationTokens"] = o.VerificationTokens
	}
	if !IsNil(o.MailFromDomainStatus) {
		toSerialize["mailFromDomainStatus"] = o.MailFromDomainStatus
	}
	toSerialize["createdAt"] = o.CreatedAt
	if !IsNil(o.PrivateDKIMKey) {
		toSerialize["privateDKIMKey"] = o.PrivateDKIMKey
	}
	if !IsNil(o.ReminderSentAt) {
		toSerialize["reminderSentAt"] = o.ReminderSentAt
	}
	toSerialize["selector"] = o.Selector
	return toSerialize, nil
}

func (o *GetSendersResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sender",
		"status",
		"lastSync",
		"createdAt",
		"selector",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSendersResponseInner := _GetSendersResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetSendersResponseInner)

	if err != nil {
		return err
	}

	*o = GetSendersResponseInner(varGetSendersResponseInner)

	return err
}

type NullableGetSendersResponseInner struct {
	value *GetSendersResponseInner
	isSet bool
}

func (v NullableGetSendersResponseInner) Get() *GetSendersResponseInner {
	return v.value
}

func (v *NullableGetSendersResponseInner) Set(val *GetSendersResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSendersResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSendersResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSendersResponseInner(val *GetSendersResponseInner) *NullableGetSendersResponseInner {
	return &NullableGetSendersResponseInner{value: val, isSet: true}
}

func (v NullableGetSendersResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSendersResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
