/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"encoding/json"
)

// checks if the GetSendersResponseInnerVerificationRecords type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSendersResponseInnerVerificationRecords{}

// GetSendersResponseInnerVerificationRecords Keyed by record id — computed on domain API responses, not stored in DB.
type GetSendersResponseInnerVerificationRecords struct {
	Dkim        *GetSendersResponseInnerVerificationRecordsDkim `json:"dkim,omitempty"`
	MailFromSpf *GetSendersResponseInnerVerificationRecordsDkim `json:"mail_from_spf,omitempty"`
	MailFromMx  *GetSendersResponseInnerVerificationRecordsDkim `json:"mail_from_mx,omitempty"`
	Dmarc       *GetSendersResponseInnerVerificationRecordsDkim `json:"dmarc,omitempty"`
	InboundMx   *GetSendersResponseInnerVerificationRecordsDkim `json:"inbound_mx,omitempty"`
}

// NewGetSendersResponseInnerVerificationRecords instantiates a new GetSendersResponseInnerVerificationRecords object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSendersResponseInnerVerificationRecords() *GetSendersResponseInnerVerificationRecords {
	this := GetSendersResponseInnerVerificationRecords{}
	return &this
}

// NewGetSendersResponseInnerVerificationRecordsWithDefaults instantiates a new GetSendersResponseInnerVerificationRecords object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSendersResponseInnerVerificationRecordsWithDefaults() *GetSendersResponseInnerVerificationRecords {
	this := GetSendersResponseInnerVerificationRecords{}
	return &this
}

// GetDkim returns the Dkim field value if set, zero value otherwise.
func (o *GetSendersResponseInnerVerificationRecords) GetDkim() GetSendersResponseInnerVerificationRecordsDkim {
	if o == nil || IsNil(o.Dkim) {
		var ret GetSendersResponseInnerVerificationRecordsDkim
		return ret
	}
	return *o.Dkim
}

// GetDkimOk returns a tuple with the Dkim field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendersResponseInnerVerificationRecords) GetDkimOk() (*GetSendersResponseInnerVerificationRecordsDkim, bool) {
	if o == nil || IsNil(o.Dkim) {
		return nil, false
	}
	return o.Dkim, true
}

// HasDkim returns a boolean if a field has been set.
func (o *GetSendersResponseInnerVerificationRecords) HasDkim() bool {
	if o != nil && !IsNil(o.Dkim) {
		return true
	}

	return false
}

// SetDkim gets a reference to the given GetSendersResponseInnerVerificationRecordsDkim and assigns it to the Dkim field.
func (o *GetSendersResponseInnerVerificationRecords) SetDkim(v GetSendersResponseInnerVerificationRecordsDkim) {
	o.Dkim = &v
}

// GetMailFromSpf returns the MailFromSpf field value if set, zero value otherwise.
func (o *GetSendersResponseInnerVerificationRecords) GetMailFromSpf() GetSendersResponseInnerVerificationRecordsDkim {
	if o == nil || IsNil(o.MailFromSpf) {
		var ret GetSendersResponseInnerVerificationRecordsDkim
		return ret
	}
	return *o.MailFromSpf
}

// GetMailFromSpfOk returns a tuple with the MailFromSpf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendersResponseInnerVerificationRecords) GetMailFromSpfOk() (*GetSendersResponseInnerVerificationRecordsDkim, bool) {
	if o == nil || IsNil(o.MailFromSpf) {
		return nil, false
	}
	return o.MailFromSpf, true
}

// HasMailFromSpf returns a boolean if a field has been set.
func (o *GetSendersResponseInnerVerificationRecords) HasMailFromSpf() bool {
	if o != nil && !IsNil(o.MailFromSpf) {
		return true
	}

	return false
}

// SetMailFromSpf gets a reference to the given GetSendersResponseInnerVerificationRecordsDkim and assigns it to the MailFromSpf field.
func (o *GetSendersResponseInnerVerificationRecords) SetMailFromSpf(v GetSendersResponseInnerVerificationRecordsDkim) {
	o.MailFromSpf = &v
}

// GetMailFromMx returns the MailFromMx field value if set, zero value otherwise.
func (o *GetSendersResponseInnerVerificationRecords) GetMailFromMx() GetSendersResponseInnerVerificationRecordsDkim {
	if o == nil || IsNil(o.MailFromMx) {
		var ret GetSendersResponseInnerVerificationRecordsDkim
		return ret
	}
	return *o.MailFromMx
}

// GetMailFromMxOk returns a tuple with the MailFromMx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendersResponseInnerVerificationRecords) GetMailFromMxOk() (*GetSendersResponseInnerVerificationRecordsDkim, bool) {
	if o == nil || IsNil(o.MailFromMx) {
		return nil, false
	}
	return o.MailFromMx, true
}

// HasMailFromMx returns a boolean if a field has been set.
func (o *GetSendersResponseInnerVerificationRecords) HasMailFromMx() bool {
	if o != nil && !IsNil(o.MailFromMx) {
		return true
	}

	return false
}

// SetMailFromMx gets a reference to the given GetSendersResponseInnerVerificationRecordsDkim and assigns it to the MailFromMx field.
func (o *GetSendersResponseInnerVerificationRecords) SetMailFromMx(v GetSendersResponseInnerVerificationRecordsDkim) {
	o.MailFromMx = &v
}

// GetDmarc returns the Dmarc field value if set, zero value otherwise.
func (o *GetSendersResponseInnerVerificationRecords) GetDmarc() GetSendersResponseInnerVerificationRecordsDkim {
	if o == nil || IsNil(o.Dmarc) {
		var ret GetSendersResponseInnerVerificationRecordsDkim
		return ret
	}
	return *o.Dmarc
}

// GetDmarcOk returns a tuple with the Dmarc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendersResponseInnerVerificationRecords) GetDmarcOk() (*GetSendersResponseInnerVerificationRecordsDkim, bool) {
	if o == nil || IsNil(o.Dmarc) {
		return nil, false
	}
	return o.Dmarc, true
}

// HasDmarc returns a boolean if a field has been set.
func (o *GetSendersResponseInnerVerificationRecords) HasDmarc() bool {
	if o != nil && !IsNil(o.Dmarc) {
		return true
	}

	return false
}

// SetDmarc gets a reference to the given GetSendersResponseInnerVerificationRecordsDkim and assigns it to the Dmarc field.
func (o *GetSendersResponseInnerVerificationRecords) SetDmarc(v GetSendersResponseInnerVerificationRecordsDkim) {
	o.Dmarc = &v
}

// GetInboundMx returns the InboundMx field value if set, zero value otherwise.
func (o *GetSendersResponseInnerVerificationRecords) GetInboundMx() GetSendersResponseInnerVerificationRecordsDkim {
	if o == nil || IsNil(o.InboundMx) {
		var ret GetSendersResponseInnerVerificationRecordsDkim
		return ret
	}
	return *o.InboundMx
}

// GetInboundMxOk returns a tuple with the InboundMx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendersResponseInnerVerificationRecords) GetInboundMxOk() (*GetSendersResponseInnerVerificationRecordsDkim, bool) {
	if o == nil || IsNil(o.InboundMx) {
		return nil, false
	}
	return o.InboundMx, true
}

// HasInboundMx returns a boolean if a field has been set.
func (o *GetSendersResponseInnerVerificationRecords) HasInboundMx() bool {
	if o != nil && !IsNil(o.InboundMx) {
		return true
	}

	return false
}

// SetInboundMx gets a reference to the given GetSendersResponseInnerVerificationRecordsDkim and assigns it to the InboundMx field.
func (o *GetSendersResponseInnerVerificationRecords) SetInboundMx(v GetSendersResponseInnerVerificationRecordsDkim) {
	o.InboundMx = &v
}

func (o GetSendersResponseInnerVerificationRecords) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSendersResponseInnerVerificationRecords) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dkim) {
		toSerialize["dkim"] = o.Dkim
	}
	if !IsNil(o.MailFromSpf) {
		toSerialize["mail_from_spf"] = o.MailFromSpf
	}
	if !IsNil(o.MailFromMx) {
		toSerialize["mail_from_mx"] = o.MailFromMx
	}
	if !IsNil(o.Dmarc) {
		toSerialize["dmarc"] = o.Dmarc
	}
	if !IsNil(o.InboundMx) {
		toSerialize["inbound_mx"] = o.InboundMx
	}
	return toSerialize, nil
}

type NullableGetSendersResponseInnerVerificationRecords struct {
	value *GetSendersResponseInnerVerificationRecords
	isSet bool
}

func (v NullableGetSendersResponseInnerVerificationRecords) Get() *GetSendersResponseInnerVerificationRecords {
	return v.value
}

func (v *NullableGetSendersResponseInnerVerificationRecords) Set(val *GetSendersResponseInnerVerificationRecords) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSendersResponseInnerVerificationRecords) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSendersResponseInnerVerificationRecords) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSendersResponseInnerVerificationRecords(val *GetSendersResponseInnerVerificationRecords) *NullableGetSendersResponseInnerVerificationRecords {
	return &NullableGetSendersResponseInnerVerificationRecords{value: val, isSet: true}
}

func (v NullableGetSendersResponseInnerVerificationRecords) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSendersResponseInnerVerificationRecords) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
