/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetLogsResponseMessagesInnerMediaInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetLogsResponseMessagesInnerMediaInner{}

// GetLogsResponseMessagesInnerMediaInner struct for GetLogsResponseMessagesInnerMediaInner
type GetLogsResponseMessagesInnerMediaInner struct {
	Url         string  `json:"url"`
	ContentType *string `json:"contentType,omitempty"`
}

type _GetLogsResponseMessagesInnerMediaInner GetLogsResponseMessagesInnerMediaInner

// NewGetLogsResponseMessagesInnerMediaInner instantiates a new GetLogsResponseMessagesInnerMediaInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLogsResponseMessagesInnerMediaInner(url string) *GetLogsResponseMessagesInnerMediaInner {
	this := GetLogsResponseMessagesInnerMediaInner{}
	this.Url = url
	return &this
}

// NewGetLogsResponseMessagesInnerMediaInnerWithDefaults instantiates a new GetLogsResponseMessagesInnerMediaInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLogsResponseMessagesInnerMediaInnerWithDefaults() *GetLogsResponseMessagesInnerMediaInner {
	this := GetLogsResponseMessagesInnerMediaInner{}
	return &this
}

// GetUrl returns the Url field value
func (o *GetLogsResponseMessagesInnerMediaInner) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *GetLogsResponseMessagesInnerMediaInner) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *GetLogsResponseMessagesInnerMediaInner) SetUrl(v string) {
	o.Url = v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *GetLogsResponseMessagesInnerMediaInner) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLogsResponseMessagesInnerMediaInner) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *GetLogsResponseMessagesInnerMediaInner) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *GetLogsResponseMessagesInnerMediaInner) SetContentType(v string) {
	o.ContentType = &v
}

func (o GetLogsResponseMessagesInnerMediaInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetLogsResponseMessagesInnerMediaInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	if !IsNil(o.ContentType) {
		toSerialize["contentType"] = o.ContentType
	}
	return toSerialize, nil
}

func (o *GetLogsResponseMessagesInnerMediaInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetLogsResponseMessagesInnerMediaInner := _GetLogsResponseMessagesInnerMediaInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetLogsResponseMessagesInnerMediaInner)

	if err != nil {
		return err
	}

	*o = GetLogsResponseMessagesInnerMediaInner(varGetLogsResponseMessagesInnerMediaInner)

	return err
}

type NullableGetLogsResponseMessagesInnerMediaInner struct {
	value *GetLogsResponseMessagesInnerMediaInner
	isSet bool
}

func (v NullableGetLogsResponseMessagesInnerMediaInner) Get() *GetLogsResponseMessagesInnerMediaInner {
	return v.value
}

func (v *NullableGetLogsResponseMessagesInnerMediaInner) Set(val *GetLogsResponseMessagesInnerMediaInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLogsResponseMessagesInnerMediaInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLogsResponseMessagesInnerMediaInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLogsResponseMessagesInnerMediaInner(val *GetLogsResponseMessagesInnerMediaInner) *NullableGetLogsResponseMessagesInnerMediaInner {
	return &NullableGetLogsResponseMessagesInnerMediaInner{value: val, isSet: true}
}

func (v NullableGetLogsResponseMessagesInnerMediaInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLogsResponseMessagesInnerMediaInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
