/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetUsageHistoryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUsageHistoryResponse{}

// GetUsageHistoryResponse Response for GET /account/usage/history
type GetUsageHistoryResponse struct {
	// Array of usage items, one per month in the requested range
	Items []GetUsageHistoryResponseItemsInner `json:"items"`
}

type _GetUsageHistoryResponse GetUsageHistoryResponse

// NewGetUsageHistoryResponse instantiates a new GetUsageHistoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUsageHistoryResponse(items []GetUsageHistoryResponseItemsInner) *GetUsageHistoryResponse {
	this := GetUsageHistoryResponse{}
	this.Items = items
	return &this
}

// NewGetUsageHistoryResponseWithDefaults instantiates a new GetUsageHistoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUsageHistoryResponseWithDefaults() *GetUsageHistoryResponse {
	this := GetUsageHistoryResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *GetUsageHistoryResponse) GetItems() []GetUsageHistoryResponseItemsInner {
	if o == nil {
		var ret []GetUsageHistoryResponseItemsInner
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *GetUsageHistoryResponse) GetItemsOk() ([]GetUsageHistoryResponseItemsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *GetUsageHistoryResponse) SetItems(v []GetUsageHistoryResponseItemsInner) {
	o.Items = v
}

func (o GetUsageHistoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUsageHistoryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *GetUsageHistoryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetUsageHistoryResponse := _GetUsageHistoryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetUsageHistoryResponse)

	if err != nil {
		return err
	}

	*o = GetUsageHistoryResponse(varGetUsageHistoryResponse)

	return err
}

type NullableGetUsageHistoryResponse struct {
	value *GetUsageHistoryResponse
	isSet bool
}

func (v NullableGetUsageHistoryResponse) Get() *GetUsageHistoryResponse {
	return v.value
}

func (v *NullableGetUsageHistoryResponse) Set(val *GetUsageHistoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUsageHistoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUsageHistoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUsageHistoryResponse(val *GetUsageHistoryResponse) *NullableGetUsageHistoryResponse {
	return &NullableGetUsageHistoryResponse{value: val, isSet: true}
}

func (v NullableGetUsageHistoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUsageHistoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
