/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BillingPostRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingPostRequestBody{}

// BillingPostRequestBody struct for BillingPostRequestBody
type BillingPostRequestBody struct {
	// Price ID for the message tier (EMAIL, INAPP_WEB, WEB_PUSH, PUSH, SLACK)
	MessagePriceId *string `json:"messagePriceId,omitempty"`
	// Price ID for the budget tier (SMS, CALL)
	BudgetPriceId *string `json:"budgetPriceId,omitempty"`
	SuccessUrl    string  `json:"successUrl"`
	CancelUrl     string  `json:"cancelUrl"`
}

type _BillingPostRequestBody BillingPostRequestBody

// NewBillingPostRequestBody instantiates a new BillingPostRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingPostRequestBody(successUrl string, cancelUrl string) *BillingPostRequestBody {
	this := BillingPostRequestBody{}
	this.SuccessUrl = successUrl
	this.CancelUrl = cancelUrl
	return &this
}

// NewBillingPostRequestBodyWithDefaults instantiates a new BillingPostRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingPostRequestBodyWithDefaults() *BillingPostRequestBody {
	this := BillingPostRequestBody{}
	return &this
}

// GetMessagePriceId returns the MessagePriceId field value if set, zero value otherwise.
func (o *BillingPostRequestBody) GetMessagePriceId() string {
	if o == nil || IsNil(o.MessagePriceId) {
		var ret string
		return ret
	}
	return *o.MessagePriceId
}

// GetMessagePriceIdOk returns a tuple with the MessagePriceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingPostRequestBody) GetMessagePriceIdOk() (*string, bool) {
	if o == nil || IsNil(o.MessagePriceId) {
		return nil, false
	}
	return o.MessagePriceId, true
}

// HasMessagePriceId returns a boolean if a field has been set.
func (o *BillingPostRequestBody) HasMessagePriceId() bool {
	if o != nil && !IsNil(o.MessagePriceId) {
		return true
	}

	return false
}

// SetMessagePriceId gets a reference to the given string and assigns it to the MessagePriceId field.
func (o *BillingPostRequestBody) SetMessagePriceId(v string) {
	o.MessagePriceId = &v
}

// GetBudgetPriceId returns the BudgetPriceId field value if set, zero value otherwise.
func (o *BillingPostRequestBody) GetBudgetPriceId() string {
	if o == nil || IsNil(o.BudgetPriceId) {
		var ret string
		return ret
	}
	return *o.BudgetPriceId
}

// GetBudgetPriceIdOk returns a tuple with the BudgetPriceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingPostRequestBody) GetBudgetPriceIdOk() (*string, bool) {
	if o == nil || IsNil(o.BudgetPriceId) {
		return nil, false
	}
	return o.BudgetPriceId, true
}

// HasBudgetPriceId returns a boolean if a field has been set.
func (o *BillingPostRequestBody) HasBudgetPriceId() bool {
	if o != nil && !IsNil(o.BudgetPriceId) {
		return true
	}

	return false
}

// SetBudgetPriceId gets a reference to the given string and assigns it to the BudgetPriceId field.
func (o *BillingPostRequestBody) SetBudgetPriceId(v string) {
	o.BudgetPriceId = &v
}

// GetSuccessUrl returns the SuccessUrl field value
func (o *BillingPostRequestBody) GetSuccessUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SuccessUrl
}

// GetSuccessUrlOk returns a tuple with the SuccessUrl field value
// and a boolean to check if the value has been set.
func (o *BillingPostRequestBody) GetSuccessUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuccessUrl, true
}

// SetSuccessUrl sets field value
func (o *BillingPostRequestBody) SetSuccessUrl(v string) {
	o.SuccessUrl = v
}

// GetCancelUrl returns the CancelUrl field value
func (o *BillingPostRequestBody) GetCancelUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CancelUrl
}

// GetCancelUrlOk returns a tuple with the CancelUrl field value
// and a boolean to check if the value has been set.
func (o *BillingPostRequestBody) GetCancelUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CancelUrl, true
}

// SetCancelUrl sets field value
func (o *BillingPostRequestBody) SetCancelUrl(v string) {
	o.CancelUrl = v
}

func (o BillingPostRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingPostRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MessagePriceId) {
		toSerialize["messagePriceId"] = o.MessagePriceId
	}
	if !IsNil(o.BudgetPriceId) {
		toSerialize["budgetPriceId"] = o.BudgetPriceId
	}
	toSerialize["successUrl"] = o.SuccessUrl
	toSerialize["cancelUrl"] = o.CancelUrl
	return toSerialize, nil
}

func (o *BillingPostRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"successUrl",
		"cancelUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingPostRequestBody := _BillingPostRequestBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingPostRequestBody)

	if err != nil {
		return err
	}

	*o = BillingPostRequestBody(varBillingPostRequestBody)

	return err
}

type NullableBillingPostRequestBody struct {
	value *BillingPostRequestBody
	isSet bool
}

func (v NullableBillingPostRequestBody) Get() *BillingPostRequestBody {
	return v.value
}

func (v *NullableBillingPostRequestBody) Set(val *BillingPostRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingPostRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingPostRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingPostRequestBody(val *BillingPostRequestBody) *NullableBillingPostRequestBody {
	return &NullableBillingPostRequestBody{value: val, isSet: true}
}

func (v NullableBillingPostRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingPostRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
