/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SetDefaultTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetDefaultTemplateRequest{}

// SetDefaultTemplateRequest struct for SetDefaultTemplateRequest
type SetDefaultTemplateRequest struct {
	TemplateId string   `json:"templateId"`
	Modes      []string `json:"modes"`
}

type _SetDefaultTemplateRequest SetDefaultTemplateRequest

// NewSetDefaultTemplateRequest instantiates a new SetDefaultTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetDefaultTemplateRequest(templateId string, modes []string) *SetDefaultTemplateRequest {
	this := SetDefaultTemplateRequest{}
	this.TemplateId = templateId
	this.Modes = modes
	return &this
}

// NewSetDefaultTemplateRequestWithDefaults instantiates a new SetDefaultTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetDefaultTemplateRequestWithDefaults() *SetDefaultTemplateRequest {
	this := SetDefaultTemplateRequest{}
	return &this
}

// GetTemplateId returns the TemplateId field value
func (o *SetDefaultTemplateRequest) GetTemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value
// and a boolean to check if the value has been set.
func (o *SetDefaultTemplateRequest) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateId, true
}

// SetTemplateId sets field value
func (o *SetDefaultTemplateRequest) SetTemplateId(v string) {
	o.TemplateId = v
}

// GetModes returns the Modes field value
func (o *SetDefaultTemplateRequest) GetModes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Modes
}

// GetModesOk returns a tuple with the Modes field value
// and a boolean to check if the value has been set.
func (o *SetDefaultTemplateRequest) GetModesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Modes, true
}

// SetModes sets field value
func (o *SetDefaultTemplateRequest) SetModes(v []string) {
	o.Modes = v
}

func (o SetDefaultTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetDefaultTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["templateId"] = o.TemplateId
	toSerialize["modes"] = o.Modes
	return toSerialize, nil
}

func (o *SetDefaultTemplateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"templateId",
		"modes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetDefaultTemplateRequest := _SetDefaultTemplateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetDefaultTemplateRequest)

	if err != nil {
		return err
	}

	*o = SetDefaultTemplateRequest(varSetDefaultTemplateRequest)

	return err
}

type NullableSetDefaultTemplateRequest struct {
	value *SetDefaultTemplateRequest
	isSet bool
}

func (v NullableSetDefaultTemplateRequest) Get() *SetDefaultTemplateRequest {
	return v.value
}

func (v *NullableSetDefaultTemplateRequest) Set(val *SetDefaultTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetDefaultTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetDefaultTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetDefaultTemplateRequest(val *SetDefaultTemplateRequest) *NullableSetDefaultTemplateRequest {
	return &NullableSetDefaultTemplateRequest{value: val, isSet: true}
}

func (v NullableSetDefaultTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetDefaultTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
