/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"encoding/json"
)

// checks if the A2pRegistrationUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &A2pRegistrationUpdateRequest{}

// A2pRegistrationUpdateRequest Request body for PUT /registrations/a2p
type A2pRegistrationUpdateRequest struct {
	ScenarioId             *string `json:"scenarioId,omitempty"`
	BusinessType           *string `json:"businessType,omitempty"`
	LegalName              *string `json:"legalName,omitempty"`
	TaxId                  *string `json:"taxId,omitempty"`
	Website                *string `json:"website,omitempty"`
	Country                *string `json:"country,omitempty"`
	FullAddress            *string `json:"fullAddress,omitempty"`
	ComplianceContactEmail *string `json:"complianceContactEmail,omitempty"`
	ComplianceContactPhone *string `json:"complianceContactPhone,omitempty"`
}

// NewA2pRegistrationUpdateRequest instantiates a new A2pRegistrationUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewA2pRegistrationUpdateRequest() *A2pRegistrationUpdateRequest {
	this := A2pRegistrationUpdateRequest{}
	return &this
}

// NewA2pRegistrationUpdateRequestWithDefaults instantiates a new A2pRegistrationUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewA2pRegistrationUpdateRequestWithDefaults() *A2pRegistrationUpdateRequest {
	this := A2pRegistrationUpdateRequest{}
	return &this
}

// GetScenarioId returns the ScenarioId field value if set, zero value otherwise.
func (o *A2pRegistrationUpdateRequest) GetScenarioId() string {
	if o == nil || IsNil(o.ScenarioId) {
		var ret string
		return ret
	}
	return *o.ScenarioId
}

// GetScenarioIdOk returns a tuple with the ScenarioId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *A2pRegistrationUpdateRequest) GetScenarioIdOk() (*string, bool) {
	if o == nil || IsNil(o.ScenarioId) {
		return nil, false
	}
	return o.ScenarioId, true
}

// HasScenarioId returns a boolean if a field has been set.
func (o *A2pRegistrationUpdateRequest) HasScenarioId() bool {
	if o != nil && !IsNil(o.ScenarioId) {
		return true
	}

	return false
}

// SetScenarioId gets a reference to the given string and assigns it to the ScenarioId field.
func (o *A2pRegistrationUpdateRequest) SetScenarioId(v string) {
	o.ScenarioId = &v
}

// GetBusinessType returns the BusinessType field value if set, zero value otherwise.
func (o *A2pRegistrationUpdateRequest) GetBusinessType() string {
	if o == nil || IsNil(o.BusinessType) {
		var ret string
		return ret
	}
	return *o.BusinessType
}

// GetBusinessTypeOk returns a tuple with the BusinessType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *A2pRegistrationUpdateRequest) GetBusinessTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BusinessType) {
		return nil, false
	}
	return o.BusinessType, true
}

// HasBusinessType returns a boolean if a field has been set.
func (o *A2pRegistrationUpdateRequest) HasBusinessType() bool {
	if o != nil && !IsNil(o.BusinessType) {
		return true
	}

	return false
}

// SetBusinessType gets a reference to the given string and assigns it to the BusinessType field.
func (o *A2pRegistrationUpdateRequest) SetBusinessType(v string) {
	o.BusinessType = &v
}

// GetLegalName returns the LegalName field value if set, zero value otherwise.
func (o *A2pRegistrationUpdateRequest) GetLegalName() string {
	if o == nil || IsNil(o.LegalName) {
		var ret string
		return ret
	}
	return *o.LegalName
}

// GetLegalNameOk returns a tuple with the LegalName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *A2pRegistrationUpdateRequest) GetLegalNameOk() (*string, bool) {
	if o == nil || IsNil(o.LegalName) {
		return nil, false
	}
	return o.LegalName, true
}

// HasLegalName returns a boolean if a field has been set.
func (o *A2pRegistrationUpdateRequest) HasLegalName() bool {
	if o != nil && !IsNil(o.LegalName) {
		return true
	}

	return false
}

// SetLegalName gets a reference to the given string and assigns it to the LegalName field.
func (o *A2pRegistrationUpdateRequest) SetLegalName(v string) {
	o.LegalName = &v
}

// GetTaxId returns the TaxId field value if set, zero value otherwise.
func (o *A2pRegistrationUpdateRequest) GetTaxId() string {
	if o == nil || IsNil(o.TaxId) {
		var ret string
		return ret
	}
	return *o.TaxId
}

// GetTaxIdOk returns a tuple with the TaxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *A2pRegistrationUpdateRequest) GetTaxIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaxId) {
		return nil, false
	}
	return o.TaxId, true
}

// HasTaxId returns a boolean if a field has been set.
func (o *A2pRegistrationUpdateRequest) HasTaxId() bool {
	if o != nil && !IsNil(o.TaxId) {
		return true
	}

	return false
}

// SetTaxId gets a reference to the given string and assigns it to the TaxId field.
func (o *A2pRegistrationUpdateRequest) SetTaxId(v string) {
	o.TaxId = &v
}

// GetWebsite returns the Website field value if set, zero value otherwise.
func (o *A2pRegistrationUpdateRequest) GetWebsite() string {
	if o == nil || IsNil(o.Website) {
		var ret string
		return ret
	}
	return *o.Website
}

// GetWebsiteOk returns a tuple with the Website field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *A2pRegistrationUpdateRequest) GetWebsiteOk() (*string, bool) {
	if o == nil || IsNil(o.Website) {
		return nil, false
	}
	return o.Website, true
}

// HasWebsite returns a boolean if a field has been set.
func (o *A2pRegistrationUpdateRequest) HasWebsite() bool {
	if o != nil && !IsNil(o.Website) {
		return true
	}

	return false
}

// SetWebsite gets a reference to the given string and assigns it to the Website field.
func (o *A2pRegistrationUpdateRequest) SetWebsite(v string) {
	o.Website = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *A2pRegistrationUpdateRequest) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *A2pRegistrationUpdateRequest) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *A2pRegistrationUpdateRequest) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *A2pRegistrationUpdateRequest) SetCountry(v string) {
	o.Country = &v
}

// GetFullAddress returns the FullAddress field value if set, zero value otherwise.
func (o *A2pRegistrationUpdateRequest) GetFullAddress() string {
	if o == nil || IsNil(o.FullAddress) {
		var ret string
		return ret
	}
	return *o.FullAddress
}

// GetFullAddressOk returns a tuple with the FullAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *A2pRegistrationUpdateRequest) GetFullAddressOk() (*string, bool) {
	if o == nil || IsNil(o.FullAddress) {
		return nil, false
	}
	return o.FullAddress, true
}

// HasFullAddress returns a boolean if a field has been set.
func (o *A2pRegistrationUpdateRequest) HasFullAddress() bool {
	if o != nil && !IsNil(o.FullAddress) {
		return true
	}

	return false
}

// SetFullAddress gets a reference to the given string and assigns it to the FullAddress field.
func (o *A2pRegistrationUpdateRequest) SetFullAddress(v string) {
	o.FullAddress = &v
}

// GetComplianceContactEmail returns the ComplianceContactEmail field value if set, zero value otherwise.
func (o *A2pRegistrationUpdateRequest) GetComplianceContactEmail() string {
	if o == nil || IsNil(o.ComplianceContactEmail) {
		var ret string
		return ret
	}
	return *o.ComplianceContactEmail
}

// GetComplianceContactEmailOk returns a tuple with the ComplianceContactEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *A2pRegistrationUpdateRequest) GetComplianceContactEmailOk() (*string, bool) {
	if o == nil || IsNil(o.ComplianceContactEmail) {
		return nil, false
	}
	return o.ComplianceContactEmail, true
}

// HasComplianceContactEmail returns a boolean if a field has been set.
func (o *A2pRegistrationUpdateRequest) HasComplianceContactEmail() bool {
	if o != nil && !IsNil(o.ComplianceContactEmail) {
		return true
	}

	return false
}

// SetComplianceContactEmail gets a reference to the given string and assigns it to the ComplianceContactEmail field.
func (o *A2pRegistrationUpdateRequest) SetComplianceContactEmail(v string) {
	o.ComplianceContactEmail = &v
}

// GetComplianceContactPhone returns the ComplianceContactPhone field value if set, zero value otherwise.
func (o *A2pRegistrationUpdateRequest) GetComplianceContactPhone() string {
	if o == nil || IsNil(o.ComplianceContactPhone) {
		var ret string
		return ret
	}
	return *o.ComplianceContactPhone
}

// GetComplianceContactPhoneOk returns a tuple with the ComplianceContactPhone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *A2pRegistrationUpdateRequest) GetComplianceContactPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.ComplianceContactPhone) {
		return nil, false
	}
	return o.ComplianceContactPhone, true
}

// HasComplianceContactPhone returns a boolean if a field has been set.
func (o *A2pRegistrationUpdateRequest) HasComplianceContactPhone() bool {
	if o != nil && !IsNil(o.ComplianceContactPhone) {
		return true
	}

	return false
}

// SetComplianceContactPhone gets a reference to the given string and assigns it to the ComplianceContactPhone field.
func (o *A2pRegistrationUpdateRequest) SetComplianceContactPhone(v string) {
	o.ComplianceContactPhone = &v
}

func (o A2pRegistrationUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o A2pRegistrationUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ScenarioId) {
		toSerialize["scenarioId"] = o.ScenarioId
	}
	if !IsNil(o.BusinessType) {
		toSerialize["businessType"] = o.BusinessType
	}
	if !IsNil(o.LegalName) {
		toSerialize["legalName"] = o.LegalName
	}
	if !IsNil(o.TaxId) {
		toSerialize["taxId"] = o.TaxId
	}
	if !IsNil(o.Website) {
		toSerialize["website"] = o.Website
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.FullAddress) {
		toSerialize["fullAddress"] = o.FullAddress
	}
	if !IsNil(o.ComplianceContactEmail) {
		toSerialize["complianceContactEmail"] = o.ComplianceContactEmail
	}
	if !IsNil(o.ComplianceContactPhone) {
		toSerialize["complianceContactPhone"] = o.ComplianceContactPhone
	}
	return toSerialize, nil
}

type NullableA2pRegistrationUpdateRequest struct {
	value *A2pRegistrationUpdateRequest
	isSet bool
}

func (v NullableA2pRegistrationUpdateRequest) Get() *A2pRegistrationUpdateRequest {
	return v.value
}

func (v *NullableA2pRegistrationUpdateRequest) Set(val *A2pRegistrationUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableA2pRegistrationUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableA2pRegistrationUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableA2pRegistrationUpdateRequest(val *A2pRegistrationUpdateRequest) *NullableA2pRegistrationUpdateRequest {
	return &NullableA2pRegistrationUpdateRequest{value: val, isSet: true}
}

func (v NullableA2pRegistrationUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableA2pRegistrationUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
