/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetVoiceCallResponseCall type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVoiceCallResponseCall{}

// GetVoiceCallResponseCall struct for GetVoiceCallResponseCall
type GetVoiceCallResponseCall struct {
	TrackingId string `json:"trackingId"`
	Status     string `json:"status"`
	// Omitted for playground calls made before the agent was saved.
	AgentId         *string `json:"agentId,omitempty"`
	AgentName       string  `json:"agentName"`
	Direction       string  `json:"direction"`
	Source          string  `json:"source"`
	From            string  `json:"from"`
	To              string  `json:"to"`
	StartedAt       string  `json:"startedAt"`
	DurationSeconds float32 `json:"durationSeconds"`
	Outcome         *string `json:"outcome,omitempty"`
	// Machine-readable reason the call ended — persisted on every call record.
	EndReason *string `json:"endReason,omitempty"`
	// Short human-readable detail (e.g. provider error message).
	EndDetail *string `json:"endDetail,omitempty"`
	// Full chronological timeline (transcript + ops events).
	Timeline     []GetVoiceCallResponseCallTimelineInner `json:"timeline"`
	RecordingUrl *string                                 `json:"recordingUrl,omitempty"`
	Variables    *map[string]string                      `json:"variables,omitempty"`
	Cost         *GetVoiceCallResponseCallCost           `json:"cost,omitempty"`
}

type _GetVoiceCallResponseCall GetVoiceCallResponseCall

// NewGetVoiceCallResponseCall instantiates a new GetVoiceCallResponseCall object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVoiceCallResponseCall(trackingId string, status string, agentName string, direction string, source string, from string, to string, startedAt string, durationSeconds float32, timeline []GetVoiceCallResponseCallTimelineInner) *GetVoiceCallResponseCall {
	this := GetVoiceCallResponseCall{}
	this.TrackingId = trackingId
	this.Status = status
	this.AgentName = agentName
	this.Direction = direction
	this.Source = source
	this.From = from
	this.To = to
	this.StartedAt = startedAt
	this.DurationSeconds = durationSeconds
	this.Timeline = timeline
	return &this
}

// NewGetVoiceCallResponseCallWithDefaults instantiates a new GetVoiceCallResponseCall object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVoiceCallResponseCallWithDefaults() *GetVoiceCallResponseCall {
	this := GetVoiceCallResponseCall{}
	return &this
}

// GetTrackingId returns the TrackingId field value
func (o *GetVoiceCallResponseCall) GetTrackingId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TrackingId
}

// GetTrackingIdOk returns a tuple with the TrackingId field value
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetTrackingIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrackingId, true
}

// SetTrackingId sets field value
func (o *GetVoiceCallResponseCall) SetTrackingId(v string) {
	o.TrackingId = v
}

// GetStatus returns the Status field value
func (o *GetVoiceCallResponseCall) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetVoiceCallResponseCall) SetStatus(v string) {
	o.Status = v
}

// GetAgentId returns the AgentId field value if set, zero value otherwise.
func (o *GetVoiceCallResponseCall) GetAgentId() string {
	if o == nil || IsNil(o.AgentId) {
		var ret string
		return ret
	}
	return *o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.AgentId) {
		return nil, false
	}
	return o.AgentId, true
}

// HasAgentId returns a boolean if a field has been set.
func (o *GetVoiceCallResponseCall) HasAgentId() bool {
	if o != nil && !IsNil(o.AgentId) {
		return true
	}

	return false
}

// SetAgentId gets a reference to the given string and assigns it to the AgentId field.
func (o *GetVoiceCallResponseCall) SetAgentId(v string) {
	o.AgentId = &v
}

// GetAgentName returns the AgentName field value
func (o *GetVoiceCallResponseCall) GetAgentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetAgentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentName, true
}

// SetAgentName sets field value
func (o *GetVoiceCallResponseCall) SetAgentName(v string) {
	o.AgentName = v
}

// GetDirection returns the Direction field value
func (o *GetVoiceCallResponseCall) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *GetVoiceCallResponseCall) SetDirection(v string) {
	o.Direction = v
}

// GetSource returns the Source field value
func (o *GetVoiceCallResponseCall) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *GetVoiceCallResponseCall) SetSource(v string) {
	o.Source = v
}

// GetFrom returns the From field value
func (o *GetVoiceCallResponseCall) GetFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *GetVoiceCallResponseCall) SetFrom(v string) {
	o.From = v
}

// GetTo returns the To field value
func (o *GetVoiceCallResponseCall) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *GetVoiceCallResponseCall) SetTo(v string) {
	o.To = v
}

// GetStartedAt returns the StartedAt field value
func (o *GetVoiceCallResponseCall) GetStartedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetStartedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartedAt, true
}

// SetStartedAt sets field value
func (o *GetVoiceCallResponseCall) SetStartedAt(v string) {
	o.StartedAt = v
}

// GetDurationSeconds returns the DurationSeconds field value
func (o *GetVoiceCallResponseCall) GetDurationSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DurationSeconds
}

// GetDurationSecondsOk returns a tuple with the DurationSeconds field value
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetDurationSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationSeconds, true
}

// SetDurationSeconds sets field value
func (o *GetVoiceCallResponseCall) SetDurationSeconds(v float32) {
	o.DurationSeconds = v
}

// GetOutcome returns the Outcome field value if set, zero value otherwise.
func (o *GetVoiceCallResponseCall) GetOutcome() string {
	if o == nil || IsNil(o.Outcome) {
		var ret string
		return ret
	}
	return *o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetOutcomeOk() (*string, bool) {
	if o == nil || IsNil(o.Outcome) {
		return nil, false
	}
	return o.Outcome, true
}

// HasOutcome returns a boolean if a field has been set.
func (o *GetVoiceCallResponseCall) HasOutcome() bool {
	if o != nil && !IsNil(o.Outcome) {
		return true
	}

	return false
}

// SetOutcome gets a reference to the given string and assigns it to the Outcome field.
func (o *GetVoiceCallResponseCall) SetOutcome(v string) {
	o.Outcome = &v
}

// GetEndReason returns the EndReason field value if set, zero value otherwise.
func (o *GetVoiceCallResponseCall) GetEndReason() string {
	if o == nil || IsNil(o.EndReason) {
		var ret string
		return ret
	}
	return *o.EndReason
}

// GetEndReasonOk returns a tuple with the EndReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetEndReasonOk() (*string, bool) {
	if o == nil || IsNil(o.EndReason) {
		return nil, false
	}
	return o.EndReason, true
}

// HasEndReason returns a boolean if a field has been set.
func (o *GetVoiceCallResponseCall) HasEndReason() bool {
	if o != nil && !IsNil(o.EndReason) {
		return true
	}

	return false
}

// SetEndReason gets a reference to the given string and assigns it to the EndReason field.
func (o *GetVoiceCallResponseCall) SetEndReason(v string) {
	o.EndReason = &v
}

// GetEndDetail returns the EndDetail field value if set, zero value otherwise.
func (o *GetVoiceCallResponseCall) GetEndDetail() string {
	if o == nil || IsNil(o.EndDetail) {
		var ret string
		return ret
	}
	return *o.EndDetail
}

// GetEndDetailOk returns a tuple with the EndDetail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetEndDetailOk() (*string, bool) {
	if o == nil || IsNil(o.EndDetail) {
		return nil, false
	}
	return o.EndDetail, true
}

// HasEndDetail returns a boolean if a field has been set.
func (o *GetVoiceCallResponseCall) HasEndDetail() bool {
	if o != nil && !IsNil(o.EndDetail) {
		return true
	}

	return false
}

// SetEndDetail gets a reference to the given string and assigns it to the EndDetail field.
func (o *GetVoiceCallResponseCall) SetEndDetail(v string) {
	o.EndDetail = &v
}

// GetTimeline returns the Timeline field value
func (o *GetVoiceCallResponseCall) GetTimeline() []GetVoiceCallResponseCallTimelineInner {
	if o == nil {
		var ret []GetVoiceCallResponseCallTimelineInner
		return ret
	}

	return o.Timeline
}

// GetTimelineOk returns a tuple with the Timeline field value
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetTimelineOk() ([]GetVoiceCallResponseCallTimelineInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timeline, true
}

// SetTimeline sets field value
func (o *GetVoiceCallResponseCall) SetTimeline(v []GetVoiceCallResponseCallTimelineInner) {
	o.Timeline = v
}

// GetRecordingUrl returns the RecordingUrl field value if set, zero value otherwise.
func (o *GetVoiceCallResponseCall) GetRecordingUrl() string {
	if o == nil || IsNil(o.RecordingUrl) {
		var ret string
		return ret
	}
	return *o.RecordingUrl
}

// GetRecordingUrlOk returns a tuple with the RecordingUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetRecordingUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RecordingUrl) {
		return nil, false
	}
	return o.RecordingUrl, true
}

// HasRecordingUrl returns a boolean if a field has been set.
func (o *GetVoiceCallResponseCall) HasRecordingUrl() bool {
	if o != nil && !IsNil(o.RecordingUrl) {
		return true
	}

	return false
}

// SetRecordingUrl gets a reference to the given string and assigns it to the RecordingUrl field.
func (o *GetVoiceCallResponseCall) SetRecordingUrl(v string) {
	o.RecordingUrl = &v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *GetVoiceCallResponseCall) GetVariables() map[string]string {
	if o == nil || IsNil(o.Variables) {
		var ret map[string]string
		return ret
	}
	return *o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetVariablesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Variables) {
		return nil, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *GetVoiceCallResponseCall) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given map[string]string and assigns it to the Variables field.
func (o *GetVoiceCallResponseCall) SetVariables(v map[string]string) {
	o.Variables = &v
}

// GetCost returns the Cost field value if set, zero value otherwise.
func (o *GetVoiceCallResponseCall) GetCost() GetVoiceCallResponseCallCost {
	if o == nil || IsNil(o.Cost) {
		var ret GetVoiceCallResponseCallCost
		return ret
	}
	return *o.Cost
}

// GetCostOk returns a tuple with the Cost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVoiceCallResponseCall) GetCostOk() (*GetVoiceCallResponseCallCost, bool) {
	if o == nil || IsNil(o.Cost) {
		return nil, false
	}
	return o.Cost, true
}

// HasCost returns a boolean if a field has been set.
func (o *GetVoiceCallResponseCall) HasCost() bool {
	if o != nil && !IsNil(o.Cost) {
		return true
	}

	return false
}

// SetCost gets a reference to the given GetVoiceCallResponseCallCost and assigns it to the Cost field.
func (o *GetVoiceCallResponseCall) SetCost(v GetVoiceCallResponseCallCost) {
	o.Cost = &v
}

func (o GetVoiceCallResponseCall) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVoiceCallResponseCall) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["trackingId"] = o.TrackingId
	toSerialize["status"] = o.Status
	if !IsNil(o.AgentId) {
		toSerialize["agentId"] = o.AgentId
	}
	toSerialize["agentName"] = o.AgentName
	toSerialize["direction"] = o.Direction
	toSerialize["source"] = o.Source
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	toSerialize["startedAt"] = o.StartedAt
	toSerialize["durationSeconds"] = o.DurationSeconds
	if !IsNil(o.Outcome) {
		toSerialize["outcome"] = o.Outcome
	}
	if !IsNil(o.EndReason) {
		toSerialize["endReason"] = o.EndReason
	}
	if !IsNil(o.EndDetail) {
		toSerialize["endDetail"] = o.EndDetail
	}
	toSerialize["timeline"] = o.Timeline
	if !IsNil(o.RecordingUrl) {
		toSerialize["recordingUrl"] = o.RecordingUrl
	}
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	if !IsNil(o.Cost) {
		toSerialize["cost"] = o.Cost
	}
	return toSerialize, nil
}

func (o *GetVoiceCallResponseCall) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"trackingId",
		"status",
		"agentName",
		"direction",
		"source",
		"from",
		"to",
		"startedAt",
		"durationSeconds",
		"timeline",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetVoiceCallResponseCall := _GetVoiceCallResponseCall{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetVoiceCallResponseCall)

	if err != nil {
		return err
	}

	*o = GetVoiceCallResponseCall(varGetVoiceCallResponseCall)

	return err
}

type NullableGetVoiceCallResponseCall struct {
	value *GetVoiceCallResponseCall
	isSet bool
}

func (v NullableGetVoiceCallResponseCall) Get() *GetVoiceCallResponseCall {
	return v.value
}

func (v *NullableGetVoiceCallResponseCall) Set(val *GetVoiceCallResponseCall) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVoiceCallResponseCall) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVoiceCallResponseCall) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVoiceCallResponseCall(val *GetVoiceCallResponseCall) *NullableGetVoiceCallResponseCall {
	return &NullableGetVoiceCallResponseCall{value: val, isSet: true}
}

func (v NullableGetVoiceCallResponseCall) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVoiceCallResponseCall) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
