/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateLibraryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLibraryResponse{}

// CreateLibraryResponse struct for CreateLibraryResponse
type CreateLibraryResponse struct {
	Id       string `json:"id"`
	UseCase  string `json:"useCase"`
	Filename string `json:"filename"`
	Key      string `json:"key"`
	// Public URL to use in emails after the file is uploaded to uploadUrl.
	Url string `json:"url"`
	// Time-limited upload URL. PUT the file bytes with the same Content-Type.
	UploadUrl   string `json:"uploadUrl"`
	ContentType string `json:"contentType"`
}

type _CreateLibraryResponse CreateLibraryResponse

// NewCreateLibraryResponse instantiates a new CreateLibraryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLibraryResponse(id string, useCase string, filename string, key string, url string, uploadUrl string, contentType string) *CreateLibraryResponse {
	this := CreateLibraryResponse{}
	this.Id = id
	this.UseCase = useCase
	this.Filename = filename
	this.Key = key
	this.Url = url
	this.UploadUrl = uploadUrl
	this.ContentType = contentType
	return &this
}

// NewCreateLibraryResponseWithDefaults instantiates a new CreateLibraryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLibraryResponseWithDefaults() *CreateLibraryResponse {
	this := CreateLibraryResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CreateLibraryResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateLibraryResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateLibraryResponse) SetId(v string) {
	o.Id = v
}

// GetUseCase returns the UseCase field value
func (o *CreateLibraryResponse) GetUseCase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UseCase
}

// GetUseCaseOk returns a tuple with the UseCase field value
// and a boolean to check if the value has been set.
func (o *CreateLibraryResponse) GetUseCaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UseCase, true
}

// SetUseCase sets field value
func (o *CreateLibraryResponse) SetUseCase(v string) {
	o.UseCase = v
}

// GetFilename returns the Filename field value
func (o *CreateLibraryResponse) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *CreateLibraryResponse) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *CreateLibraryResponse) SetFilename(v string) {
	o.Filename = v
}

// GetKey returns the Key field value
func (o *CreateLibraryResponse) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *CreateLibraryResponse) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *CreateLibraryResponse) SetKey(v string) {
	o.Key = v
}

// GetUrl returns the Url field value
func (o *CreateLibraryResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CreateLibraryResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CreateLibraryResponse) SetUrl(v string) {
	o.Url = v
}

// GetUploadUrl returns the UploadUrl field value
func (o *CreateLibraryResponse) GetUploadUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UploadUrl
}

// GetUploadUrlOk returns a tuple with the UploadUrl field value
// and a boolean to check if the value has been set.
func (o *CreateLibraryResponse) GetUploadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadUrl, true
}

// SetUploadUrl sets field value
func (o *CreateLibraryResponse) SetUploadUrl(v string) {
	o.UploadUrl = v
}

// GetContentType returns the ContentType field value
func (o *CreateLibraryResponse) GetContentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *CreateLibraryResponse) GetContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *CreateLibraryResponse) SetContentType(v string) {
	o.ContentType = v
}

func (o CreateLibraryResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLibraryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["useCase"] = o.UseCase
	toSerialize["filename"] = o.Filename
	toSerialize["key"] = o.Key
	toSerialize["url"] = o.Url
	toSerialize["uploadUrl"] = o.UploadUrl
	toSerialize["contentType"] = o.ContentType
	return toSerialize, nil
}

func (o *CreateLibraryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"useCase",
		"filename",
		"key",
		"url",
		"uploadUrl",
		"contentType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateLibraryResponse := _CreateLibraryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateLibraryResponse)

	if err != nil {
		return err
	}

	*o = CreateLibraryResponse(varCreateLibraryResponse)

	return err
}

type NullableCreateLibraryResponse struct {
	value *CreateLibraryResponse
	isSet bool
}

func (v NullableCreateLibraryResponse) Get() *CreateLibraryResponse {
	return v.value
}

func (v *NullableCreateLibraryResponse) Set(val *CreateLibraryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLibraryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLibraryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLibraryResponse(val *CreateLibraryResponse) *NullableCreateLibraryResponse {
	return &NullableCreateLibraryResponse{value: val, isSet: true}
}

func (v NullableCreateLibraryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLibraryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
