/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TemplatePostRequestBatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplatePostRequestBatch{}

// TemplatePostRequestBatch Copy for batch delivery.
type TemplatePostRequestBatch struct {
	Title       string `json:"title"`
	RedirectURL string `json:"redirectURL"`
	ImageURL    string `json:"imageURL"`
}

type _TemplatePostRequestBatch TemplatePostRequestBatch

// NewTemplatePostRequestBatch instantiates a new TemplatePostRequestBatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplatePostRequestBatch(title string, redirectURL string, imageURL string) *TemplatePostRequestBatch {
	this := TemplatePostRequestBatch{}
	this.Title = title
	this.RedirectURL = redirectURL
	this.ImageURL = imageURL
	return &this
}

// NewTemplatePostRequestBatchWithDefaults instantiates a new TemplatePostRequestBatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplatePostRequestBatchWithDefaults() *TemplatePostRequestBatch {
	this := TemplatePostRequestBatch{}
	return &this
}

// GetTitle returns the Title field value
func (o *TemplatePostRequestBatch) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *TemplatePostRequestBatch) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *TemplatePostRequestBatch) SetTitle(v string) {
	o.Title = v
}

// GetRedirectURL returns the RedirectURL field value
func (o *TemplatePostRequestBatch) GetRedirectURL() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RedirectURL
}

// GetRedirectURLOk returns a tuple with the RedirectURL field value
// and a boolean to check if the value has been set.
func (o *TemplatePostRequestBatch) GetRedirectURLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RedirectURL, true
}

// SetRedirectURL sets field value
func (o *TemplatePostRequestBatch) SetRedirectURL(v string) {
	o.RedirectURL = v
}

// GetImageURL returns the ImageURL field value
func (o *TemplatePostRequestBatch) GetImageURL() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageURL
}

// GetImageURLOk returns a tuple with the ImageURL field value
// and a boolean to check if the value has been set.
func (o *TemplatePostRequestBatch) GetImageURLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageURL, true
}

// SetImageURL sets field value
func (o *TemplatePostRequestBatch) SetImageURL(v string) {
	o.ImageURL = v
}

func (o TemplatePostRequestBatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplatePostRequestBatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	toSerialize["redirectURL"] = o.RedirectURL
	toSerialize["imageURL"] = o.ImageURL
	return toSerialize, nil
}

func (o *TemplatePostRequestBatch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"redirectURL",
		"imageURL",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplatePostRequestBatch := _TemplatePostRequestBatch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplatePostRequestBatch)

	if err != nil {
		return err
	}

	*o = TemplatePostRequestBatch(varTemplatePostRequestBatch)

	return err
}

type NullableTemplatePostRequestBatch struct {
	value *TemplatePostRequestBatch
	isSet bool
}

func (v NullableTemplatePostRequestBatch) Get() *TemplatePostRequestBatch {
	return v.value
}

func (v *NullableTemplatePostRequestBatch) Set(val *TemplatePostRequestBatch) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplatePostRequestBatch) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplatePostRequestBatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplatePostRequestBatch(val *TemplatePostRequestBatch) *NullableTemplatePostRequestBatch {
	return &NullableTemplatePostRequestBatch{value: val, isSet: true}
}

func (v NullableTemplatePostRequestBatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplatePostRequestBatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
