/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetTemplatesListResponseInnerAnyOf6 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTemplatesListResponseInnerAnyOf6{}

// GetTemplatesListResponseInnerAnyOf6 struct for GetTemplatesListResponseInnerAnyOf6
type GetTemplatesListResponseInnerAnyOf6 struct {
	EnvId          string                                       `json:"envId"`
	NotificationId string                                       `json:"notificationId"`
	TemplateId     string                                       `json:"templateId"`
	Channel        ChannelsEnum                                 `json:"channel"`
	Default        bool                                         `json:"default"`
	IsDefaultFor   *map[string]bool                             `json:"isDefaultFor,omitempty"`
	Text           string                                       `json:"text"`
	Blocks         []map[string]interface{}                     `json:"blocks,omitempty"`
	Username       *string                                      `json:"username,omitempty"`
	Icon           *string                                      `json:"icon,omitempty"`
	ThreadTs       *string                                      `json:"thread_ts,omitempty"`
	ReplyBroadcast *bool                                        `json:"reply_broadcast,omitempty"`
	Parse          *string                                      `json:"parse,omitempty"`
	LinkNames      *bool                                        `json:"link_names,omitempty"`
	Mrkdwn         *bool                                        `json:"mrkdwn,omitempty"`
	UnfurlLinks    *bool                                        `json:"unfurl_links,omitempty"`
	UnfurlMedia    *bool                                        `json:"unfurl_media,omitempty"`
	Metadata       *GetTemplatesListResponseInnerAnyOf6Metadata `json:"metadata,omitempty"`
}

type _GetTemplatesListResponseInnerAnyOf6 GetTemplatesListResponseInnerAnyOf6

// NewGetTemplatesListResponseInnerAnyOf6 instantiates a new GetTemplatesListResponseInnerAnyOf6 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTemplatesListResponseInnerAnyOf6(envId string, notificationId string, templateId string, channel ChannelsEnum, default_ bool, text string) *GetTemplatesListResponseInnerAnyOf6 {
	this := GetTemplatesListResponseInnerAnyOf6{}
	this.EnvId = envId
	this.NotificationId = notificationId
	this.TemplateId = templateId
	this.Channel = channel
	this.Default = default_
	this.Text = text
	return &this
}

// NewGetTemplatesListResponseInnerAnyOf6WithDefaults instantiates a new GetTemplatesListResponseInnerAnyOf6 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTemplatesListResponseInnerAnyOf6WithDefaults() *GetTemplatesListResponseInnerAnyOf6 {
	this := GetTemplatesListResponseInnerAnyOf6{}
	return &this
}

// GetEnvId returns the EnvId field value
func (o *GetTemplatesListResponseInnerAnyOf6) GetEnvId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvId
}

// GetEnvIdOk returns a tuple with the EnvId field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetEnvIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvId, true
}

// SetEnvId sets field value
func (o *GetTemplatesListResponseInnerAnyOf6) SetEnvId(v string) {
	o.EnvId = v
}

// GetNotificationId returns the NotificationId field value
func (o *GetTemplatesListResponseInnerAnyOf6) GetNotificationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NotificationId
}

// GetNotificationIdOk returns a tuple with the NotificationId field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetNotificationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotificationId, true
}

// SetNotificationId sets field value
func (o *GetTemplatesListResponseInnerAnyOf6) SetNotificationId(v string) {
	o.NotificationId = v
}

// GetTemplateId returns the TemplateId field value
func (o *GetTemplatesListResponseInnerAnyOf6) GetTemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateId, true
}

// SetTemplateId sets field value
func (o *GetTemplatesListResponseInnerAnyOf6) SetTemplateId(v string) {
	o.TemplateId = v
}

// GetChannel returns the Channel field value
func (o *GetTemplatesListResponseInnerAnyOf6) GetChannel() ChannelsEnum {
	if o == nil {
		var ret ChannelsEnum
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetChannelOk() (*ChannelsEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *GetTemplatesListResponseInnerAnyOf6) SetChannel(v ChannelsEnum) {
	o.Channel = v
}

// GetDefault returns the Default field value
func (o *GetTemplatesListResponseInnerAnyOf6) GetDefault() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetDefaultOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Default, true
}

// SetDefault sets field value
func (o *GetTemplatesListResponseInnerAnyOf6) SetDefault(v bool) {
	o.Default = v
}

// GetIsDefaultFor returns the IsDefaultFor field value if set, zero value otherwise.
func (o *GetTemplatesListResponseInnerAnyOf6) GetIsDefaultFor() map[string]bool {
	if o == nil || IsNil(o.IsDefaultFor) {
		var ret map[string]bool
		return ret
	}
	return *o.IsDefaultFor
}

// GetIsDefaultForOk returns a tuple with the IsDefaultFor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetIsDefaultForOk() (*map[string]bool, bool) {
	if o == nil || IsNil(o.IsDefaultFor) {
		return nil, false
	}
	return o.IsDefaultFor, true
}

// HasIsDefaultFor returns a boolean if a field has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) HasIsDefaultFor() bool {
	if o != nil && !IsNil(o.IsDefaultFor) {
		return true
	}

	return false
}

// SetIsDefaultFor gets a reference to the given map[string]bool and assigns it to the IsDefaultFor field.
func (o *GetTemplatesListResponseInnerAnyOf6) SetIsDefaultFor(v map[string]bool) {
	o.IsDefaultFor = &v
}

// GetText returns the Text field value
func (o *GetTemplatesListResponseInnerAnyOf6) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *GetTemplatesListResponseInnerAnyOf6) SetText(v string) {
	o.Text = v
}

// GetBlocks returns the Blocks field value if set, zero value otherwise.
func (o *GetTemplatesListResponseInnerAnyOf6) GetBlocks() []map[string]interface{} {
	if o == nil || IsNil(o.Blocks) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Blocks
}

// GetBlocksOk returns a tuple with the Blocks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetBlocksOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Blocks) {
		return nil, false
	}
	return o.Blocks, true
}

// HasBlocks returns a boolean if a field has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) HasBlocks() bool {
	if o != nil && !IsNil(o.Blocks) {
		return true
	}

	return false
}

// SetBlocks gets a reference to the given []map[string]interface{} and assigns it to the Blocks field.
func (o *GetTemplatesListResponseInnerAnyOf6) SetBlocks(v []map[string]interface{}) {
	o.Blocks = v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *GetTemplatesListResponseInnerAnyOf6) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *GetTemplatesListResponseInnerAnyOf6) SetUsername(v string) {
	o.Username = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *GetTemplatesListResponseInnerAnyOf6) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *GetTemplatesListResponseInnerAnyOf6) SetIcon(v string) {
	o.Icon = &v
}

// GetThreadTs returns the ThreadTs field value if set, zero value otherwise.
func (o *GetTemplatesListResponseInnerAnyOf6) GetThreadTs() string {
	if o == nil || IsNil(o.ThreadTs) {
		var ret string
		return ret
	}
	return *o.ThreadTs
}

// GetThreadTsOk returns a tuple with the ThreadTs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetThreadTsOk() (*string, bool) {
	if o == nil || IsNil(o.ThreadTs) {
		return nil, false
	}
	return o.ThreadTs, true
}

// HasThreadTs returns a boolean if a field has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) HasThreadTs() bool {
	if o != nil && !IsNil(o.ThreadTs) {
		return true
	}

	return false
}

// SetThreadTs gets a reference to the given string and assigns it to the ThreadTs field.
func (o *GetTemplatesListResponseInnerAnyOf6) SetThreadTs(v string) {
	o.ThreadTs = &v
}

// GetReplyBroadcast returns the ReplyBroadcast field value if set, zero value otherwise.
func (o *GetTemplatesListResponseInnerAnyOf6) GetReplyBroadcast() bool {
	if o == nil || IsNil(o.ReplyBroadcast) {
		var ret bool
		return ret
	}
	return *o.ReplyBroadcast
}

// GetReplyBroadcastOk returns a tuple with the ReplyBroadcast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetReplyBroadcastOk() (*bool, bool) {
	if o == nil || IsNil(o.ReplyBroadcast) {
		return nil, false
	}
	return o.ReplyBroadcast, true
}

// HasReplyBroadcast returns a boolean if a field has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) HasReplyBroadcast() bool {
	if o != nil && !IsNil(o.ReplyBroadcast) {
		return true
	}

	return false
}

// SetReplyBroadcast gets a reference to the given bool and assigns it to the ReplyBroadcast field.
func (o *GetTemplatesListResponseInnerAnyOf6) SetReplyBroadcast(v bool) {
	o.ReplyBroadcast = &v
}

// GetParse returns the Parse field value if set, zero value otherwise.
func (o *GetTemplatesListResponseInnerAnyOf6) GetParse() string {
	if o == nil || IsNil(o.Parse) {
		var ret string
		return ret
	}
	return *o.Parse
}

// GetParseOk returns a tuple with the Parse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetParseOk() (*string, bool) {
	if o == nil || IsNil(o.Parse) {
		return nil, false
	}
	return o.Parse, true
}

// HasParse returns a boolean if a field has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) HasParse() bool {
	if o != nil && !IsNil(o.Parse) {
		return true
	}

	return false
}

// SetParse gets a reference to the given string and assigns it to the Parse field.
func (o *GetTemplatesListResponseInnerAnyOf6) SetParse(v string) {
	o.Parse = &v
}

// GetLinkNames returns the LinkNames field value if set, zero value otherwise.
func (o *GetTemplatesListResponseInnerAnyOf6) GetLinkNames() bool {
	if o == nil || IsNil(o.LinkNames) {
		var ret bool
		return ret
	}
	return *o.LinkNames
}

// GetLinkNamesOk returns a tuple with the LinkNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetLinkNamesOk() (*bool, bool) {
	if o == nil || IsNil(o.LinkNames) {
		return nil, false
	}
	return o.LinkNames, true
}

// HasLinkNames returns a boolean if a field has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) HasLinkNames() bool {
	if o != nil && !IsNil(o.LinkNames) {
		return true
	}

	return false
}

// SetLinkNames gets a reference to the given bool and assigns it to the LinkNames field.
func (o *GetTemplatesListResponseInnerAnyOf6) SetLinkNames(v bool) {
	o.LinkNames = &v
}

// GetMrkdwn returns the Mrkdwn field value if set, zero value otherwise.
func (o *GetTemplatesListResponseInnerAnyOf6) GetMrkdwn() bool {
	if o == nil || IsNil(o.Mrkdwn) {
		var ret bool
		return ret
	}
	return *o.Mrkdwn
}

// GetMrkdwnOk returns a tuple with the Mrkdwn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetMrkdwnOk() (*bool, bool) {
	if o == nil || IsNil(o.Mrkdwn) {
		return nil, false
	}
	return o.Mrkdwn, true
}

// HasMrkdwn returns a boolean if a field has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) HasMrkdwn() bool {
	if o != nil && !IsNil(o.Mrkdwn) {
		return true
	}

	return false
}

// SetMrkdwn gets a reference to the given bool and assigns it to the Mrkdwn field.
func (o *GetTemplatesListResponseInnerAnyOf6) SetMrkdwn(v bool) {
	o.Mrkdwn = &v
}

// GetUnfurlLinks returns the UnfurlLinks field value if set, zero value otherwise.
func (o *GetTemplatesListResponseInnerAnyOf6) GetUnfurlLinks() bool {
	if o == nil || IsNil(o.UnfurlLinks) {
		var ret bool
		return ret
	}
	return *o.UnfurlLinks
}

// GetUnfurlLinksOk returns a tuple with the UnfurlLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetUnfurlLinksOk() (*bool, bool) {
	if o == nil || IsNil(o.UnfurlLinks) {
		return nil, false
	}
	return o.UnfurlLinks, true
}

// HasUnfurlLinks returns a boolean if a field has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) HasUnfurlLinks() bool {
	if o != nil && !IsNil(o.UnfurlLinks) {
		return true
	}

	return false
}

// SetUnfurlLinks gets a reference to the given bool and assigns it to the UnfurlLinks field.
func (o *GetTemplatesListResponseInnerAnyOf6) SetUnfurlLinks(v bool) {
	o.UnfurlLinks = &v
}

// GetUnfurlMedia returns the UnfurlMedia field value if set, zero value otherwise.
func (o *GetTemplatesListResponseInnerAnyOf6) GetUnfurlMedia() bool {
	if o == nil || IsNil(o.UnfurlMedia) {
		var ret bool
		return ret
	}
	return *o.UnfurlMedia
}

// GetUnfurlMediaOk returns a tuple with the UnfurlMedia field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetUnfurlMediaOk() (*bool, bool) {
	if o == nil || IsNil(o.UnfurlMedia) {
		return nil, false
	}
	return o.UnfurlMedia, true
}

// HasUnfurlMedia returns a boolean if a field has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) HasUnfurlMedia() bool {
	if o != nil && !IsNil(o.UnfurlMedia) {
		return true
	}

	return false
}

// SetUnfurlMedia gets a reference to the given bool and assigns it to the UnfurlMedia field.
func (o *GetTemplatesListResponseInnerAnyOf6) SetUnfurlMedia(v bool) {
	o.UnfurlMedia = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *GetTemplatesListResponseInnerAnyOf6) GetMetadata() GetTemplatesListResponseInnerAnyOf6Metadata {
	if o == nil || IsNil(o.Metadata) {
		var ret GetTemplatesListResponseInnerAnyOf6Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) GetMetadataOk() (*GetTemplatesListResponseInnerAnyOf6Metadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *GetTemplatesListResponseInnerAnyOf6) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given GetTemplatesListResponseInnerAnyOf6Metadata and assigns it to the Metadata field.
func (o *GetTemplatesListResponseInnerAnyOf6) SetMetadata(v GetTemplatesListResponseInnerAnyOf6Metadata) {
	o.Metadata = &v
}

func (o GetTemplatesListResponseInnerAnyOf6) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTemplatesListResponseInnerAnyOf6) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["envId"] = o.EnvId
	toSerialize["notificationId"] = o.NotificationId
	toSerialize["templateId"] = o.TemplateId
	toSerialize["channel"] = o.Channel
	toSerialize["default"] = o.Default
	if !IsNil(o.IsDefaultFor) {
		toSerialize["isDefaultFor"] = o.IsDefaultFor
	}
	toSerialize["text"] = o.Text
	if !IsNil(o.Blocks) {
		toSerialize["blocks"] = o.Blocks
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.ThreadTs) {
		toSerialize["thread_ts"] = o.ThreadTs
	}
	if !IsNil(o.ReplyBroadcast) {
		toSerialize["reply_broadcast"] = o.ReplyBroadcast
	}
	if !IsNil(o.Parse) {
		toSerialize["parse"] = o.Parse
	}
	if !IsNil(o.LinkNames) {
		toSerialize["link_names"] = o.LinkNames
	}
	if !IsNil(o.Mrkdwn) {
		toSerialize["mrkdwn"] = o.Mrkdwn
	}
	if !IsNil(o.UnfurlLinks) {
		toSerialize["unfurl_links"] = o.UnfurlLinks
	}
	if !IsNil(o.UnfurlMedia) {
		toSerialize["unfurl_media"] = o.UnfurlMedia
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *GetTemplatesListResponseInnerAnyOf6) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"envId",
		"notificationId",
		"templateId",
		"channel",
		"default",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetTemplatesListResponseInnerAnyOf6 := _GetTemplatesListResponseInnerAnyOf6{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetTemplatesListResponseInnerAnyOf6)

	if err != nil {
		return err
	}

	*o = GetTemplatesListResponseInnerAnyOf6(varGetTemplatesListResponseInnerAnyOf6)

	return err
}

type NullableGetTemplatesListResponseInnerAnyOf6 struct {
	value *GetTemplatesListResponseInnerAnyOf6
	isSet bool
}

func (v NullableGetTemplatesListResponseInnerAnyOf6) Get() *GetTemplatesListResponseInnerAnyOf6 {
	return v.value
}

func (v *NullableGetTemplatesListResponseInnerAnyOf6) Set(val *GetTemplatesListResponseInnerAnyOf6) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTemplatesListResponseInnerAnyOf6) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTemplatesListResponseInnerAnyOf6) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTemplatesListResponseInnerAnyOf6(val *GetTemplatesListResponseInnerAnyOf6) *NullableGetTemplatesListResponseInnerAnyOf6 {
	return &NullableGetTemplatesListResponseInnerAnyOf6{value: val, isSet: true}
}

func (v NullableGetTemplatesListResponseInnerAnyOf6) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTemplatesListResponseInnerAnyOf6) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
