/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"encoding/json"
)

// checks if the FirstAccountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FirstAccountRequest{}

// FirstAccountRequest struct for FirstAccountRequest
type FirstAccountRequest struct {
	// First-touch PostHog props from the client; attached to signup events.
	Attribution *map[string]string `json:"attribution,omitempty"`
}

// NewFirstAccountRequest instantiates a new FirstAccountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirstAccountRequest() *FirstAccountRequest {
	this := FirstAccountRequest{}
	return &this
}

// NewFirstAccountRequestWithDefaults instantiates a new FirstAccountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirstAccountRequestWithDefaults() *FirstAccountRequest {
	this := FirstAccountRequest{}
	return &this
}

// GetAttribution returns the Attribution field value if set, zero value otherwise.
func (o *FirstAccountRequest) GetAttribution() map[string]string {
	if o == nil || IsNil(o.Attribution) {
		var ret map[string]string
		return ret
	}
	return *o.Attribution
}

// GetAttributionOk returns a tuple with the Attribution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirstAccountRequest) GetAttributionOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Attribution) {
		return nil, false
	}
	return o.Attribution, true
}

// HasAttribution returns a boolean if a field has been set.
func (o *FirstAccountRequest) HasAttribution() bool {
	if o != nil && !IsNil(o.Attribution) {
		return true
	}

	return false
}

// SetAttribution gets a reference to the given map[string]string and assigns it to the Attribution field.
func (o *FirstAccountRequest) SetAttribution(v map[string]string) {
	o.Attribution = &v
}

func (o FirstAccountRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FirstAccountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attribution) {
		toSerialize["attribution"] = o.Attribution
	}
	return toSerialize, nil
}

type NullableFirstAccountRequest struct {
	value *FirstAccountRequest
	isSet bool
}

func (v NullableFirstAccountRequest) Get() *FirstAccountRequest {
	return v.value
}

func (v *NullableFirstAccountRequest) Set(val *FirstAccountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFirstAccountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFirstAccountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirstAccountRequest(val *FirstAccountRequest) *NullableFirstAccountRequest {
	return &NullableFirstAccountRequest{value: val, isSet: true}
}

func (v NullableFirstAccountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirstAccountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
