/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetUsersResponseUsersInnerWebPushTokensInnerSub type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUsersResponseUsersInnerWebPushTokensInnerSub{}

// GetUsersResponseUsersInnerWebPushTokensInnerSub Configuration for a Push Subscription. This can be obtained on the frontend by calling serviceWorkerRegistration.pushManager.subscribe(). The expected format is the same output as JSON.stringify'ing a PushSubscription in the browser.
type GetUsersResponseUsersInnerWebPushTokensInnerSub struct {
	Endpoint string                                              `json:"endpoint"`
	Keys     GetUsersResponseUsersInnerWebPushTokensInnerSubKeys `json:"keys"`
}

type _GetUsersResponseUsersInnerWebPushTokensInnerSub GetUsersResponseUsersInnerWebPushTokensInnerSub

// NewGetUsersResponseUsersInnerWebPushTokensInnerSub instantiates a new GetUsersResponseUsersInnerWebPushTokensInnerSub object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUsersResponseUsersInnerWebPushTokensInnerSub(endpoint string, keys GetUsersResponseUsersInnerWebPushTokensInnerSubKeys) *GetUsersResponseUsersInnerWebPushTokensInnerSub {
	this := GetUsersResponseUsersInnerWebPushTokensInnerSub{}
	this.Endpoint = endpoint
	this.Keys = keys
	return &this
}

// NewGetUsersResponseUsersInnerWebPushTokensInnerSubWithDefaults instantiates a new GetUsersResponseUsersInnerWebPushTokensInnerSub object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUsersResponseUsersInnerWebPushTokensInnerSubWithDefaults() *GetUsersResponseUsersInnerWebPushTokensInnerSub {
	this := GetUsersResponseUsersInnerWebPushTokensInnerSub{}
	return &this
}

// GetEndpoint returns the Endpoint field value
func (o *GetUsersResponseUsersInnerWebPushTokensInnerSub) GetEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value
// and a boolean to check if the value has been set.
func (o *GetUsersResponseUsersInnerWebPushTokensInnerSub) GetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Endpoint, true
}

// SetEndpoint sets field value
func (o *GetUsersResponseUsersInnerWebPushTokensInnerSub) SetEndpoint(v string) {
	o.Endpoint = v
}

// GetKeys returns the Keys field value
func (o *GetUsersResponseUsersInnerWebPushTokensInnerSub) GetKeys() GetUsersResponseUsersInnerWebPushTokensInnerSubKeys {
	if o == nil {
		var ret GetUsersResponseUsersInnerWebPushTokensInnerSubKeys
		return ret
	}

	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value
// and a boolean to check if the value has been set.
func (o *GetUsersResponseUsersInnerWebPushTokensInnerSub) GetKeysOk() (*GetUsersResponseUsersInnerWebPushTokensInnerSubKeys, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Keys, true
}

// SetKeys sets field value
func (o *GetUsersResponseUsersInnerWebPushTokensInnerSub) SetKeys(v GetUsersResponseUsersInnerWebPushTokensInnerSubKeys) {
	o.Keys = v
}

func (o GetUsersResponseUsersInnerWebPushTokensInnerSub) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUsersResponseUsersInnerWebPushTokensInnerSub) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["endpoint"] = o.Endpoint
	toSerialize["keys"] = o.Keys
	return toSerialize, nil
}

func (o *GetUsersResponseUsersInnerWebPushTokensInnerSub) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"endpoint",
		"keys",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetUsersResponseUsersInnerWebPushTokensInnerSub := _GetUsersResponseUsersInnerWebPushTokensInnerSub{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetUsersResponseUsersInnerWebPushTokensInnerSub)

	if err != nil {
		return err
	}

	*o = GetUsersResponseUsersInnerWebPushTokensInnerSub(varGetUsersResponseUsersInnerWebPushTokensInnerSub)

	return err
}

type NullableGetUsersResponseUsersInnerWebPushTokensInnerSub struct {
	value *GetUsersResponseUsersInnerWebPushTokensInnerSub
	isSet bool
}

func (v NullableGetUsersResponseUsersInnerWebPushTokensInnerSub) Get() *GetUsersResponseUsersInnerWebPushTokensInnerSub {
	return v.value
}

func (v *NullableGetUsersResponseUsersInnerWebPushTokensInnerSub) Set(val *GetUsersResponseUsersInnerWebPushTokensInnerSub) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUsersResponseUsersInnerWebPushTokensInnerSub) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUsersResponseUsersInnerWebPushTokensInnerSub) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUsersResponseUsersInnerWebPushTokensInnerSub(val *GetUsersResponseUsersInnerWebPushTokensInnerSub) *NullableGetUsersResponseUsersInnerWebPushTokensInnerSub {
	return &NullableGetUsersResponseUsersInnerWebPushTokensInnerSub{value: val, isSet: true}
}

func (v NullableGetUsersResponseUsersInnerWebPushTokensInnerSub) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUsersResponseUsersInnerWebPushTokensInnerSub) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
