/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TenDlcCampaignRegistrationDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenDlcCampaignRegistrationDetails{}

// TenDlcCampaignRegistrationDetails Admin GET/PATCH response for 10DLC campaign registration
type TenDlcCampaignRegistrationDetails struct {
	AccountId string `json:"accountId"`
	// Pingram-side brand registration workflow status. - not_started: no customer submission yet - pending_review: customer submitted; Pingram has not submitted to carriers - in_progress: submitted for carrier review - approved | rejected | info_needed: review outcome
	CampaignStatus                 string  `json:"campaignStatus"`
	CampaignDescription            *string `json:"campaignDescription,omitempty"`
	CampaignSample1                *string `json:"campaignSample1,omitempty"`
	CampaignSample2                *string `json:"campaignSample2,omitempty"`
	CampaignSample3                *string `json:"campaignSample3,omitempty"`
	CampaignSample4                *string `json:"campaignSample4,omitempty"`
	CampaignMessageFlow            *string `json:"campaignMessageFlow,omitempty"`
	CampaignOptinKeywords          *string `json:"campaignOptinKeywords,omitempty"`
	CampaignOptinMessage           *string `json:"campaignOptinMessage,omitempty"`
	CampaignOptoutKeywords         *string `json:"campaignOptoutKeywords,omitempty"`
	CampaignOptoutMessage          *string `json:"campaignOptoutMessage,omitempty"`
	CampaignHelpKeywords           *string `json:"campaignHelpKeywords,omitempty"`
	CampaignHelpMessage            *string `json:"campaignHelpMessage,omitempty"`
	CampaignEmbeddedLink           *bool   `json:"campaignEmbeddedLink,omitempty"`
	CampaignEmbeddedLinkUrl        *string `json:"campaignEmbeddedLinkUrl,omitempty"`
	CampaignEmbeddedPhone          *bool   `json:"campaignEmbeddedPhone,omitempty"`
	CampaignAgeGated               *bool   `json:"campaignAgeGated,omitempty"`
	CampaignDirectLending          *bool   `json:"campaignDirectLending,omitempty"`
	CampaignPrivacyPolicyLink      *string `json:"campaignPrivacyPolicyLink,omitempty"`
	CampaignTermsAndConditionsLink *string `json:"campaignTermsAndConditionsLink,omitempty"`
	CampaignUsecase                *string `json:"campaignUsecase,omitempty"`
	CampaignId                     *string `json:"campaignId,omitempty"`
	CreatedAt                      string  `json:"createdAt"`
	UpdatedAt                      string  `json:"updatedAt"`
}

type _TenDlcCampaignRegistrationDetails TenDlcCampaignRegistrationDetails

// NewTenDlcCampaignRegistrationDetails instantiates a new TenDlcCampaignRegistrationDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenDlcCampaignRegistrationDetails(accountId string, campaignStatus string, createdAt string, updatedAt string) *TenDlcCampaignRegistrationDetails {
	this := TenDlcCampaignRegistrationDetails{}
	this.AccountId = accountId
	this.CampaignStatus = campaignStatus
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewTenDlcCampaignRegistrationDetailsWithDefaults instantiates a new TenDlcCampaignRegistrationDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenDlcCampaignRegistrationDetailsWithDefaults() *TenDlcCampaignRegistrationDetails {
	this := TenDlcCampaignRegistrationDetails{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *TenDlcCampaignRegistrationDetails) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *TenDlcCampaignRegistrationDetails) SetAccountId(v string) {
	o.AccountId = v
}

// GetCampaignStatus returns the CampaignStatus field value
func (o *TenDlcCampaignRegistrationDetails) GetCampaignStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CampaignStatus
}

// GetCampaignStatusOk returns a tuple with the CampaignStatus field value
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CampaignStatus, true
}

// SetCampaignStatus sets field value
func (o *TenDlcCampaignRegistrationDetails) SetCampaignStatus(v string) {
	o.CampaignStatus = v
}

// GetCampaignDescription returns the CampaignDescription field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignDescription() string {
	if o == nil || IsNil(o.CampaignDescription) {
		var ret string
		return ret
	}
	return *o.CampaignDescription
}

// GetCampaignDescriptionOk returns a tuple with the CampaignDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignDescription) {
		return nil, false
	}
	return o.CampaignDescription, true
}

// HasCampaignDescription returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignDescription() bool {
	if o != nil && !IsNil(o.CampaignDescription) {
		return true
	}

	return false
}

// SetCampaignDescription gets a reference to the given string and assigns it to the CampaignDescription field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignDescription(v string) {
	o.CampaignDescription = &v
}

// GetCampaignSample1 returns the CampaignSample1 field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignSample1() string {
	if o == nil || IsNil(o.CampaignSample1) {
		var ret string
		return ret
	}
	return *o.CampaignSample1
}

// GetCampaignSample1Ok returns a tuple with the CampaignSample1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignSample1Ok() (*string, bool) {
	if o == nil || IsNil(o.CampaignSample1) {
		return nil, false
	}
	return o.CampaignSample1, true
}

// HasCampaignSample1 returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignSample1() bool {
	if o != nil && !IsNil(o.CampaignSample1) {
		return true
	}

	return false
}

// SetCampaignSample1 gets a reference to the given string and assigns it to the CampaignSample1 field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignSample1(v string) {
	o.CampaignSample1 = &v
}

// GetCampaignSample2 returns the CampaignSample2 field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignSample2() string {
	if o == nil || IsNil(o.CampaignSample2) {
		var ret string
		return ret
	}
	return *o.CampaignSample2
}

// GetCampaignSample2Ok returns a tuple with the CampaignSample2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignSample2Ok() (*string, bool) {
	if o == nil || IsNil(o.CampaignSample2) {
		return nil, false
	}
	return o.CampaignSample2, true
}

// HasCampaignSample2 returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignSample2() bool {
	if o != nil && !IsNil(o.CampaignSample2) {
		return true
	}

	return false
}

// SetCampaignSample2 gets a reference to the given string and assigns it to the CampaignSample2 field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignSample2(v string) {
	o.CampaignSample2 = &v
}

// GetCampaignSample3 returns the CampaignSample3 field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignSample3() string {
	if o == nil || IsNil(o.CampaignSample3) {
		var ret string
		return ret
	}
	return *o.CampaignSample3
}

// GetCampaignSample3Ok returns a tuple with the CampaignSample3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignSample3Ok() (*string, bool) {
	if o == nil || IsNil(o.CampaignSample3) {
		return nil, false
	}
	return o.CampaignSample3, true
}

// HasCampaignSample3 returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignSample3() bool {
	if o != nil && !IsNil(o.CampaignSample3) {
		return true
	}

	return false
}

// SetCampaignSample3 gets a reference to the given string and assigns it to the CampaignSample3 field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignSample3(v string) {
	o.CampaignSample3 = &v
}

// GetCampaignSample4 returns the CampaignSample4 field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignSample4() string {
	if o == nil || IsNil(o.CampaignSample4) {
		var ret string
		return ret
	}
	return *o.CampaignSample4
}

// GetCampaignSample4Ok returns a tuple with the CampaignSample4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignSample4Ok() (*string, bool) {
	if o == nil || IsNil(o.CampaignSample4) {
		return nil, false
	}
	return o.CampaignSample4, true
}

// HasCampaignSample4 returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignSample4() bool {
	if o != nil && !IsNil(o.CampaignSample4) {
		return true
	}

	return false
}

// SetCampaignSample4 gets a reference to the given string and assigns it to the CampaignSample4 field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignSample4(v string) {
	o.CampaignSample4 = &v
}

// GetCampaignMessageFlow returns the CampaignMessageFlow field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignMessageFlow() string {
	if o == nil || IsNil(o.CampaignMessageFlow) {
		var ret string
		return ret
	}
	return *o.CampaignMessageFlow
}

// GetCampaignMessageFlowOk returns a tuple with the CampaignMessageFlow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignMessageFlowOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignMessageFlow) {
		return nil, false
	}
	return o.CampaignMessageFlow, true
}

// HasCampaignMessageFlow returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignMessageFlow() bool {
	if o != nil && !IsNil(o.CampaignMessageFlow) {
		return true
	}

	return false
}

// SetCampaignMessageFlow gets a reference to the given string and assigns it to the CampaignMessageFlow field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignMessageFlow(v string) {
	o.CampaignMessageFlow = &v
}

// GetCampaignOptinKeywords returns the CampaignOptinKeywords field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignOptinKeywords() string {
	if o == nil || IsNil(o.CampaignOptinKeywords) {
		var ret string
		return ret
	}
	return *o.CampaignOptinKeywords
}

// GetCampaignOptinKeywordsOk returns a tuple with the CampaignOptinKeywords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignOptinKeywordsOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignOptinKeywords) {
		return nil, false
	}
	return o.CampaignOptinKeywords, true
}

// HasCampaignOptinKeywords returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignOptinKeywords() bool {
	if o != nil && !IsNil(o.CampaignOptinKeywords) {
		return true
	}

	return false
}

// SetCampaignOptinKeywords gets a reference to the given string and assigns it to the CampaignOptinKeywords field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignOptinKeywords(v string) {
	o.CampaignOptinKeywords = &v
}

// GetCampaignOptinMessage returns the CampaignOptinMessage field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignOptinMessage() string {
	if o == nil || IsNil(o.CampaignOptinMessage) {
		var ret string
		return ret
	}
	return *o.CampaignOptinMessage
}

// GetCampaignOptinMessageOk returns a tuple with the CampaignOptinMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignOptinMessageOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignOptinMessage) {
		return nil, false
	}
	return o.CampaignOptinMessage, true
}

// HasCampaignOptinMessage returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignOptinMessage() bool {
	if o != nil && !IsNil(o.CampaignOptinMessage) {
		return true
	}

	return false
}

// SetCampaignOptinMessage gets a reference to the given string and assigns it to the CampaignOptinMessage field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignOptinMessage(v string) {
	o.CampaignOptinMessage = &v
}

// GetCampaignOptoutKeywords returns the CampaignOptoutKeywords field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignOptoutKeywords() string {
	if o == nil || IsNil(o.CampaignOptoutKeywords) {
		var ret string
		return ret
	}
	return *o.CampaignOptoutKeywords
}

// GetCampaignOptoutKeywordsOk returns a tuple with the CampaignOptoutKeywords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignOptoutKeywordsOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignOptoutKeywords) {
		return nil, false
	}
	return o.CampaignOptoutKeywords, true
}

// HasCampaignOptoutKeywords returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignOptoutKeywords() bool {
	if o != nil && !IsNil(o.CampaignOptoutKeywords) {
		return true
	}

	return false
}

// SetCampaignOptoutKeywords gets a reference to the given string and assigns it to the CampaignOptoutKeywords field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignOptoutKeywords(v string) {
	o.CampaignOptoutKeywords = &v
}

// GetCampaignOptoutMessage returns the CampaignOptoutMessage field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignOptoutMessage() string {
	if o == nil || IsNil(o.CampaignOptoutMessage) {
		var ret string
		return ret
	}
	return *o.CampaignOptoutMessage
}

// GetCampaignOptoutMessageOk returns a tuple with the CampaignOptoutMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignOptoutMessageOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignOptoutMessage) {
		return nil, false
	}
	return o.CampaignOptoutMessage, true
}

// HasCampaignOptoutMessage returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignOptoutMessage() bool {
	if o != nil && !IsNil(o.CampaignOptoutMessage) {
		return true
	}

	return false
}

// SetCampaignOptoutMessage gets a reference to the given string and assigns it to the CampaignOptoutMessage field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignOptoutMessage(v string) {
	o.CampaignOptoutMessage = &v
}

// GetCampaignHelpKeywords returns the CampaignHelpKeywords field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignHelpKeywords() string {
	if o == nil || IsNil(o.CampaignHelpKeywords) {
		var ret string
		return ret
	}
	return *o.CampaignHelpKeywords
}

// GetCampaignHelpKeywordsOk returns a tuple with the CampaignHelpKeywords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignHelpKeywordsOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignHelpKeywords) {
		return nil, false
	}
	return o.CampaignHelpKeywords, true
}

// HasCampaignHelpKeywords returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignHelpKeywords() bool {
	if o != nil && !IsNil(o.CampaignHelpKeywords) {
		return true
	}

	return false
}

// SetCampaignHelpKeywords gets a reference to the given string and assigns it to the CampaignHelpKeywords field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignHelpKeywords(v string) {
	o.CampaignHelpKeywords = &v
}

// GetCampaignHelpMessage returns the CampaignHelpMessage field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignHelpMessage() string {
	if o == nil || IsNil(o.CampaignHelpMessage) {
		var ret string
		return ret
	}
	return *o.CampaignHelpMessage
}

// GetCampaignHelpMessageOk returns a tuple with the CampaignHelpMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignHelpMessageOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignHelpMessage) {
		return nil, false
	}
	return o.CampaignHelpMessage, true
}

// HasCampaignHelpMessage returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignHelpMessage() bool {
	if o != nil && !IsNil(o.CampaignHelpMessage) {
		return true
	}

	return false
}

// SetCampaignHelpMessage gets a reference to the given string and assigns it to the CampaignHelpMessage field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignHelpMessage(v string) {
	o.CampaignHelpMessage = &v
}

// GetCampaignEmbeddedLink returns the CampaignEmbeddedLink field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignEmbeddedLink() bool {
	if o == nil || IsNil(o.CampaignEmbeddedLink) {
		var ret bool
		return ret
	}
	return *o.CampaignEmbeddedLink
}

// GetCampaignEmbeddedLinkOk returns a tuple with the CampaignEmbeddedLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignEmbeddedLinkOk() (*bool, bool) {
	if o == nil || IsNil(o.CampaignEmbeddedLink) {
		return nil, false
	}
	return o.CampaignEmbeddedLink, true
}

// HasCampaignEmbeddedLink returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignEmbeddedLink() bool {
	if o != nil && !IsNil(o.CampaignEmbeddedLink) {
		return true
	}

	return false
}

// SetCampaignEmbeddedLink gets a reference to the given bool and assigns it to the CampaignEmbeddedLink field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignEmbeddedLink(v bool) {
	o.CampaignEmbeddedLink = &v
}

// GetCampaignEmbeddedLinkUrl returns the CampaignEmbeddedLinkUrl field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignEmbeddedLinkUrl() string {
	if o == nil || IsNil(o.CampaignEmbeddedLinkUrl) {
		var ret string
		return ret
	}
	return *o.CampaignEmbeddedLinkUrl
}

// GetCampaignEmbeddedLinkUrlOk returns a tuple with the CampaignEmbeddedLinkUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignEmbeddedLinkUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignEmbeddedLinkUrl) {
		return nil, false
	}
	return o.CampaignEmbeddedLinkUrl, true
}

// HasCampaignEmbeddedLinkUrl returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignEmbeddedLinkUrl() bool {
	if o != nil && !IsNil(o.CampaignEmbeddedLinkUrl) {
		return true
	}

	return false
}

// SetCampaignEmbeddedLinkUrl gets a reference to the given string and assigns it to the CampaignEmbeddedLinkUrl field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignEmbeddedLinkUrl(v string) {
	o.CampaignEmbeddedLinkUrl = &v
}

// GetCampaignEmbeddedPhone returns the CampaignEmbeddedPhone field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignEmbeddedPhone() bool {
	if o == nil || IsNil(o.CampaignEmbeddedPhone) {
		var ret bool
		return ret
	}
	return *o.CampaignEmbeddedPhone
}

// GetCampaignEmbeddedPhoneOk returns a tuple with the CampaignEmbeddedPhone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignEmbeddedPhoneOk() (*bool, bool) {
	if o == nil || IsNil(o.CampaignEmbeddedPhone) {
		return nil, false
	}
	return o.CampaignEmbeddedPhone, true
}

// HasCampaignEmbeddedPhone returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignEmbeddedPhone() bool {
	if o != nil && !IsNil(o.CampaignEmbeddedPhone) {
		return true
	}

	return false
}

// SetCampaignEmbeddedPhone gets a reference to the given bool and assigns it to the CampaignEmbeddedPhone field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignEmbeddedPhone(v bool) {
	o.CampaignEmbeddedPhone = &v
}

// GetCampaignAgeGated returns the CampaignAgeGated field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignAgeGated() bool {
	if o == nil || IsNil(o.CampaignAgeGated) {
		var ret bool
		return ret
	}
	return *o.CampaignAgeGated
}

// GetCampaignAgeGatedOk returns a tuple with the CampaignAgeGated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignAgeGatedOk() (*bool, bool) {
	if o == nil || IsNil(o.CampaignAgeGated) {
		return nil, false
	}
	return o.CampaignAgeGated, true
}

// HasCampaignAgeGated returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignAgeGated() bool {
	if o != nil && !IsNil(o.CampaignAgeGated) {
		return true
	}

	return false
}

// SetCampaignAgeGated gets a reference to the given bool and assigns it to the CampaignAgeGated field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignAgeGated(v bool) {
	o.CampaignAgeGated = &v
}

// GetCampaignDirectLending returns the CampaignDirectLending field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignDirectLending() bool {
	if o == nil || IsNil(o.CampaignDirectLending) {
		var ret bool
		return ret
	}
	return *o.CampaignDirectLending
}

// GetCampaignDirectLendingOk returns a tuple with the CampaignDirectLending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignDirectLendingOk() (*bool, bool) {
	if o == nil || IsNil(o.CampaignDirectLending) {
		return nil, false
	}
	return o.CampaignDirectLending, true
}

// HasCampaignDirectLending returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignDirectLending() bool {
	if o != nil && !IsNil(o.CampaignDirectLending) {
		return true
	}

	return false
}

// SetCampaignDirectLending gets a reference to the given bool and assigns it to the CampaignDirectLending field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignDirectLending(v bool) {
	o.CampaignDirectLending = &v
}

// GetCampaignPrivacyPolicyLink returns the CampaignPrivacyPolicyLink field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignPrivacyPolicyLink() string {
	if o == nil || IsNil(o.CampaignPrivacyPolicyLink) {
		var ret string
		return ret
	}
	return *o.CampaignPrivacyPolicyLink
}

// GetCampaignPrivacyPolicyLinkOk returns a tuple with the CampaignPrivacyPolicyLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignPrivacyPolicyLinkOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignPrivacyPolicyLink) {
		return nil, false
	}
	return o.CampaignPrivacyPolicyLink, true
}

// HasCampaignPrivacyPolicyLink returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignPrivacyPolicyLink() bool {
	if o != nil && !IsNil(o.CampaignPrivacyPolicyLink) {
		return true
	}

	return false
}

// SetCampaignPrivacyPolicyLink gets a reference to the given string and assigns it to the CampaignPrivacyPolicyLink field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignPrivacyPolicyLink(v string) {
	o.CampaignPrivacyPolicyLink = &v
}

// GetCampaignTermsAndConditionsLink returns the CampaignTermsAndConditionsLink field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignTermsAndConditionsLink() string {
	if o == nil || IsNil(o.CampaignTermsAndConditionsLink) {
		var ret string
		return ret
	}
	return *o.CampaignTermsAndConditionsLink
}

// GetCampaignTermsAndConditionsLinkOk returns a tuple with the CampaignTermsAndConditionsLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignTermsAndConditionsLinkOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignTermsAndConditionsLink) {
		return nil, false
	}
	return o.CampaignTermsAndConditionsLink, true
}

// HasCampaignTermsAndConditionsLink returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignTermsAndConditionsLink() bool {
	if o != nil && !IsNil(o.CampaignTermsAndConditionsLink) {
		return true
	}

	return false
}

// SetCampaignTermsAndConditionsLink gets a reference to the given string and assigns it to the CampaignTermsAndConditionsLink field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignTermsAndConditionsLink(v string) {
	o.CampaignTermsAndConditionsLink = &v
}

// GetCampaignUsecase returns the CampaignUsecase field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignUsecase() string {
	if o == nil || IsNil(o.CampaignUsecase) {
		var ret string
		return ret
	}
	return *o.CampaignUsecase
}

// GetCampaignUsecaseOk returns a tuple with the CampaignUsecase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignUsecaseOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignUsecase) {
		return nil, false
	}
	return o.CampaignUsecase, true
}

// HasCampaignUsecase returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignUsecase() bool {
	if o != nil && !IsNil(o.CampaignUsecase) {
		return true
	}

	return false
}

// SetCampaignUsecase gets a reference to the given string and assigns it to the CampaignUsecase field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignUsecase(v string) {
	o.CampaignUsecase = &v
}

// GetCampaignId returns the CampaignId field value if set, zero value otherwise.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignId() string {
	if o == nil || IsNil(o.CampaignId) {
		var ret string
		return ret
	}
	return *o.CampaignId
}

// GetCampaignIdOk returns a tuple with the CampaignId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCampaignIdOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignId) {
		return nil, false
	}
	return o.CampaignId, true
}

// HasCampaignId returns a boolean if a field has been set.
func (o *TenDlcCampaignRegistrationDetails) HasCampaignId() bool {
	if o != nil && !IsNil(o.CampaignId) {
		return true
	}

	return false
}

// SetCampaignId gets a reference to the given string and assigns it to the CampaignId field.
func (o *TenDlcCampaignRegistrationDetails) SetCampaignId(v string) {
	o.CampaignId = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *TenDlcCampaignRegistrationDetails) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TenDlcCampaignRegistrationDetails) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *TenDlcCampaignRegistrationDetails) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *TenDlcCampaignRegistrationDetails) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *TenDlcCampaignRegistrationDetails) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o TenDlcCampaignRegistrationDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenDlcCampaignRegistrationDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountId"] = o.AccountId
	toSerialize["campaignStatus"] = o.CampaignStatus
	if !IsNil(o.CampaignDescription) {
		toSerialize["campaignDescription"] = o.CampaignDescription
	}
	if !IsNil(o.CampaignSample1) {
		toSerialize["campaignSample1"] = o.CampaignSample1
	}
	if !IsNil(o.CampaignSample2) {
		toSerialize["campaignSample2"] = o.CampaignSample2
	}
	if !IsNil(o.CampaignSample3) {
		toSerialize["campaignSample3"] = o.CampaignSample3
	}
	if !IsNil(o.CampaignSample4) {
		toSerialize["campaignSample4"] = o.CampaignSample4
	}
	if !IsNil(o.CampaignMessageFlow) {
		toSerialize["campaignMessageFlow"] = o.CampaignMessageFlow
	}
	if !IsNil(o.CampaignOptinKeywords) {
		toSerialize["campaignOptinKeywords"] = o.CampaignOptinKeywords
	}
	if !IsNil(o.CampaignOptinMessage) {
		toSerialize["campaignOptinMessage"] = o.CampaignOptinMessage
	}
	if !IsNil(o.CampaignOptoutKeywords) {
		toSerialize["campaignOptoutKeywords"] = o.CampaignOptoutKeywords
	}
	if !IsNil(o.CampaignOptoutMessage) {
		toSerialize["campaignOptoutMessage"] = o.CampaignOptoutMessage
	}
	if !IsNil(o.CampaignHelpKeywords) {
		toSerialize["campaignHelpKeywords"] = o.CampaignHelpKeywords
	}
	if !IsNil(o.CampaignHelpMessage) {
		toSerialize["campaignHelpMessage"] = o.CampaignHelpMessage
	}
	if !IsNil(o.CampaignEmbeddedLink) {
		toSerialize["campaignEmbeddedLink"] = o.CampaignEmbeddedLink
	}
	if !IsNil(o.CampaignEmbeddedLinkUrl) {
		toSerialize["campaignEmbeddedLinkUrl"] = o.CampaignEmbeddedLinkUrl
	}
	if !IsNil(o.CampaignEmbeddedPhone) {
		toSerialize["campaignEmbeddedPhone"] = o.CampaignEmbeddedPhone
	}
	if !IsNil(o.CampaignAgeGated) {
		toSerialize["campaignAgeGated"] = o.CampaignAgeGated
	}
	if !IsNil(o.CampaignDirectLending) {
		toSerialize["campaignDirectLending"] = o.CampaignDirectLending
	}
	if !IsNil(o.CampaignPrivacyPolicyLink) {
		toSerialize["campaignPrivacyPolicyLink"] = o.CampaignPrivacyPolicyLink
	}
	if !IsNil(o.CampaignTermsAndConditionsLink) {
		toSerialize["campaignTermsAndConditionsLink"] = o.CampaignTermsAndConditionsLink
	}
	if !IsNil(o.CampaignUsecase) {
		toSerialize["campaignUsecase"] = o.CampaignUsecase
	}
	if !IsNil(o.CampaignId) {
		toSerialize["campaignId"] = o.CampaignId
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *TenDlcCampaignRegistrationDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountId",
		"campaignStatus",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenDlcCampaignRegistrationDetails := _TenDlcCampaignRegistrationDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTenDlcCampaignRegistrationDetails)

	if err != nil {
		return err
	}

	*o = TenDlcCampaignRegistrationDetails(varTenDlcCampaignRegistrationDetails)

	return err
}

type NullableTenDlcCampaignRegistrationDetails struct {
	value *TenDlcCampaignRegistrationDetails
	isSet bool
}

func (v NullableTenDlcCampaignRegistrationDetails) Get() *TenDlcCampaignRegistrationDetails {
	return v.value
}

func (v *NullableTenDlcCampaignRegistrationDetails) Set(val *TenDlcCampaignRegistrationDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableTenDlcCampaignRegistrationDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableTenDlcCampaignRegistrationDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenDlcCampaignRegistrationDetails(val *TenDlcCampaignRegistrationDetails) *NullableTenDlcCampaignRegistrationDetails {
	return &NullableTenDlcCampaignRegistrationDetails{value: val, isSet: true}
}

func (v NullableTenDlcCampaignRegistrationDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenDlcCampaignRegistrationDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
