/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"encoding/json"
)

// checks if the GetUsageResponseCosts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUsageResponseCosts{}

// GetUsageResponseCosts Total costs for the billing cycle (all channel costs + number rent)
type GetUsageResponseCosts struct {
	NUMBER               *float32 `json:"NUMBER,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetUsageResponseCosts GetUsageResponseCosts

// NewGetUsageResponseCosts instantiates a new GetUsageResponseCosts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUsageResponseCosts() *GetUsageResponseCosts {
	this := GetUsageResponseCosts{}
	return &this
}

// NewGetUsageResponseCostsWithDefaults instantiates a new GetUsageResponseCosts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUsageResponseCostsWithDefaults() *GetUsageResponseCosts {
	this := GetUsageResponseCosts{}
	return &this
}

// GetNUMBER returns the NUMBER field value if set, zero value otherwise.
func (o *GetUsageResponseCosts) GetNUMBER() float32 {
	if o == nil || IsNil(o.NUMBER) {
		var ret float32
		return ret
	}
	return *o.NUMBER
}

// GetNUMBEROk returns a tuple with the NUMBER field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsageResponseCosts) GetNUMBEROk() (*float32, bool) {
	if o == nil || IsNil(o.NUMBER) {
		return nil, false
	}
	return o.NUMBER, true
}

// HasNUMBER returns a boolean if a field has been set.
func (o *GetUsageResponseCosts) HasNUMBER() bool {
	if o != nil && !IsNil(o.NUMBER) {
		return true
	}

	return false
}

// SetNUMBER gets a reference to the given float32 and assigns it to the NUMBER field.
func (o *GetUsageResponseCosts) SetNUMBER(v float32) {
	o.NUMBER = &v
}

func (o GetUsageResponseCosts) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUsageResponseCosts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NUMBER) {
		toSerialize["NUMBER"] = o.NUMBER
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetUsageResponseCosts) UnmarshalJSON(data []byte) (err error) {
	varGetUsageResponseCosts := _GetUsageResponseCosts{}

	err = json.Unmarshal(data, &varGetUsageResponseCosts)

	if err != nil {
		return err
	}

	*o = GetUsageResponseCosts(varGetUsageResponseCosts)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "NUMBER")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetUsageResponseCosts struct {
	value *GetUsageResponseCosts
	isSet bool
}

func (v NullableGetUsageResponseCosts) Get() *GetUsageResponseCosts {
	return v.value
}

func (v *NullableGetUsageResponseCosts) Set(val *GetUsageResponseCosts) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUsageResponseCosts) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUsageResponseCosts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUsageResponseCosts(val *GetUsageResponseCosts) *NullableGetUsageResponseCosts {
	return &NullableGetUsageResponseCosts{value: val, isSet: true}
}

func (v NullableGetUsageResponseCosts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUsageResponseCosts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
