/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"encoding/json"
)

// checks if the TemplatePatchRequestAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplatePatchRequestAnyOf1{}

// TemplatePatchRequestAnyOf1 Properties for updating an INAPP_WEB channel template. All fields are optional; only provided fields are updated. instant and batch configure delivery-mode-specific copy (real-time vs batched).
type TemplatePatchRequestAnyOf1 struct {
	// Notification title (in-app).
	Title *string `json:"title,omitempty"`
	// URL to open when the user taps the notification.
	RedirectURL *string `json:"redirectURL,omitempty"`
	// Image URL shown in the in-app notification.
	ImageURL *string                            `json:"imageURL,omitempty"`
	Instant  *TemplatePatchRequestAnyOf1Instant `json:"instant,omitempty"`
	Batch    *TemplatePatchRequestAnyOf1Batch   `json:"batch,omitempty"`
}

// NewTemplatePatchRequestAnyOf1 instantiates a new TemplatePatchRequestAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplatePatchRequestAnyOf1() *TemplatePatchRequestAnyOf1 {
	this := TemplatePatchRequestAnyOf1{}
	return &this
}

// NewTemplatePatchRequestAnyOf1WithDefaults instantiates a new TemplatePatchRequestAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplatePatchRequestAnyOf1WithDefaults() *TemplatePatchRequestAnyOf1 {
	this := TemplatePatchRequestAnyOf1{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *TemplatePatchRequestAnyOf1) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplatePatchRequestAnyOf1) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *TemplatePatchRequestAnyOf1) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *TemplatePatchRequestAnyOf1) SetTitle(v string) {
	o.Title = &v
}

// GetRedirectURL returns the RedirectURL field value if set, zero value otherwise.
func (o *TemplatePatchRequestAnyOf1) GetRedirectURL() string {
	if o == nil || IsNil(o.RedirectURL) {
		var ret string
		return ret
	}
	return *o.RedirectURL
}

// GetRedirectURLOk returns a tuple with the RedirectURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplatePatchRequestAnyOf1) GetRedirectURLOk() (*string, bool) {
	if o == nil || IsNil(o.RedirectURL) {
		return nil, false
	}
	return o.RedirectURL, true
}

// HasRedirectURL returns a boolean if a field has been set.
func (o *TemplatePatchRequestAnyOf1) HasRedirectURL() bool {
	if o != nil && !IsNil(o.RedirectURL) {
		return true
	}

	return false
}

// SetRedirectURL gets a reference to the given string and assigns it to the RedirectURL field.
func (o *TemplatePatchRequestAnyOf1) SetRedirectURL(v string) {
	o.RedirectURL = &v
}

// GetImageURL returns the ImageURL field value if set, zero value otherwise.
func (o *TemplatePatchRequestAnyOf1) GetImageURL() string {
	if o == nil || IsNil(o.ImageURL) {
		var ret string
		return ret
	}
	return *o.ImageURL
}

// GetImageURLOk returns a tuple with the ImageURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplatePatchRequestAnyOf1) GetImageURLOk() (*string, bool) {
	if o == nil || IsNil(o.ImageURL) {
		return nil, false
	}
	return o.ImageURL, true
}

// HasImageURL returns a boolean if a field has been set.
func (o *TemplatePatchRequestAnyOf1) HasImageURL() bool {
	if o != nil && !IsNil(o.ImageURL) {
		return true
	}

	return false
}

// SetImageURL gets a reference to the given string and assigns it to the ImageURL field.
func (o *TemplatePatchRequestAnyOf1) SetImageURL(v string) {
	o.ImageURL = &v
}

// GetInstant returns the Instant field value if set, zero value otherwise.
func (o *TemplatePatchRequestAnyOf1) GetInstant() TemplatePatchRequestAnyOf1Instant {
	if o == nil || IsNil(o.Instant) {
		var ret TemplatePatchRequestAnyOf1Instant
		return ret
	}
	return *o.Instant
}

// GetInstantOk returns a tuple with the Instant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplatePatchRequestAnyOf1) GetInstantOk() (*TemplatePatchRequestAnyOf1Instant, bool) {
	if o == nil || IsNil(o.Instant) {
		return nil, false
	}
	return o.Instant, true
}

// HasInstant returns a boolean if a field has been set.
func (o *TemplatePatchRequestAnyOf1) HasInstant() bool {
	if o != nil && !IsNil(o.Instant) {
		return true
	}

	return false
}

// SetInstant gets a reference to the given TemplatePatchRequestAnyOf1Instant and assigns it to the Instant field.
func (o *TemplatePatchRequestAnyOf1) SetInstant(v TemplatePatchRequestAnyOf1Instant) {
	o.Instant = &v
}

// GetBatch returns the Batch field value if set, zero value otherwise.
func (o *TemplatePatchRequestAnyOf1) GetBatch() TemplatePatchRequestAnyOf1Batch {
	if o == nil || IsNil(o.Batch) {
		var ret TemplatePatchRequestAnyOf1Batch
		return ret
	}
	return *o.Batch
}

// GetBatchOk returns a tuple with the Batch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplatePatchRequestAnyOf1) GetBatchOk() (*TemplatePatchRequestAnyOf1Batch, bool) {
	if o == nil || IsNil(o.Batch) {
		return nil, false
	}
	return o.Batch, true
}

// HasBatch returns a boolean if a field has been set.
func (o *TemplatePatchRequestAnyOf1) HasBatch() bool {
	if o != nil && !IsNil(o.Batch) {
		return true
	}

	return false
}

// SetBatch gets a reference to the given TemplatePatchRequestAnyOf1Batch and assigns it to the Batch field.
func (o *TemplatePatchRequestAnyOf1) SetBatch(v TemplatePatchRequestAnyOf1Batch) {
	o.Batch = &v
}

func (o TemplatePatchRequestAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplatePatchRequestAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.RedirectURL) {
		toSerialize["redirectURL"] = o.RedirectURL
	}
	if !IsNil(o.ImageURL) {
		toSerialize["imageURL"] = o.ImageURL
	}
	if !IsNil(o.Instant) {
		toSerialize["instant"] = o.Instant
	}
	if !IsNil(o.Batch) {
		toSerialize["batch"] = o.Batch
	}
	return toSerialize, nil
}

type NullableTemplatePatchRequestAnyOf1 struct {
	value *TemplatePatchRequestAnyOf1
	isSet bool
}

func (v NullableTemplatePatchRequestAnyOf1) Get() *TemplatePatchRequestAnyOf1 {
	return v.value
}

func (v *NullableTemplatePatchRequestAnyOf1) Set(val *TemplatePatchRequestAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplatePatchRequestAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplatePatchRequestAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplatePatchRequestAnyOf1(val *TemplatePatchRequestAnyOf1) *NullableTemplatePatchRequestAnyOf1 {
	return &NullableTemplatePatchRequestAnyOf1{value: val, isSet: true}
}

func (v NullableTemplatePatchRequestAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplatePatchRequestAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
