/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"encoding/json"
)

// checks if the GetTemplatesListResponseInnerAnyOf6Metadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTemplatesListResponseInnerAnyOf6Metadata{}

// GetTemplatesListResponseInnerAnyOf6Metadata Slack message metadata with optional work object entities. Combines standard Slack message metadata fields with an array of entity objects.
type GetTemplatesListResponseInnerAnyOf6Metadata struct {
	// An array of work object entities.
	Entities []GetTemplatesListResponseInnerAnyOf6MetadataEntitiesInner `json:"entities,omitempty"`
	// A human readable alphanumeric string representing your application's metadata event.
	EventType *string `json:"event_type,omitempty"`
	// A free-form object containing whatever data your application wishes to attach to messages.
	EventPayload map[string]interface{} `json:"event_payload,omitempty"`
}

// NewGetTemplatesListResponseInnerAnyOf6Metadata instantiates a new GetTemplatesListResponseInnerAnyOf6Metadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTemplatesListResponseInnerAnyOf6Metadata() *GetTemplatesListResponseInnerAnyOf6Metadata {
	this := GetTemplatesListResponseInnerAnyOf6Metadata{}
	return &this
}

// NewGetTemplatesListResponseInnerAnyOf6MetadataWithDefaults instantiates a new GetTemplatesListResponseInnerAnyOf6Metadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTemplatesListResponseInnerAnyOf6MetadataWithDefaults() *GetTemplatesListResponseInnerAnyOf6Metadata {
	this := GetTemplatesListResponseInnerAnyOf6Metadata{}
	return &this
}

// GetEntities returns the Entities field value if set, zero value otherwise.
func (o *GetTemplatesListResponseInnerAnyOf6Metadata) GetEntities() []GetTemplatesListResponseInnerAnyOf6MetadataEntitiesInner {
	if o == nil || IsNil(o.Entities) {
		var ret []GetTemplatesListResponseInnerAnyOf6MetadataEntitiesInner
		return ret
	}
	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6Metadata) GetEntitiesOk() ([]GetTemplatesListResponseInnerAnyOf6MetadataEntitiesInner, bool) {
	if o == nil || IsNil(o.Entities) {
		return nil, false
	}
	return o.Entities, true
}

// HasEntities returns a boolean if a field has been set.
func (o *GetTemplatesListResponseInnerAnyOf6Metadata) HasEntities() bool {
	if o != nil && !IsNil(o.Entities) {
		return true
	}

	return false
}

// SetEntities gets a reference to the given []GetTemplatesListResponseInnerAnyOf6MetadataEntitiesInner and assigns it to the Entities field.
func (o *GetTemplatesListResponseInnerAnyOf6Metadata) SetEntities(v []GetTemplatesListResponseInnerAnyOf6MetadataEntitiesInner) {
	o.Entities = v
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *GetTemplatesListResponseInnerAnyOf6Metadata) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6Metadata) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *GetTemplatesListResponseInnerAnyOf6Metadata) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *GetTemplatesListResponseInnerAnyOf6Metadata) SetEventType(v string) {
	o.EventType = &v
}

// GetEventPayload returns the EventPayload field value if set, zero value otherwise.
func (o *GetTemplatesListResponseInnerAnyOf6Metadata) GetEventPayload() map[string]interface{} {
	if o == nil || IsNil(o.EventPayload) {
		var ret map[string]interface{}
		return ret
	}
	return o.EventPayload
}

// GetEventPayloadOk returns a tuple with the EventPayload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesListResponseInnerAnyOf6Metadata) GetEventPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.EventPayload) {
		return map[string]interface{}{}, false
	}
	return o.EventPayload, true
}

// HasEventPayload returns a boolean if a field has been set.
func (o *GetTemplatesListResponseInnerAnyOf6Metadata) HasEventPayload() bool {
	if o != nil && !IsNil(o.EventPayload) {
		return true
	}

	return false
}

// SetEventPayload gets a reference to the given map[string]interface{} and assigns it to the EventPayload field.
func (o *GetTemplatesListResponseInnerAnyOf6Metadata) SetEventPayload(v map[string]interface{}) {
	o.EventPayload = v
}

func (o GetTemplatesListResponseInnerAnyOf6Metadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTemplatesListResponseInnerAnyOf6Metadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Entities) {
		toSerialize["entities"] = o.Entities
	}
	if !IsNil(o.EventType) {
		toSerialize["event_type"] = o.EventType
	}
	if !IsNil(o.EventPayload) {
		toSerialize["event_payload"] = o.EventPayload
	}
	return toSerialize, nil
}

type NullableGetTemplatesListResponseInnerAnyOf6Metadata struct {
	value *GetTemplatesListResponseInnerAnyOf6Metadata
	isSet bool
}

func (v NullableGetTemplatesListResponseInnerAnyOf6Metadata) Get() *GetTemplatesListResponseInnerAnyOf6Metadata {
	return v.value
}

func (v *NullableGetTemplatesListResponseInnerAnyOf6Metadata) Set(val *GetTemplatesListResponseInnerAnyOf6Metadata) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTemplatesListResponseInnerAnyOf6Metadata) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTemplatesListResponseInnerAnyOf6Metadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTemplatesListResponseInnerAnyOf6Metadata(val *GetTemplatesListResponseInnerAnyOf6Metadata) *NullableGetTemplatesListResponseInnerAnyOf6Metadata {
	return &NullableGetTemplatesListResponseInnerAnyOf6Metadata{value: val, isSet: true}
}

func (v NullableGetTemplatesListResponseInnerAnyOf6Metadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTemplatesListResponseInnerAnyOf6Metadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
