/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EmailComponentPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailComponentPostRequest{}

// EmailComponentPostRequest struct for EmailComponentPostRequest
type EmailComponentPostRequest struct {
	ComponentId  string  `json:"componentId"`
	Name         string  `json:"name"`
	Internal     *string `json:"internal,omitempty"`
	InternalPage *string `json:"internalPage,omitempty"`
	Html         *string `json:"html,omitempty"`
}

type _EmailComponentPostRequest EmailComponentPostRequest

// NewEmailComponentPostRequest instantiates a new EmailComponentPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailComponentPostRequest(componentId string, name string) *EmailComponentPostRequest {
	this := EmailComponentPostRequest{}
	this.ComponentId = componentId
	this.Name = name
	return &this
}

// NewEmailComponentPostRequestWithDefaults instantiates a new EmailComponentPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailComponentPostRequestWithDefaults() *EmailComponentPostRequest {
	this := EmailComponentPostRequest{}
	return &this
}

// GetComponentId returns the ComponentId field value
func (o *EmailComponentPostRequest) GetComponentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComponentId
}

// GetComponentIdOk returns a tuple with the ComponentId field value
// and a boolean to check if the value has been set.
func (o *EmailComponentPostRequest) GetComponentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComponentId, true
}

// SetComponentId sets field value
func (o *EmailComponentPostRequest) SetComponentId(v string) {
	o.ComponentId = v
}

// GetName returns the Name field value
func (o *EmailComponentPostRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EmailComponentPostRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EmailComponentPostRequest) SetName(v string) {
	o.Name = v
}

// GetInternal returns the Internal field value if set, zero value otherwise.
func (o *EmailComponentPostRequest) GetInternal() string {
	if o == nil || IsNil(o.Internal) {
		var ret string
		return ret
	}
	return *o.Internal
}

// GetInternalOk returns a tuple with the Internal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailComponentPostRequest) GetInternalOk() (*string, bool) {
	if o == nil || IsNil(o.Internal) {
		return nil, false
	}
	return o.Internal, true
}

// HasInternal returns a boolean if a field has been set.
func (o *EmailComponentPostRequest) HasInternal() bool {
	if o != nil && !IsNil(o.Internal) {
		return true
	}

	return false
}

// SetInternal gets a reference to the given string and assigns it to the Internal field.
func (o *EmailComponentPostRequest) SetInternal(v string) {
	o.Internal = &v
}

// GetInternalPage returns the InternalPage field value if set, zero value otherwise.
func (o *EmailComponentPostRequest) GetInternalPage() string {
	if o == nil || IsNil(o.InternalPage) {
		var ret string
		return ret
	}
	return *o.InternalPage
}

// GetInternalPageOk returns a tuple with the InternalPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailComponentPostRequest) GetInternalPageOk() (*string, bool) {
	if o == nil || IsNil(o.InternalPage) {
		return nil, false
	}
	return o.InternalPage, true
}

// HasInternalPage returns a boolean if a field has been set.
func (o *EmailComponentPostRequest) HasInternalPage() bool {
	if o != nil && !IsNil(o.InternalPage) {
		return true
	}

	return false
}

// SetInternalPage gets a reference to the given string and assigns it to the InternalPage field.
func (o *EmailComponentPostRequest) SetInternalPage(v string) {
	o.InternalPage = &v
}

// GetHtml returns the Html field value if set, zero value otherwise.
func (o *EmailComponentPostRequest) GetHtml() string {
	if o == nil || IsNil(o.Html) {
		var ret string
		return ret
	}
	return *o.Html
}

// GetHtmlOk returns a tuple with the Html field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailComponentPostRequest) GetHtmlOk() (*string, bool) {
	if o == nil || IsNil(o.Html) {
		return nil, false
	}
	return o.Html, true
}

// HasHtml returns a boolean if a field has been set.
func (o *EmailComponentPostRequest) HasHtml() bool {
	if o != nil && !IsNil(o.Html) {
		return true
	}

	return false
}

// SetHtml gets a reference to the given string and assigns it to the Html field.
func (o *EmailComponentPostRequest) SetHtml(v string) {
	o.Html = &v
}

func (o EmailComponentPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailComponentPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["componentId"] = o.ComponentId
	toSerialize["name"] = o.Name
	if !IsNil(o.Internal) {
		toSerialize["internal"] = o.Internal
	}
	if !IsNil(o.InternalPage) {
		toSerialize["internalPage"] = o.InternalPage
	}
	if !IsNil(o.Html) {
		toSerialize["html"] = o.Html
	}
	return toSerialize, nil
}

func (o *EmailComponentPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"componentId",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailComponentPostRequest := _EmailComponentPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailComponentPostRequest)

	if err != nil {
		return err
	}

	*o = EmailComponentPostRequest(varEmailComponentPostRequest)

	return err
}

type NullableEmailComponentPostRequest struct {
	value *EmailComponentPostRequest
	isSet bool
}

func (v NullableEmailComponentPostRequest) Get() *EmailComponentPostRequest {
	return v.value
}

func (v *NullableEmailComponentPostRequest) Set(val *EmailComponentPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailComponentPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailComponentPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailComponentPostRequest(val *EmailComponentPostRequest) *NullableEmailComponentPostRequest {
	return &NullableEmailComponentPostRequest{value: val, isSet: true}
}

func (v NullableEmailComponentPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailComponentPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
