/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MFAStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MFAStatusResponse{}

// MFAStatusResponse struct for MFAStatusResponse
type MFAStatusResponse struct {
	Enabled bool `json:"enabled"`
	// MFA methods supported by the profile MFA API.
	PreferredMfa *string `json:"preferredMfa,omitempty"`
	// Whether the org has the Enterprise add-on required to enable MFA.
	Available bool `json:"available"`
}

type _MFAStatusResponse MFAStatusResponse

// NewMFAStatusResponse instantiates a new MFAStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMFAStatusResponse(enabled bool, available bool) *MFAStatusResponse {
	this := MFAStatusResponse{}
	this.Enabled = enabled
	this.Available = available
	return &this
}

// NewMFAStatusResponseWithDefaults instantiates a new MFAStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMFAStatusResponseWithDefaults() *MFAStatusResponse {
	this := MFAStatusResponse{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *MFAStatusResponse) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *MFAStatusResponse) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *MFAStatusResponse) SetEnabled(v bool) {
	o.Enabled = v
}

// GetPreferredMfa returns the PreferredMfa field value if set, zero value otherwise.
func (o *MFAStatusResponse) GetPreferredMfa() string {
	if o == nil || IsNil(o.PreferredMfa) {
		var ret string
		return ret
	}
	return *o.PreferredMfa
}

// GetPreferredMfaOk returns a tuple with the PreferredMfa field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MFAStatusResponse) GetPreferredMfaOk() (*string, bool) {
	if o == nil || IsNil(o.PreferredMfa) {
		return nil, false
	}
	return o.PreferredMfa, true
}

// HasPreferredMfa returns a boolean if a field has been set.
func (o *MFAStatusResponse) HasPreferredMfa() bool {
	if o != nil && !IsNil(o.PreferredMfa) {
		return true
	}

	return false
}

// SetPreferredMfa gets a reference to the given string and assigns it to the PreferredMfa field.
func (o *MFAStatusResponse) SetPreferredMfa(v string) {
	o.PreferredMfa = &v
}

// GetAvailable returns the Available field value
func (o *MFAStatusResponse) GetAvailable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Available
}

// GetAvailableOk returns a tuple with the Available field value
// and a boolean to check if the value has been set.
func (o *MFAStatusResponse) GetAvailableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Available, true
}

// SetAvailable sets field value
func (o *MFAStatusResponse) SetAvailable(v bool) {
	o.Available = v
}

func (o MFAStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MFAStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	if !IsNil(o.PreferredMfa) {
		toSerialize["preferredMfa"] = o.PreferredMfa
	}
	toSerialize["available"] = o.Available
	return toSerialize, nil
}

func (o *MFAStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"available",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMFAStatusResponse := _MFAStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMFAStatusResponse)

	if err != nil {
		return err
	}

	*o = MFAStatusResponse(varMFAStatusResponse)

	return err
}

type NullableMFAStatusResponse struct {
	value *MFAStatusResponse
	isSet bool
}

func (v NullableMFAStatusResponse) Get() *MFAStatusResponse {
	return v.value
}

func (v *NullableMFAStatusResponse) Set(val *MFAStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMFAStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMFAStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMFAStatusResponse(val *MFAStatusResponse) *NullableMFAStatusResponse {
	return &NullableMFAStatusResponse{value: val, isSet: true}
}

func (v NullableMFAStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMFAStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
