/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SendSmsResponseAnyOf1Error type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendSmsResponseAnyOf1Error{}

// SendSmsResponseAnyOf1Error Error details for SMS send failures.
type SendSmsResponseAnyOf1Error struct {
	// Machine-readable error code.
	Code string `json:"code"`
	// Human-readable error message.
	Message string `json:"message"`
	// Actionable hint for fixing the error.
	Fix *string `json:"fix,omitempty"`
}

type _SendSmsResponseAnyOf1Error SendSmsResponseAnyOf1Error

// NewSendSmsResponseAnyOf1Error instantiates a new SendSmsResponseAnyOf1Error object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendSmsResponseAnyOf1Error(code string, message string) *SendSmsResponseAnyOf1Error {
	this := SendSmsResponseAnyOf1Error{}
	this.Code = code
	this.Message = message
	return &this
}

// NewSendSmsResponseAnyOf1ErrorWithDefaults instantiates a new SendSmsResponseAnyOf1Error object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendSmsResponseAnyOf1ErrorWithDefaults() *SendSmsResponseAnyOf1Error {
	this := SendSmsResponseAnyOf1Error{}
	return &this
}

// GetCode returns the Code field value
func (o *SendSmsResponseAnyOf1Error) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *SendSmsResponseAnyOf1Error) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *SendSmsResponseAnyOf1Error) SetCode(v string) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *SendSmsResponseAnyOf1Error) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *SendSmsResponseAnyOf1Error) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *SendSmsResponseAnyOf1Error) SetMessage(v string) {
	o.Message = v
}

// GetFix returns the Fix field value if set, zero value otherwise.
func (o *SendSmsResponseAnyOf1Error) GetFix() string {
	if o == nil || IsNil(o.Fix) {
		var ret string
		return ret
	}
	return *o.Fix
}

// GetFixOk returns a tuple with the Fix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendSmsResponseAnyOf1Error) GetFixOk() (*string, bool) {
	if o == nil || IsNil(o.Fix) {
		return nil, false
	}
	return o.Fix, true
}

// HasFix returns a boolean if a field has been set.
func (o *SendSmsResponseAnyOf1Error) HasFix() bool {
	if o != nil && !IsNil(o.Fix) {
		return true
	}

	return false
}

// SetFix gets a reference to the given string and assigns it to the Fix field.
func (o *SendSmsResponseAnyOf1Error) SetFix(v string) {
	o.Fix = &v
}

func (o SendSmsResponseAnyOf1Error) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendSmsResponseAnyOf1Error) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["message"] = o.Message
	if !IsNil(o.Fix) {
		toSerialize["fix"] = o.Fix
	}
	return toSerialize, nil
}

func (o *SendSmsResponseAnyOf1Error) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendSmsResponseAnyOf1Error := _SendSmsResponseAnyOf1Error{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendSmsResponseAnyOf1Error)

	if err != nil {
		return err
	}

	*o = SendSmsResponseAnyOf1Error(varSendSmsResponseAnyOf1Error)

	return err
}

type NullableSendSmsResponseAnyOf1Error struct {
	value *SendSmsResponseAnyOf1Error
	isSet bool
}

func (v NullableSendSmsResponseAnyOf1Error) Get() *SendSmsResponseAnyOf1Error {
	return v.value
}

func (v *NullableSendSmsResponseAnyOf1Error) Set(val *SendSmsResponseAnyOf1Error) {
	v.value = val
	v.isSet = true
}

func (v NullableSendSmsResponseAnyOf1Error) IsSet() bool {
	return v.isSet
}

func (v *NullableSendSmsResponseAnyOf1Error) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendSmsResponseAnyOf1Error(val *SendSmsResponseAnyOf1Error) *NullableSendSmsResponseAnyOf1Error {
	return &NullableSendSmsResponseAnyOf1Error{value: val, isSet: true}
}

func (v NullableSendSmsResponseAnyOf1Error) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendSmsResponseAnyOf1Error) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
