/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"encoding/json"
)

// checks if the SenderPostBodyTo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SenderPostBodyTo{}

// SenderPostBodyTo Recipient user. Provide `id`, `email`, or `number` to identify the user.
type SenderPostBodyTo struct {
	// Unique user identifier. Required.
	Id *string `json:"id,omitempty"`
	// User's email address for email notifications.
	Email *string `json:"email,omitempty"`
	// User's phone number for SMS/call notifications.
	Number *string `json:"number,omitempty"`
	// Mobile push tokens (FCM, APN) for push notifications.
	PushTokens []GetUsersResponseUsersInnerPushTokensInner `json:"pushTokens,omitempty"`
	// Web push subscription config from the browser.
	WebPushTokens []GetUsersResponseUsersInnerWebPushTokensInner `json:"webPushTokens,omitempty"`
	// User's timezone (e.g. \"America/New_York\") for scheduling.
	Timezone *string `json:"timezone,omitempty"`
	// The destination channel of slack notifications sent to this user. Can be either of the following: - Channel name, e.g. \"test\" - Channel name with # prefix, e.g. \"#test\" - Channel ID, e.g. \"C1234567890\" - User ID for DM, e.g. \"U1234567890\" - Username with @ prefix, e.g. \"@test\"
	SlackChannel *string                               `json:"slackChannel,omitempty"`
	SlackToken   *GetUsersResponseUsersInnerSlackToken `json:"slackToken,omitempty"`
	// Last activity timestamp. Updated automatically. Read-only.
	LastSeenTime *string `json:"lastSeenTime,omitempty"`
	// Last update timestamp. Read-only.
	UpdatedAt *string `json:"updatedAt,omitempty"`
	// Creation timestamp. Read-only.
	CreatedAt              *string                                           `json:"createdAt,omitempty"`
	EmailSuppressionStatus *GetUsersResponseUsersInnerEmailSuppressionStatus `json:"emailSuppressionStatus,omitempty"`
}

// NewSenderPostBodyTo instantiates a new SenderPostBodyTo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSenderPostBodyTo() *SenderPostBodyTo {
	this := SenderPostBodyTo{}
	return &this
}

// NewSenderPostBodyToWithDefaults instantiates a new SenderPostBodyTo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSenderPostBodyToWithDefaults() *SenderPostBodyTo {
	this := SenderPostBodyTo{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SenderPostBodyTo) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodyTo) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SenderPostBodyTo) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SenderPostBodyTo) SetId(v string) {
	o.Id = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *SenderPostBodyTo) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodyTo) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *SenderPostBodyTo) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *SenderPostBodyTo) SetEmail(v string) {
	o.Email = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *SenderPostBodyTo) GetNumber() string {
	if o == nil || IsNil(o.Number) {
		var ret string
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodyTo) GetNumberOk() (*string, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *SenderPostBodyTo) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given string and assigns it to the Number field.
func (o *SenderPostBodyTo) SetNumber(v string) {
	o.Number = &v
}

// GetPushTokens returns the PushTokens field value if set, zero value otherwise.
func (o *SenderPostBodyTo) GetPushTokens() []GetUsersResponseUsersInnerPushTokensInner {
	if o == nil || IsNil(o.PushTokens) {
		var ret []GetUsersResponseUsersInnerPushTokensInner
		return ret
	}
	return o.PushTokens
}

// GetPushTokensOk returns a tuple with the PushTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodyTo) GetPushTokensOk() ([]GetUsersResponseUsersInnerPushTokensInner, bool) {
	if o == nil || IsNil(o.PushTokens) {
		return nil, false
	}
	return o.PushTokens, true
}

// HasPushTokens returns a boolean if a field has been set.
func (o *SenderPostBodyTo) HasPushTokens() bool {
	if o != nil && !IsNil(o.PushTokens) {
		return true
	}

	return false
}

// SetPushTokens gets a reference to the given []GetUsersResponseUsersInnerPushTokensInner and assigns it to the PushTokens field.
func (o *SenderPostBodyTo) SetPushTokens(v []GetUsersResponseUsersInnerPushTokensInner) {
	o.PushTokens = v
}

// GetWebPushTokens returns the WebPushTokens field value if set, zero value otherwise.
func (o *SenderPostBodyTo) GetWebPushTokens() []GetUsersResponseUsersInnerWebPushTokensInner {
	if o == nil || IsNil(o.WebPushTokens) {
		var ret []GetUsersResponseUsersInnerWebPushTokensInner
		return ret
	}
	return o.WebPushTokens
}

// GetWebPushTokensOk returns a tuple with the WebPushTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodyTo) GetWebPushTokensOk() ([]GetUsersResponseUsersInnerWebPushTokensInner, bool) {
	if o == nil || IsNil(o.WebPushTokens) {
		return nil, false
	}
	return o.WebPushTokens, true
}

// HasWebPushTokens returns a boolean if a field has been set.
func (o *SenderPostBodyTo) HasWebPushTokens() bool {
	if o != nil && !IsNil(o.WebPushTokens) {
		return true
	}

	return false
}

// SetWebPushTokens gets a reference to the given []GetUsersResponseUsersInnerWebPushTokensInner and assigns it to the WebPushTokens field.
func (o *SenderPostBodyTo) SetWebPushTokens(v []GetUsersResponseUsersInnerWebPushTokensInner) {
	o.WebPushTokens = v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *SenderPostBodyTo) GetTimezone() string {
	if o == nil || IsNil(o.Timezone) {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodyTo) GetTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.Timezone) {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *SenderPostBodyTo) HasTimezone() bool {
	if o != nil && !IsNil(o.Timezone) {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *SenderPostBodyTo) SetTimezone(v string) {
	o.Timezone = &v
}

// GetSlackChannel returns the SlackChannel field value if set, zero value otherwise.
func (o *SenderPostBodyTo) GetSlackChannel() string {
	if o == nil || IsNil(o.SlackChannel) {
		var ret string
		return ret
	}
	return *o.SlackChannel
}

// GetSlackChannelOk returns a tuple with the SlackChannel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodyTo) GetSlackChannelOk() (*string, bool) {
	if o == nil || IsNil(o.SlackChannel) {
		return nil, false
	}
	return o.SlackChannel, true
}

// HasSlackChannel returns a boolean if a field has been set.
func (o *SenderPostBodyTo) HasSlackChannel() bool {
	if o != nil && !IsNil(o.SlackChannel) {
		return true
	}

	return false
}

// SetSlackChannel gets a reference to the given string and assigns it to the SlackChannel field.
func (o *SenderPostBodyTo) SetSlackChannel(v string) {
	o.SlackChannel = &v
}

// GetSlackToken returns the SlackToken field value if set, zero value otherwise.
func (o *SenderPostBodyTo) GetSlackToken() GetUsersResponseUsersInnerSlackToken {
	if o == nil || IsNil(o.SlackToken) {
		var ret GetUsersResponseUsersInnerSlackToken
		return ret
	}
	return *o.SlackToken
}

// GetSlackTokenOk returns a tuple with the SlackToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodyTo) GetSlackTokenOk() (*GetUsersResponseUsersInnerSlackToken, bool) {
	if o == nil || IsNil(o.SlackToken) {
		return nil, false
	}
	return o.SlackToken, true
}

// HasSlackToken returns a boolean if a field has been set.
func (o *SenderPostBodyTo) HasSlackToken() bool {
	if o != nil && !IsNil(o.SlackToken) {
		return true
	}

	return false
}

// SetSlackToken gets a reference to the given GetUsersResponseUsersInnerSlackToken and assigns it to the SlackToken field.
func (o *SenderPostBodyTo) SetSlackToken(v GetUsersResponseUsersInnerSlackToken) {
	o.SlackToken = &v
}

// GetLastSeenTime returns the LastSeenTime field value if set, zero value otherwise.
func (o *SenderPostBodyTo) GetLastSeenTime() string {
	if o == nil || IsNil(o.LastSeenTime) {
		var ret string
		return ret
	}
	return *o.LastSeenTime
}

// GetLastSeenTimeOk returns a tuple with the LastSeenTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodyTo) GetLastSeenTimeOk() (*string, bool) {
	if o == nil || IsNil(o.LastSeenTime) {
		return nil, false
	}
	return o.LastSeenTime, true
}

// HasLastSeenTime returns a boolean if a field has been set.
func (o *SenderPostBodyTo) HasLastSeenTime() bool {
	if o != nil && !IsNil(o.LastSeenTime) {
		return true
	}

	return false
}

// SetLastSeenTime gets a reference to the given string and assigns it to the LastSeenTime field.
func (o *SenderPostBodyTo) SetLastSeenTime(v string) {
	o.LastSeenTime = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *SenderPostBodyTo) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodyTo) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *SenderPostBodyTo) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *SenderPostBodyTo) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *SenderPostBodyTo) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodyTo) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *SenderPostBodyTo) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *SenderPostBodyTo) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetEmailSuppressionStatus returns the EmailSuppressionStatus field value if set, zero value otherwise.
func (o *SenderPostBodyTo) GetEmailSuppressionStatus() GetUsersResponseUsersInnerEmailSuppressionStatus {
	if o == nil || IsNil(o.EmailSuppressionStatus) {
		var ret GetUsersResponseUsersInnerEmailSuppressionStatus
		return ret
	}
	return *o.EmailSuppressionStatus
}

// GetEmailSuppressionStatusOk returns a tuple with the EmailSuppressionStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodyTo) GetEmailSuppressionStatusOk() (*GetUsersResponseUsersInnerEmailSuppressionStatus, bool) {
	if o == nil || IsNil(o.EmailSuppressionStatus) {
		return nil, false
	}
	return o.EmailSuppressionStatus, true
}

// HasEmailSuppressionStatus returns a boolean if a field has been set.
func (o *SenderPostBodyTo) HasEmailSuppressionStatus() bool {
	if o != nil && !IsNil(o.EmailSuppressionStatus) {
		return true
	}

	return false
}

// SetEmailSuppressionStatus gets a reference to the given GetUsersResponseUsersInnerEmailSuppressionStatus and assigns it to the EmailSuppressionStatus field.
func (o *SenderPostBodyTo) SetEmailSuppressionStatus(v GetUsersResponseUsersInnerEmailSuppressionStatus) {
	o.EmailSuppressionStatus = &v
}

func (o SenderPostBodyTo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SenderPostBodyTo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	if !IsNil(o.PushTokens) {
		toSerialize["pushTokens"] = o.PushTokens
	}
	if !IsNil(o.WebPushTokens) {
		toSerialize["webPushTokens"] = o.WebPushTokens
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	if !IsNil(o.SlackChannel) {
		toSerialize["slackChannel"] = o.SlackChannel
	}
	if !IsNil(o.SlackToken) {
		toSerialize["slackToken"] = o.SlackToken
	}
	if !IsNil(o.LastSeenTime) {
		toSerialize["lastSeenTime"] = o.LastSeenTime
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.EmailSuppressionStatus) {
		toSerialize["emailSuppressionStatus"] = o.EmailSuppressionStatus
	}
	return toSerialize, nil
}

type NullableSenderPostBodyTo struct {
	value *SenderPostBodyTo
	isSet bool
}

func (v NullableSenderPostBodyTo) Get() *SenderPostBodyTo {
	return v.value
}

func (v *NullableSenderPostBodyTo) Set(val *SenderPostBodyTo) {
	v.value = val
	v.isSet = true
}

func (v NullableSenderPostBodyTo) IsSet() bool {
	return v.isSet
}

func (v *NullableSenderPostBodyTo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSenderPostBodyTo(val *SenderPostBodyTo) *NullableSenderPostBodyTo {
	return &NullableSenderPostBodyTo{value: val, isSet: true}
}

func (v NullableSenderPostBodyTo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSenderPostBodyTo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
