/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SendSmsResponseAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendSmsResponseAnyOf1{}

// SendSmsResponseAnyOf1 Error response for `POST /sms`.
type SendSmsResponseAnyOf1 struct {
	TrackingId string                     `json:"trackingId"`
	Error      SendSmsResponseAnyOf1Error `json:"error"`
}

type _SendSmsResponseAnyOf1 SendSmsResponseAnyOf1

// NewSendSmsResponseAnyOf1 instantiates a new SendSmsResponseAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendSmsResponseAnyOf1(trackingId string, error_ SendSmsResponseAnyOf1Error) *SendSmsResponseAnyOf1 {
	this := SendSmsResponseAnyOf1{}
	this.TrackingId = trackingId
	this.Error = error_
	return &this
}

// NewSendSmsResponseAnyOf1WithDefaults instantiates a new SendSmsResponseAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendSmsResponseAnyOf1WithDefaults() *SendSmsResponseAnyOf1 {
	this := SendSmsResponseAnyOf1{}
	return &this
}

// GetTrackingId returns the TrackingId field value
func (o *SendSmsResponseAnyOf1) GetTrackingId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TrackingId
}

// GetTrackingIdOk returns a tuple with the TrackingId field value
// and a boolean to check if the value has been set.
func (o *SendSmsResponseAnyOf1) GetTrackingIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrackingId, true
}

// SetTrackingId sets field value
func (o *SendSmsResponseAnyOf1) SetTrackingId(v string) {
	o.TrackingId = v
}

// GetError returns the Error field value
func (o *SendSmsResponseAnyOf1) GetError() SendSmsResponseAnyOf1Error {
	if o == nil {
		var ret SendSmsResponseAnyOf1Error
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *SendSmsResponseAnyOf1) GetErrorOk() (*SendSmsResponseAnyOf1Error, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *SendSmsResponseAnyOf1) SetError(v SendSmsResponseAnyOf1Error) {
	o.Error = v
}

func (o SendSmsResponseAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendSmsResponseAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["trackingId"] = o.TrackingId
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *SendSmsResponseAnyOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"trackingId",
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendSmsResponseAnyOf1 := _SendSmsResponseAnyOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendSmsResponseAnyOf1)

	if err != nil {
		return err
	}

	*o = SendSmsResponseAnyOf1(varSendSmsResponseAnyOf1)

	return err
}

type NullableSendSmsResponseAnyOf1 struct {
	value *SendSmsResponseAnyOf1
	isSet bool
}

func (v NullableSendSmsResponseAnyOf1) Get() *SendSmsResponseAnyOf1 {
	return v.value
}

func (v *NullableSendSmsResponseAnyOf1) Set(val *SendSmsResponseAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableSendSmsResponseAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableSendSmsResponseAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendSmsResponseAnyOf1(val *SendSmsResponseAnyOf1) *NullableSendSmsResponseAnyOf1 {
	return &NullableSendSmsResponseAnyOf1{value: val, isSet: true}
}

func (v NullableSendSmsResponseAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendSmsResponseAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
