/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"encoding/json"
	"fmt"
)

// IntercomWebhookDataItem struct for IntercomWebhookDataItem
type IntercomWebhookDataItem struct {
	IntercomWebhookDataItemAnyOf *IntercomWebhookDataItemAnyOf
	MapmapOfStringAny            *map[string]interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *IntercomWebhookDataItem) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into IntercomWebhookDataItemAnyOf
	err = json.Unmarshal(data, &dst.IntercomWebhookDataItemAnyOf)
	if err == nil {
		jsonIntercomWebhookDataItemAnyOf, _ := json.Marshal(dst.IntercomWebhookDataItemAnyOf)
		if string(jsonIntercomWebhookDataItemAnyOf) == "{}" { // empty struct
			dst.IntercomWebhookDataItemAnyOf = nil
		} else {
			return nil // data stored in dst.IntercomWebhookDataItemAnyOf, return on the first match
		}
	} else {
		dst.IntercomWebhookDataItemAnyOf = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(IntercomWebhookDataItem)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src IntercomWebhookDataItem) MarshalJSON() ([]byte, error) {
	if src.IntercomWebhookDataItemAnyOf != nil {
		return json.Marshal(&src.IntercomWebhookDataItemAnyOf)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableIntercomWebhookDataItem struct {
	value *IntercomWebhookDataItem
	isSet bool
}

func (v NullableIntercomWebhookDataItem) Get() *IntercomWebhookDataItem {
	return v.value
}

func (v *NullableIntercomWebhookDataItem) Set(val *IntercomWebhookDataItem) {
	v.value = val
	v.isSet = true
}

func (v NullableIntercomWebhookDataItem) IsSet() bool {
	return v.isSet
}

func (v *NullableIntercomWebhookDataItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntercomWebhookDataItem(val *IntercomWebhookDataItem) *NullableIntercomWebhookDataItem {
	return &NullableIntercomWebhookDataItem{value: val, isSet: true}
}

func (v NullableIntercomWebhookDataItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntercomWebhookDataItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
