/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BillingPostResponseBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingPostResponseBody{}

// BillingPostResponseBody struct for BillingPostResponseBody
type BillingPostResponseBody struct {
	AccountId            string         `json:"accountId"`
	Name                 *string        `json:"name,omitempty"`
	AccountType          string         `json:"accountType"`
	CreatedAt            string         `json:"createdAt"`
	Creator              *string        `json:"creator,omitempty"`
	StripeCustomerId     *string        `json:"stripeCustomerId,omitempty"`
	StripeSubscriptionId *string        `json:"stripeSubscriptionId,omitempty"`
	SubscriptionStatus   NullableString `json:"subscriptionStatus,omitempty"`
	// ISO date (YYYY-MM-DD) when the billing cycle resets. Used for anniversary-based billing.
	AnniversaryDate *string `json:"anniversaryDate,omitempty"`
	// ISO date (YYYY-MM-DD) when the pending downgrade takes effect
	PendingDowngradeEffectiveDate *string `json:"pendingDowngradeEffectiveDate,omitempty"`
	// The account type to switch to when downgrade takes effect
	PendingDowngradeAccountType *string                                            `json:"pendingDowngradeAccountType,omitempty"`
	PendingDowngradeUsageLimit  *BillingPostResponseBodyPendingDowngradeUsageLimit `json:"pendingDowngradeUsageLimit,omitempty"`
	SessionId                   *string                                            `json:"sessionId,omitempty"`
	Url                         *string                                            `json:"url,omitempty"`
}

type _BillingPostResponseBody BillingPostResponseBody

// NewBillingPostResponseBody instantiates a new BillingPostResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingPostResponseBody(accountId string, accountType string, createdAt string) *BillingPostResponseBody {
	this := BillingPostResponseBody{}
	this.AccountId = accountId
	this.AccountType = accountType
	this.CreatedAt = createdAt
	return &this
}

// NewBillingPostResponseBodyWithDefaults instantiates a new BillingPostResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingPostResponseBodyWithDefaults() *BillingPostResponseBody {
	this := BillingPostResponseBody{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *BillingPostResponseBody) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *BillingPostResponseBody) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *BillingPostResponseBody) SetAccountId(v string) {
	o.AccountId = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BillingPostResponseBody) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingPostResponseBody) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BillingPostResponseBody) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BillingPostResponseBody) SetName(v string) {
	o.Name = &v
}

// GetAccountType returns the AccountType field value
func (o *BillingPostResponseBody) GetAccountType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value
// and a boolean to check if the value has been set.
func (o *BillingPostResponseBody) GetAccountTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountType, true
}

// SetAccountType sets field value
func (o *BillingPostResponseBody) SetAccountType(v string) {
	o.AccountType = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *BillingPostResponseBody) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *BillingPostResponseBody) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *BillingPostResponseBody) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetCreator returns the Creator field value if set, zero value otherwise.
func (o *BillingPostResponseBody) GetCreator() string {
	if o == nil || IsNil(o.Creator) {
		var ret string
		return ret
	}
	return *o.Creator
}

// GetCreatorOk returns a tuple with the Creator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingPostResponseBody) GetCreatorOk() (*string, bool) {
	if o == nil || IsNil(o.Creator) {
		return nil, false
	}
	return o.Creator, true
}

// HasCreator returns a boolean if a field has been set.
func (o *BillingPostResponseBody) HasCreator() bool {
	if o != nil && !IsNil(o.Creator) {
		return true
	}

	return false
}

// SetCreator gets a reference to the given string and assigns it to the Creator field.
func (o *BillingPostResponseBody) SetCreator(v string) {
	o.Creator = &v
}

// GetStripeCustomerId returns the StripeCustomerId field value if set, zero value otherwise.
func (o *BillingPostResponseBody) GetStripeCustomerId() string {
	if o == nil || IsNil(o.StripeCustomerId) {
		var ret string
		return ret
	}
	return *o.StripeCustomerId
}

// GetStripeCustomerIdOk returns a tuple with the StripeCustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingPostResponseBody) GetStripeCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.StripeCustomerId) {
		return nil, false
	}
	return o.StripeCustomerId, true
}

// HasStripeCustomerId returns a boolean if a field has been set.
func (o *BillingPostResponseBody) HasStripeCustomerId() bool {
	if o != nil && !IsNil(o.StripeCustomerId) {
		return true
	}

	return false
}

// SetStripeCustomerId gets a reference to the given string and assigns it to the StripeCustomerId field.
func (o *BillingPostResponseBody) SetStripeCustomerId(v string) {
	o.StripeCustomerId = &v
}

// GetStripeSubscriptionId returns the StripeSubscriptionId field value if set, zero value otherwise.
func (o *BillingPostResponseBody) GetStripeSubscriptionId() string {
	if o == nil || IsNil(o.StripeSubscriptionId) {
		var ret string
		return ret
	}
	return *o.StripeSubscriptionId
}

// GetStripeSubscriptionIdOk returns a tuple with the StripeSubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingPostResponseBody) GetStripeSubscriptionIdOk() (*string, bool) {
	if o == nil || IsNil(o.StripeSubscriptionId) {
		return nil, false
	}
	return o.StripeSubscriptionId, true
}

// HasStripeSubscriptionId returns a boolean if a field has been set.
func (o *BillingPostResponseBody) HasStripeSubscriptionId() bool {
	if o != nil && !IsNil(o.StripeSubscriptionId) {
		return true
	}

	return false
}

// SetStripeSubscriptionId gets a reference to the given string and assigns it to the StripeSubscriptionId field.
func (o *BillingPostResponseBody) SetStripeSubscriptionId(v string) {
	o.StripeSubscriptionId = &v
}

// GetSubscriptionStatus returns the SubscriptionStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BillingPostResponseBody) GetSubscriptionStatus() string {
	if o == nil || IsNil(o.SubscriptionStatus.Get()) {
		var ret string
		return ret
	}
	return *o.SubscriptionStatus.Get()
}

// GetSubscriptionStatusOk returns a tuple with the SubscriptionStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BillingPostResponseBody) GetSubscriptionStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubscriptionStatus.Get(), o.SubscriptionStatus.IsSet()
}

// HasSubscriptionStatus returns a boolean if a field has been set.
func (o *BillingPostResponseBody) HasSubscriptionStatus() bool {
	if o != nil && o.SubscriptionStatus.IsSet() {
		return true
	}

	return false
}

// SetSubscriptionStatus gets a reference to the given NullableString and assigns it to the SubscriptionStatus field.
func (o *BillingPostResponseBody) SetSubscriptionStatus(v string) {
	o.SubscriptionStatus.Set(&v)
}

// SetSubscriptionStatusNil sets the value for SubscriptionStatus to be an explicit nil
func (o *BillingPostResponseBody) SetSubscriptionStatusNil() {
	o.SubscriptionStatus.Set(nil)
}

// UnsetSubscriptionStatus ensures that no value is present for SubscriptionStatus, not even an explicit nil
func (o *BillingPostResponseBody) UnsetSubscriptionStatus() {
	o.SubscriptionStatus.Unset()
}

// GetAnniversaryDate returns the AnniversaryDate field value if set, zero value otherwise.
func (o *BillingPostResponseBody) GetAnniversaryDate() string {
	if o == nil || IsNil(o.AnniversaryDate) {
		var ret string
		return ret
	}
	return *o.AnniversaryDate
}

// GetAnniversaryDateOk returns a tuple with the AnniversaryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingPostResponseBody) GetAnniversaryDateOk() (*string, bool) {
	if o == nil || IsNil(o.AnniversaryDate) {
		return nil, false
	}
	return o.AnniversaryDate, true
}

// HasAnniversaryDate returns a boolean if a field has been set.
func (o *BillingPostResponseBody) HasAnniversaryDate() bool {
	if o != nil && !IsNil(o.AnniversaryDate) {
		return true
	}

	return false
}

// SetAnniversaryDate gets a reference to the given string and assigns it to the AnniversaryDate field.
func (o *BillingPostResponseBody) SetAnniversaryDate(v string) {
	o.AnniversaryDate = &v
}

// GetPendingDowngradeEffectiveDate returns the PendingDowngradeEffectiveDate field value if set, zero value otherwise.
func (o *BillingPostResponseBody) GetPendingDowngradeEffectiveDate() string {
	if o == nil || IsNil(o.PendingDowngradeEffectiveDate) {
		var ret string
		return ret
	}
	return *o.PendingDowngradeEffectiveDate
}

// GetPendingDowngradeEffectiveDateOk returns a tuple with the PendingDowngradeEffectiveDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingPostResponseBody) GetPendingDowngradeEffectiveDateOk() (*string, bool) {
	if o == nil || IsNil(o.PendingDowngradeEffectiveDate) {
		return nil, false
	}
	return o.PendingDowngradeEffectiveDate, true
}

// HasPendingDowngradeEffectiveDate returns a boolean if a field has been set.
func (o *BillingPostResponseBody) HasPendingDowngradeEffectiveDate() bool {
	if o != nil && !IsNil(o.PendingDowngradeEffectiveDate) {
		return true
	}

	return false
}

// SetPendingDowngradeEffectiveDate gets a reference to the given string and assigns it to the PendingDowngradeEffectiveDate field.
func (o *BillingPostResponseBody) SetPendingDowngradeEffectiveDate(v string) {
	o.PendingDowngradeEffectiveDate = &v
}

// GetPendingDowngradeAccountType returns the PendingDowngradeAccountType field value if set, zero value otherwise.
func (o *BillingPostResponseBody) GetPendingDowngradeAccountType() string {
	if o == nil || IsNil(o.PendingDowngradeAccountType) {
		var ret string
		return ret
	}
	return *o.PendingDowngradeAccountType
}

// GetPendingDowngradeAccountTypeOk returns a tuple with the PendingDowngradeAccountType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingPostResponseBody) GetPendingDowngradeAccountTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PendingDowngradeAccountType) {
		return nil, false
	}
	return o.PendingDowngradeAccountType, true
}

// HasPendingDowngradeAccountType returns a boolean if a field has been set.
func (o *BillingPostResponseBody) HasPendingDowngradeAccountType() bool {
	if o != nil && !IsNil(o.PendingDowngradeAccountType) {
		return true
	}

	return false
}

// SetPendingDowngradeAccountType gets a reference to the given string and assigns it to the PendingDowngradeAccountType field.
func (o *BillingPostResponseBody) SetPendingDowngradeAccountType(v string) {
	o.PendingDowngradeAccountType = &v
}

// GetPendingDowngradeUsageLimit returns the PendingDowngradeUsageLimit field value if set, zero value otherwise.
func (o *BillingPostResponseBody) GetPendingDowngradeUsageLimit() BillingPostResponseBodyPendingDowngradeUsageLimit {
	if o == nil || IsNil(o.PendingDowngradeUsageLimit) {
		var ret BillingPostResponseBodyPendingDowngradeUsageLimit
		return ret
	}
	return *o.PendingDowngradeUsageLimit
}

// GetPendingDowngradeUsageLimitOk returns a tuple with the PendingDowngradeUsageLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingPostResponseBody) GetPendingDowngradeUsageLimitOk() (*BillingPostResponseBodyPendingDowngradeUsageLimit, bool) {
	if o == nil || IsNil(o.PendingDowngradeUsageLimit) {
		return nil, false
	}
	return o.PendingDowngradeUsageLimit, true
}

// HasPendingDowngradeUsageLimit returns a boolean if a field has been set.
func (o *BillingPostResponseBody) HasPendingDowngradeUsageLimit() bool {
	if o != nil && !IsNil(o.PendingDowngradeUsageLimit) {
		return true
	}

	return false
}

// SetPendingDowngradeUsageLimit gets a reference to the given BillingPostResponseBodyPendingDowngradeUsageLimit and assigns it to the PendingDowngradeUsageLimit field.
func (o *BillingPostResponseBody) SetPendingDowngradeUsageLimit(v BillingPostResponseBodyPendingDowngradeUsageLimit) {
	o.PendingDowngradeUsageLimit = &v
}

// GetSessionId returns the SessionId field value if set, zero value otherwise.
func (o *BillingPostResponseBody) GetSessionId() string {
	if o == nil || IsNil(o.SessionId) {
		var ret string
		return ret
	}
	return *o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingPostResponseBody) GetSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SessionId) {
		return nil, false
	}
	return o.SessionId, true
}

// HasSessionId returns a boolean if a field has been set.
func (o *BillingPostResponseBody) HasSessionId() bool {
	if o != nil && !IsNil(o.SessionId) {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given string and assigns it to the SessionId field.
func (o *BillingPostResponseBody) SetSessionId(v string) {
	o.SessionId = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *BillingPostResponseBody) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingPostResponseBody) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *BillingPostResponseBody) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *BillingPostResponseBody) SetUrl(v string) {
	o.Url = &v
}

func (o BillingPostResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingPostResponseBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountId"] = o.AccountId
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["accountType"] = o.AccountType
	toSerialize["createdAt"] = o.CreatedAt
	if !IsNil(o.Creator) {
		toSerialize["creator"] = o.Creator
	}
	if !IsNil(o.StripeCustomerId) {
		toSerialize["stripeCustomerId"] = o.StripeCustomerId
	}
	if !IsNil(o.StripeSubscriptionId) {
		toSerialize["stripeSubscriptionId"] = o.StripeSubscriptionId
	}
	if o.SubscriptionStatus.IsSet() {
		toSerialize["subscriptionStatus"] = o.SubscriptionStatus.Get()
	}
	if !IsNil(o.AnniversaryDate) {
		toSerialize["anniversaryDate"] = o.AnniversaryDate
	}
	if !IsNil(o.PendingDowngradeEffectiveDate) {
		toSerialize["pendingDowngradeEffectiveDate"] = o.PendingDowngradeEffectiveDate
	}
	if !IsNil(o.PendingDowngradeAccountType) {
		toSerialize["pendingDowngradeAccountType"] = o.PendingDowngradeAccountType
	}
	if !IsNil(o.PendingDowngradeUsageLimit) {
		toSerialize["pendingDowngradeUsageLimit"] = o.PendingDowngradeUsageLimit
	}
	if !IsNil(o.SessionId) {
		toSerialize["sessionId"] = o.SessionId
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

func (o *BillingPostResponseBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountId",
		"accountType",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingPostResponseBody := _BillingPostResponseBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingPostResponseBody)

	if err != nil {
		return err
	}

	*o = BillingPostResponseBody(varBillingPostResponseBody)

	return err
}

type NullableBillingPostResponseBody struct {
	value *BillingPostResponseBody
	isSet bool
}

func (v NullableBillingPostResponseBody) Get() *BillingPostResponseBody {
	return v.value
}

func (v *NullableBillingPostResponseBody) Set(val *BillingPostResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingPostResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingPostResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingPostResponseBody(val *BillingPostResponseBody) *NullableBillingPostResponseBody {
	return &NullableBillingPostResponseBody{value: val, isSet: true}
}

func (v NullableBillingPostResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingPostResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
