/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UserPreferencesPOSTResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserPreferencesPOSTResponseInner{}

// UserPreferencesPOSTResponseInner struct for UserPreferencesPOSTResponseInner
type UserPreferencesPOSTResponseInner struct {
	EnvId             string                                                `json:"envId"`
	UserId            string                                                `json:"userId"`
	NotificationId    string                                                `json:"notificationId"`
	SubNotificationId string                                                `json:"subNotificationId"`
	ChannelsStates    []UserPreferencesPOSTResponseInnerChannelsStatesInner `json:"channelsStates,omitempty"`
}

type _UserPreferencesPOSTResponseInner UserPreferencesPOSTResponseInner

// NewUserPreferencesPOSTResponseInner instantiates a new UserPreferencesPOSTResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserPreferencesPOSTResponseInner(envId string, userId string, notificationId string, subNotificationId string) *UserPreferencesPOSTResponseInner {
	this := UserPreferencesPOSTResponseInner{}
	this.EnvId = envId
	this.UserId = userId
	this.NotificationId = notificationId
	this.SubNotificationId = subNotificationId
	return &this
}

// NewUserPreferencesPOSTResponseInnerWithDefaults instantiates a new UserPreferencesPOSTResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserPreferencesPOSTResponseInnerWithDefaults() *UserPreferencesPOSTResponseInner {
	this := UserPreferencesPOSTResponseInner{}
	return &this
}

// GetEnvId returns the EnvId field value
func (o *UserPreferencesPOSTResponseInner) GetEnvId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvId
}

// GetEnvIdOk returns a tuple with the EnvId field value
// and a boolean to check if the value has been set.
func (o *UserPreferencesPOSTResponseInner) GetEnvIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvId, true
}

// SetEnvId sets field value
func (o *UserPreferencesPOSTResponseInner) SetEnvId(v string) {
	o.EnvId = v
}

// GetUserId returns the UserId field value
func (o *UserPreferencesPOSTResponseInner) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *UserPreferencesPOSTResponseInner) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *UserPreferencesPOSTResponseInner) SetUserId(v string) {
	o.UserId = v
}

// GetNotificationId returns the NotificationId field value
func (o *UserPreferencesPOSTResponseInner) GetNotificationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NotificationId
}

// GetNotificationIdOk returns a tuple with the NotificationId field value
// and a boolean to check if the value has been set.
func (o *UserPreferencesPOSTResponseInner) GetNotificationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotificationId, true
}

// SetNotificationId sets field value
func (o *UserPreferencesPOSTResponseInner) SetNotificationId(v string) {
	o.NotificationId = v
}

// GetSubNotificationId returns the SubNotificationId field value
func (o *UserPreferencesPOSTResponseInner) GetSubNotificationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubNotificationId
}

// GetSubNotificationIdOk returns a tuple with the SubNotificationId field value
// and a boolean to check if the value has been set.
func (o *UserPreferencesPOSTResponseInner) GetSubNotificationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubNotificationId, true
}

// SetSubNotificationId sets field value
func (o *UserPreferencesPOSTResponseInner) SetSubNotificationId(v string) {
	o.SubNotificationId = v
}

// GetChannelsStates returns the ChannelsStates field value if set, zero value otherwise.
func (o *UserPreferencesPOSTResponseInner) GetChannelsStates() []UserPreferencesPOSTResponseInnerChannelsStatesInner {
	if o == nil || IsNil(o.ChannelsStates) {
		var ret []UserPreferencesPOSTResponseInnerChannelsStatesInner
		return ret
	}
	return o.ChannelsStates
}

// GetChannelsStatesOk returns a tuple with the ChannelsStates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserPreferencesPOSTResponseInner) GetChannelsStatesOk() ([]UserPreferencesPOSTResponseInnerChannelsStatesInner, bool) {
	if o == nil || IsNil(o.ChannelsStates) {
		return nil, false
	}
	return o.ChannelsStates, true
}

// HasChannelsStates returns a boolean if a field has been set.
func (o *UserPreferencesPOSTResponseInner) HasChannelsStates() bool {
	if o != nil && !IsNil(o.ChannelsStates) {
		return true
	}

	return false
}

// SetChannelsStates gets a reference to the given []UserPreferencesPOSTResponseInnerChannelsStatesInner and assigns it to the ChannelsStates field.
func (o *UserPreferencesPOSTResponseInner) SetChannelsStates(v []UserPreferencesPOSTResponseInnerChannelsStatesInner) {
	o.ChannelsStates = v
}

func (o UserPreferencesPOSTResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserPreferencesPOSTResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["envId"] = o.EnvId
	toSerialize["userId"] = o.UserId
	toSerialize["notificationId"] = o.NotificationId
	toSerialize["subNotificationId"] = o.SubNotificationId
	if !IsNil(o.ChannelsStates) {
		toSerialize["channelsStates"] = o.ChannelsStates
	}
	return toSerialize, nil
}

func (o *UserPreferencesPOSTResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"envId",
		"userId",
		"notificationId",
		"subNotificationId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserPreferencesPOSTResponseInner := _UserPreferencesPOSTResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserPreferencesPOSTResponseInner)

	if err != nil {
		return err
	}

	*o = UserPreferencesPOSTResponseInner(varUserPreferencesPOSTResponseInner)

	return err
}

type NullableUserPreferencesPOSTResponseInner struct {
	value *UserPreferencesPOSTResponseInner
	isSet bool
}

func (v NullableUserPreferencesPOSTResponseInner) Get() *UserPreferencesPOSTResponseInner {
	return v.value
}

func (v *NullableUserPreferencesPOSTResponseInner) Set(val *UserPreferencesPOSTResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUserPreferencesPOSTResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUserPreferencesPOSTResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserPreferencesPOSTResponseInner(val *UserPreferencesPOSTResponseInner) *NullableUserPreferencesPOSTResponseInner {
	return &NullableUserPreferencesPOSTResponseInner{value: val, isSet: true}
}

func (v NullableUserPreferencesPOSTResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserPreferencesPOSTResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
