/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MemberInviteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemberInviteRequest{}

// MemberInviteRequest struct for MemberInviteRequest
type MemberInviteRequest struct {
	Email string  `json:"email"`
	Role  *string `json:"role,omitempty"`
}

type _MemberInviteRequest MemberInviteRequest

// NewMemberInviteRequest instantiates a new MemberInviteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberInviteRequest(email string) *MemberInviteRequest {
	this := MemberInviteRequest{}
	this.Email = email
	return &this
}

// NewMemberInviteRequestWithDefaults instantiates a new MemberInviteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberInviteRequestWithDefaults() *MemberInviteRequest {
	this := MemberInviteRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *MemberInviteRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *MemberInviteRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *MemberInviteRequest) SetEmail(v string) {
	o.Email = v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *MemberInviteRequest) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemberInviteRequest) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *MemberInviteRequest) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *MemberInviteRequest) SetRole(v string) {
	o.Role = &v
}

func (o MemberInviteRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemberInviteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

func (o *MemberInviteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemberInviteRequest := _MemberInviteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemberInviteRequest)

	if err != nil {
		return err
	}

	*o = MemberInviteRequest(varMemberInviteRequest)

	return err
}

type NullableMemberInviteRequest struct {
	value *MemberInviteRequest
	isSet bool
}

func (v NullableMemberInviteRequest) Get() *MemberInviteRequest {
	return v.value
}

func (v *NullableMemberInviteRequest) Set(val *MemberInviteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberInviteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberInviteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberInviteRequest(val *MemberInviteRequest) *NullableMemberInviteRequest {
	return &NullableMemberInviteRequest{value: val, isSet: true}
}

func (v NullableMemberInviteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberInviteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
