/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EventsWebhookUpsertRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventsWebhookUpsertRequest{}

// EventsWebhookUpsertRequest Request body for creating or updating the events webhook configuration.
type EventsWebhookUpsertRequest struct {
	// Destination URL that receives webhook event payloads. Must be a valid http(s) URL.
	Webhook string `json:"webhook"`
	// List of event types that should be forwarded to the webhook URL.
	Events []string `json:"events"`
}

type _EventsWebhookUpsertRequest EventsWebhookUpsertRequest

// NewEventsWebhookUpsertRequest instantiates a new EventsWebhookUpsertRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventsWebhookUpsertRequest(webhook string, events []string) *EventsWebhookUpsertRequest {
	this := EventsWebhookUpsertRequest{}
	this.Webhook = webhook
	this.Events = events
	return &this
}

// NewEventsWebhookUpsertRequestWithDefaults instantiates a new EventsWebhookUpsertRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventsWebhookUpsertRequestWithDefaults() *EventsWebhookUpsertRequest {
	this := EventsWebhookUpsertRequest{}
	return &this
}

// GetWebhook returns the Webhook field value
func (o *EventsWebhookUpsertRequest) GetWebhook() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Webhook
}

// GetWebhookOk returns a tuple with the Webhook field value
// and a boolean to check if the value has been set.
func (o *EventsWebhookUpsertRequest) GetWebhookOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Webhook, true
}

// SetWebhook sets field value
func (o *EventsWebhookUpsertRequest) SetWebhook(v string) {
	o.Webhook = v
}

// GetEvents returns the Events field value
func (o *EventsWebhookUpsertRequest) GetEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *EventsWebhookUpsertRequest) GetEventsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *EventsWebhookUpsertRequest) SetEvents(v []string) {
	o.Events = v
}

func (o EventsWebhookUpsertRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventsWebhookUpsertRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["webhook"] = o.Webhook
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *EventsWebhookUpsertRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"webhook",
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventsWebhookUpsertRequest := _EventsWebhookUpsertRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventsWebhookUpsertRequest)

	if err != nil {
		return err
	}

	*o = EventsWebhookUpsertRequest(varEventsWebhookUpsertRequest)

	return err
}

type NullableEventsWebhookUpsertRequest struct {
	value *EventsWebhookUpsertRequest
	isSet bool
}

func (v NullableEventsWebhookUpsertRequest) Get() *EventsWebhookUpsertRequest {
	return v.value
}

func (v *NullableEventsWebhookUpsertRequest) Set(val *EventsWebhookUpsertRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEventsWebhookUpsertRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEventsWebhookUpsertRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventsWebhookUpsertRequest(val *EventsWebhookUpsertRequest) *NullableEventsWebhookUpsertRequest {
	return &NullableEventsWebhookUpsertRequest{value: val, isSet: true}
}

func (v NullableEventsWebhookUpsertRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventsWebhookUpsertRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
