/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"encoding/json"
	"fmt"
)

// GetUsersResponseUsersInnerPropertiesValue struct for GetUsersResponseUsersInnerPropertiesValue
type GetUsersResponseUsersInnerPropertiesValue struct {
	Bool    *bool
	Float32 *float32
	String  *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetUsersResponseUsersInnerPropertiesValue) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Bool
	err = json.Unmarshal(data, &dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			return nil // data stored in dst.Bool, return on the first match
		}
	} else {
		dst.Bool = nil
	}

	// try to unmarshal JSON data into Float32
	err = json.Unmarshal(data, &dst.Float32)
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			return nil // data stored in dst.Float32, return on the first match
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetUsersResponseUsersInnerPropertiesValue)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetUsersResponseUsersInnerPropertiesValue) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableGetUsersResponseUsersInnerPropertiesValue struct {
	value *GetUsersResponseUsersInnerPropertiesValue
	isSet bool
}

func (v NullableGetUsersResponseUsersInnerPropertiesValue) Get() *GetUsersResponseUsersInnerPropertiesValue {
	return v.value
}

func (v *NullableGetUsersResponseUsersInnerPropertiesValue) Set(val *GetUsersResponseUsersInnerPropertiesValue) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUsersResponseUsersInnerPropertiesValue) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUsersResponseUsersInnerPropertiesValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUsersResponseUsersInnerPropertiesValue(val *GetUsersResponseUsersInnerPropertiesValue) *NullableGetUsersResponseUsersInnerPropertiesValue {
	return &NullableGetUsersResponseUsersInnerPropertiesValue{value: val, isSet: true}
}

func (v NullableGetUsersResponseUsersInnerPropertiesValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUsersResponseUsersInnerPropertiesValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
