/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ChangePhoneRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangePhoneRequest{}

// ChangePhoneRequest struct for ChangePhoneRequest
type ChangePhoneRequest struct {
	PhoneNumber string `json:"phoneNumber"`
}

type _ChangePhoneRequest ChangePhoneRequest

// NewChangePhoneRequest instantiates a new ChangePhoneRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangePhoneRequest(phoneNumber string) *ChangePhoneRequest {
	this := ChangePhoneRequest{}
	this.PhoneNumber = phoneNumber
	return &this
}

// NewChangePhoneRequestWithDefaults instantiates a new ChangePhoneRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangePhoneRequestWithDefaults() *ChangePhoneRequest {
	this := ChangePhoneRequest{}
	return &this
}

// GetPhoneNumber returns the PhoneNumber field value
func (o *ChangePhoneRequest) GetPhoneNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value
// and a boolean to check if the value has been set.
func (o *ChangePhoneRequest) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneNumber, true
}

// SetPhoneNumber sets field value
func (o *ChangePhoneRequest) SetPhoneNumber(v string) {
	o.PhoneNumber = v
}

func (o ChangePhoneRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangePhoneRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phoneNumber"] = o.PhoneNumber
	return toSerialize, nil
}

func (o *ChangePhoneRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phoneNumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChangePhoneRequest := _ChangePhoneRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChangePhoneRequest)

	if err != nil {
		return err
	}

	*o = ChangePhoneRequest(varChangePhoneRequest)

	return err
}

type NullableChangePhoneRequest struct {
	value *ChangePhoneRequest
	isSet bool
}

func (v NullableChangePhoneRequest) Get() *ChangePhoneRequest {
	return v.value
}

func (v *NullableChangePhoneRequest) Set(val *ChangePhoneRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChangePhoneRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChangePhoneRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangePhoneRequest(val *ChangePhoneRequest) *NullableChangePhoneRequest {
	return &NullableChangePhoneRequest{value: val, isSet: true}
}

func (v NullableChangePhoneRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangePhoneRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
