/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SlackOauthRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SlackOauthRequest{}

// SlackOauthRequest struct for SlackOauthRequest
type SlackOauthRequest struct {
	Code        string `json:"code"`
	RedirectUri string `json:"redirect_uri"`
}

type _SlackOauthRequest SlackOauthRequest

// NewSlackOauthRequest instantiates a new SlackOauthRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlackOauthRequest(code string, redirectUri string) *SlackOauthRequest {
	this := SlackOauthRequest{}
	this.Code = code
	this.RedirectUri = redirectUri
	return &this
}

// NewSlackOauthRequestWithDefaults instantiates a new SlackOauthRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlackOauthRequestWithDefaults() *SlackOauthRequest {
	this := SlackOauthRequest{}
	return &this
}

// GetCode returns the Code field value
func (o *SlackOauthRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *SlackOauthRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *SlackOauthRequest) SetCode(v string) {
	o.Code = v
}

// GetRedirectUri returns the RedirectUri field value
func (o *SlackOauthRequest) GetRedirectUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RedirectUri
}

// GetRedirectUriOk returns a tuple with the RedirectUri field value
// and a boolean to check if the value has been set.
func (o *SlackOauthRequest) GetRedirectUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RedirectUri, true
}

// SetRedirectUri sets field value
func (o *SlackOauthRequest) SetRedirectUri(v string) {
	o.RedirectUri = v
}

func (o SlackOauthRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SlackOauthRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["redirect_uri"] = o.RedirectUri
	return toSerialize, nil
}

func (o *SlackOauthRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"redirect_uri",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSlackOauthRequest := _SlackOauthRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSlackOauthRequest)

	if err != nil {
		return err
	}

	*o = SlackOauthRequest(varSlackOauthRequest)

	return err
}

type NullableSlackOauthRequest struct {
	value *SlackOauthRequest
	isSet bool
}

func (v NullableSlackOauthRequest) Get() *SlackOauthRequest {
	return v.value
}

func (v *NullableSlackOauthRequest) Set(val *SlackOauthRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSlackOauthRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSlackOauthRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlackOauthRequest(val *SlackOauthRequest) *NullableSlackOauthRequest {
	return &NullableSlackOauthRequest{value: val, isSet: true}
}

func (v NullableSlackOauthRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlackOauthRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
