/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AccountGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountGetResponse{}

// AccountGetResponse GET /account response: basic account info (billing fields are on the organization).
type AccountGetResponse struct {
	AccountId      string `json:"accountId"`
	OrganizationId string `json:"organizationId"`
	Name           string `json:"name"`
	CreatedAt      string `json:"createdAt"`
}

type _AccountGetResponse AccountGetResponse

// NewAccountGetResponse instantiates a new AccountGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountGetResponse(accountId string, organizationId string, name string, createdAt string) *AccountGetResponse {
	this := AccountGetResponse{}
	this.AccountId = accountId
	this.OrganizationId = organizationId
	this.Name = name
	this.CreatedAt = createdAt
	return &this
}

// NewAccountGetResponseWithDefaults instantiates a new AccountGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountGetResponseWithDefaults() *AccountGetResponse {
	this := AccountGetResponse{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *AccountGetResponse) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *AccountGetResponse) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *AccountGetResponse) SetAccountId(v string) {
	o.AccountId = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *AccountGetResponse) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *AccountGetResponse) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *AccountGetResponse) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetName returns the Name field value
func (o *AccountGetResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AccountGetResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AccountGetResponse) SetName(v string) {
	o.Name = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AccountGetResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AccountGetResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AccountGetResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o AccountGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountId"] = o.AccountId
	toSerialize["organizationId"] = o.OrganizationId
	toSerialize["name"] = o.Name
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

func (o *AccountGetResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountId",
		"organizationId",
		"name",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountGetResponse := _AccountGetResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccountGetResponse)

	if err != nil {
		return err
	}

	*o = AccountGetResponse(varAccountGetResponse)

	return err
}

type NullableAccountGetResponse struct {
	value *AccountGetResponse
	isSet bool
}

func (v NullableAccountGetResponse) Get() *AccountGetResponse {
	return v.value
}

func (v *NullableAccountGetResponse) Set(val *AccountGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountGetResponse(val *AccountGetResponse) *NullableAccountGetResponse {
	return &NullableAccountGetResponse{value: val, isSet: true}
}

func (v NullableAccountGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
