/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"encoding/json"
	"fmt"
)

// GetTemplatesResponse Single template or list of templates (get handler: one when templateId provided, list when not).
type GetTemplatesResponse struct {
	GetTemplatesListResponseInner        *GetTemplatesListResponseInner
	ArrayOfGetTemplatesListResponseInner *[]GetTemplatesListResponseInner
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetTemplatesResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into GetTemplatesListResponseInner
	err = json.Unmarshal(data, &dst.GetTemplatesListResponseInner)
	if err == nil {
		jsonGetTemplatesListResponseInner, _ := json.Marshal(dst.GetTemplatesListResponseInner)
		if string(jsonGetTemplatesListResponseInner) == "{}" { // empty struct
			dst.GetTemplatesListResponseInner = nil
		} else {
			return nil // data stored in dst.GetTemplatesListResponseInner, return on the first match
		}
	} else {
		dst.GetTemplatesListResponseInner = nil
	}

	// try to unmarshal JSON data into ArrayOfGetTemplatesListResponseInner
	err = json.Unmarshal(data, &dst.ArrayOfGetTemplatesListResponseInner)
	if err == nil {
		jsonArrayOfGetTemplatesListResponseInner, _ := json.Marshal(dst.ArrayOfGetTemplatesListResponseInner)
		if string(jsonArrayOfGetTemplatesListResponseInner) == "{}" { // empty struct
			dst.ArrayOfGetTemplatesListResponseInner = nil
		} else {
			return nil // data stored in dst.ArrayOfGetTemplatesListResponseInner, return on the first match
		}
	} else {
		dst.ArrayOfGetTemplatesListResponseInner = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetTemplatesResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetTemplatesResponse) MarshalJSON() ([]byte, error) {
	if src.GetTemplatesListResponseInner != nil {
		return json.Marshal(&src.GetTemplatesListResponseInner)
	}

	if src.ArrayOfGetTemplatesListResponseInner != nil {
		return json.Marshal(&src.ArrayOfGetTemplatesListResponseInner)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableGetTemplatesResponse struct {
	value *GetTemplatesResponse
	isSet bool
}

func (v NullableGetTemplatesResponse) Get() *GetTemplatesResponse {
	return v.value
}

func (v *NullableGetTemplatesResponse) Set(val *GetTemplatesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTemplatesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTemplatesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTemplatesResponse(val *GetTemplatesResponse) *NullableGetTemplatesResponse {
	return &NullableGetTemplatesResponse{value: val, isSet: true}
}

func (v NullableGetTemplatesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTemplatesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
