/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TenDlcBrandCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenDlcBrandCreateRequest{}

// TenDlcBrandCreateRequest Request body for POST /registrations/us/10dlc/brand
type TenDlcBrandCreateRequest struct {
	ScenarioId             string  `json:"scenarioId"`
	BusinessType           string  `json:"businessType"`
	LegalName              string  `json:"legalName"`
	TaxId                  *string `json:"taxId,omitempty"`
	Website                string  `json:"website"`
	Country                string  `json:"country"`
	Street                 *string `json:"street,omitempty"`
	City                   *string `json:"city,omitempty"`
	State                  *string `json:"state,omitempty"`
	PostalCode             *string `json:"postalCode,omitempty"`
	ComplianceContactEmail string  `json:"complianceContactEmail"`
	ComplianceContactPhone string  `json:"complianceContactPhone"`
}

type _TenDlcBrandCreateRequest TenDlcBrandCreateRequest

// NewTenDlcBrandCreateRequest instantiates a new TenDlcBrandCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenDlcBrandCreateRequest(scenarioId string, businessType string, legalName string, website string, country string, complianceContactEmail string, complianceContactPhone string) *TenDlcBrandCreateRequest {
	this := TenDlcBrandCreateRequest{}
	this.ScenarioId = scenarioId
	this.BusinessType = businessType
	this.LegalName = legalName
	this.Website = website
	this.Country = country
	this.ComplianceContactEmail = complianceContactEmail
	this.ComplianceContactPhone = complianceContactPhone
	return &this
}

// NewTenDlcBrandCreateRequestWithDefaults instantiates a new TenDlcBrandCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenDlcBrandCreateRequestWithDefaults() *TenDlcBrandCreateRequest {
	this := TenDlcBrandCreateRequest{}
	return &this
}

// GetScenarioId returns the ScenarioId field value
func (o *TenDlcBrandCreateRequest) GetScenarioId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScenarioId
}

// GetScenarioIdOk returns a tuple with the ScenarioId field value
// and a boolean to check if the value has been set.
func (o *TenDlcBrandCreateRequest) GetScenarioIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScenarioId, true
}

// SetScenarioId sets field value
func (o *TenDlcBrandCreateRequest) SetScenarioId(v string) {
	o.ScenarioId = v
}

// GetBusinessType returns the BusinessType field value
func (o *TenDlcBrandCreateRequest) GetBusinessType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BusinessType
}

// GetBusinessTypeOk returns a tuple with the BusinessType field value
// and a boolean to check if the value has been set.
func (o *TenDlcBrandCreateRequest) GetBusinessTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BusinessType, true
}

// SetBusinessType sets field value
func (o *TenDlcBrandCreateRequest) SetBusinessType(v string) {
	o.BusinessType = v
}

// GetLegalName returns the LegalName field value
func (o *TenDlcBrandCreateRequest) GetLegalName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LegalName
}

// GetLegalNameOk returns a tuple with the LegalName field value
// and a boolean to check if the value has been set.
func (o *TenDlcBrandCreateRequest) GetLegalNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LegalName, true
}

// SetLegalName sets field value
func (o *TenDlcBrandCreateRequest) SetLegalName(v string) {
	o.LegalName = v
}

// GetTaxId returns the TaxId field value if set, zero value otherwise.
func (o *TenDlcBrandCreateRequest) GetTaxId() string {
	if o == nil || IsNil(o.TaxId) {
		var ret string
		return ret
	}
	return *o.TaxId
}

// GetTaxIdOk returns a tuple with the TaxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcBrandCreateRequest) GetTaxIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaxId) {
		return nil, false
	}
	return o.TaxId, true
}

// HasTaxId returns a boolean if a field has been set.
func (o *TenDlcBrandCreateRequest) HasTaxId() bool {
	if o != nil && !IsNil(o.TaxId) {
		return true
	}

	return false
}

// SetTaxId gets a reference to the given string and assigns it to the TaxId field.
func (o *TenDlcBrandCreateRequest) SetTaxId(v string) {
	o.TaxId = &v
}

// GetWebsite returns the Website field value
func (o *TenDlcBrandCreateRequest) GetWebsite() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Website
}

// GetWebsiteOk returns a tuple with the Website field value
// and a boolean to check if the value has been set.
func (o *TenDlcBrandCreateRequest) GetWebsiteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Website, true
}

// SetWebsite sets field value
func (o *TenDlcBrandCreateRequest) SetWebsite(v string) {
	o.Website = v
}

// GetCountry returns the Country field value
func (o *TenDlcBrandCreateRequest) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *TenDlcBrandCreateRequest) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *TenDlcBrandCreateRequest) SetCountry(v string) {
	o.Country = v
}

// GetStreet returns the Street field value if set, zero value otherwise.
func (o *TenDlcBrandCreateRequest) GetStreet() string {
	if o == nil || IsNil(o.Street) {
		var ret string
		return ret
	}
	return *o.Street
}

// GetStreetOk returns a tuple with the Street field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcBrandCreateRequest) GetStreetOk() (*string, bool) {
	if o == nil || IsNil(o.Street) {
		return nil, false
	}
	return o.Street, true
}

// HasStreet returns a boolean if a field has been set.
func (o *TenDlcBrandCreateRequest) HasStreet() bool {
	if o != nil && !IsNil(o.Street) {
		return true
	}

	return false
}

// SetStreet gets a reference to the given string and assigns it to the Street field.
func (o *TenDlcBrandCreateRequest) SetStreet(v string) {
	o.Street = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *TenDlcBrandCreateRequest) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcBrandCreateRequest) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *TenDlcBrandCreateRequest) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *TenDlcBrandCreateRequest) SetCity(v string) {
	o.City = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *TenDlcBrandCreateRequest) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcBrandCreateRequest) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *TenDlcBrandCreateRequest) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *TenDlcBrandCreateRequest) SetState(v string) {
	o.State = &v
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise.
func (o *TenDlcBrandCreateRequest) GetPostalCode() string {
	if o == nil || IsNil(o.PostalCode) {
		var ret string
		return ret
	}
	return *o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenDlcBrandCreateRequest) GetPostalCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PostalCode) {
		return nil, false
	}
	return o.PostalCode, true
}

// HasPostalCode returns a boolean if a field has been set.
func (o *TenDlcBrandCreateRequest) HasPostalCode() bool {
	if o != nil && !IsNil(o.PostalCode) {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given string and assigns it to the PostalCode field.
func (o *TenDlcBrandCreateRequest) SetPostalCode(v string) {
	o.PostalCode = &v
}

// GetComplianceContactEmail returns the ComplianceContactEmail field value
func (o *TenDlcBrandCreateRequest) GetComplianceContactEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComplianceContactEmail
}

// GetComplianceContactEmailOk returns a tuple with the ComplianceContactEmail field value
// and a boolean to check if the value has been set.
func (o *TenDlcBrandCreateRequest) GetComplianceContactEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComplianceContactEmail, true
}

// SetComplianceContactEmail sets field value
func (o *TenDlcBrandCreateRequest) SetComplianceContactEmail(v string) {
	o.ComplianceContactEmail = v
}

// GetComplianceContactPhone returns the ComplianceContactPhone field value
func (o *TenDlcBrandCreateRequest) GetComplianceContactPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComplianceContactPhone
}

// GetComplianceContactPhoneOk returns a tuple with the ComplianceContactPhone field value
// and a boolean to check if the value has been set.
func (o *TenDlcBrandCreateRequest) GetComplianceContactPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComplianceContactPhone, true
}

// SetComplianceContactPhone sets field value
func (o *TenDlcBrandCreateRequest) SetComplianceContactPhone(v string) {
	o.ComplianceContactPhone = v
}

func (o TenDlcBrandCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenDlcBrandCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scenarioId"] = o.ScenarioId
	toSerialize["businessType"] = o.BusinessType
	toSerialize["legalName"] = o.LegalName
	if !IsNil(o.TaxId) {
		toSerialize["taxId"] = o.TaxId
	}
	toSerialize["website"] = o.Website
	toSerialize["country"] = o.Country
	if !IsNil(o.Street) {
		toSerialize["street"] = o.Street
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.PostalCode) {
		toSerialize["postalCode"] = o.PostalCode
	}
	toSerialize["complianceContactEmail"] = o.ComplianceContactEmail
	toSerialize["complianceContactPhone"] = o.ComplianceContactPhone
	return toSerialize, nil
}

func (o *TenDlcBrandCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scenarioId",
		"businessType",
		"legalName",
		"website",
		"country",
		"complianceContactEmail",
		"complianceContactPhone",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenDlcBrandCreateRequest := _TenDlcBrandCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTenDlcBrandCreateRequest)

	if err != nil {
		return err
	}

	*o = TenDlcBrandCreateRequest(varTenDlcBrandCreateRequest)

	return err
}

type NullableTenDlcBrandCreateRequest struct {
	value *TenDlcBrandCreateRequest
	isSet bool
}

func (v NullableTenDlcBrandCreateRequest) Get() *TenDlcBrandCreateRequest {
	return v.value
}

func (v *NullableTenDlcBrandCreateRequest) Set(val *TenDlcBrandCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTenDlcBrandCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTenDlcBrandCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenDlcBrandCreateRequest(val *TenDlcBrandCreateRequest) *NullableTenDlcBrandCreateRequest {
	return &NullableTenDlcBrandCreateRequest{value: val, isSet: true}
}

func (v NullableTenDlcBrandCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenDlcBrandCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
