/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"encoding/json"
)

// checks if the BroadcastResponseAudience type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BroadcastResponseAudience{}

// BroadcastResponseAudience Broadcast audience: exactly one of `filter` (Mongo-style query evaluated against synced user objects) or `emails` (raw list, max 10,000 addresses; for larger audiences use filter after syncing users via the Users API).
type BroadcastResponseAudience struct {
	Filter map[string]interface{} `json:"filter,omitempty"`
	Emails []string               `json:"emails,omitempty"`
}

// NewBroadcastResponseAudience instantiates a new BroadcastResponseAudience object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBroadcastResponseAudience() *BroadcastResponseAudience {
	this := BroadcastResponseAudience{}
	return &this
}

// NewBroadcastResponseAudienceWithDefaults instantiates a new BroadcastResponseAudience object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBroadcastResponseAudienceWithDefaults() *BroadcastResponseAudience {
	this := BroadcastResponseAudience{}
	return &this
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *BroadcastResponseAudience) GetFilter() map[string]interface{} {
	if o == nil || IsNil(o.Filter) {
		var ret map[string]interface{}
		return ret
	}
	return o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BroadcastResponseAudience) GetFilterOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Filter) {
		return map[string]interface{}{}, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *BroadcastResponseAudience) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given map[string]interface{} and assigns it to the Filter field.
func (o *BroadcastResponseAudience) SetFilter(v map[string]interface{}) {
	o.Filter = v
}

// GetEmails returns the Emails field value if set, zero value otherwise.
func (o *BroadcastResponseAudience) GetEmails() []string {
	if o == nil || IsNil(o.Emails) {
		var ret []string
		return ret
	}
	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BroadcastResponseAudience) GetEmailsOk() ([]string, bool) {
	if o == nil || IsNil(o.Emails) {
		return nil, false
	}
	return o.Emails, true
}

// HasEmails returns a boolean if a field has been set.
func (o *BroadcastResponseAudience) HasEmails() bool {
	if o != nil && !IsNil(o.Emails) {
		return true
	}

	return false
}

// SetEmails gets a reference to the given []string and assigns it to the Emails field.
func (o *BroadcastResponseAudience) SetEmails(v []string) {
	o.Emails = v
}

func (o BroadcastResponseAudience) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BroadcastResponseAudience) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	if !IsNil(o.Emails) {
		toSerialize["emails"] = o.Emails
	}
	return toSerialize, nil
}

type NullableBroadcastResponseAudience struct {
	value *BroadcastResponseAudience
	isSet bool
}

func (v NullableBroadcastResponseAudience) Get() *BroadcastResponseAudience {
	return v.value
}

func (v *NullableBroadcastResponseAudience) Set(val *BroadcastResponseAudience) {
	v.value = val
	v.isSet = true
}

func (v NullableBroadcastResponseAudience) IsSet() bool {
	return v.isSet
}

func (v *NullableBroadcastResponseAudience) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBroadcastResponseAudience(val *BroadcastResponseAudience) *NullableBroadcastResponseAudience {
	return &NullableBroadcastResponseAudience{value: val, isSet: true}
}

func (v NullableBroadcastResponseAudience) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBroadcastResponseAudience) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
