/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"encoding/json"
	"time"
)

// checks if the GetMetricsResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMetricsResponseInner{}

// GetMetricsResponseInner <p>A <code>GetMetricData</code> call returns an array of <code>MetricDataResult</code>             structures. Each of these structures includes the data points for that metric, along             with the timestamps of those data points and other identifying information.</p>
type GetMetricsResponseInner struct {
	// <p>The short name you specified to represent this metric.</p>
	Id *string `json:"Id,omitempty"`
	// <p>The human-readable label associated with the data.</p>
	Label *string `json:"Label,omitempty"`
	// <p>The timestamps for the data points, formatted in Unix timestamp format. The number of             timestamps always matches the number of values and the value for Timestamps[x] is             Values[x].</p>
	Timestamps []time.Time `json:"Timestamps,omitempty"`
	// <p>The data points for the metric corresponding to <code>Timestamps</code>. The number of             values always matches the number of timestamps and the timestamp for Values[x] is             Timestamps[x].</p>
	Values     []float32 `json:"Values,omitempty"`
	StatusCode *string   `json:"StatusCode,omitempty"`
	// <p>A list of messages with additional information about the data returned.</p>
	Messages []GetMetricsResponseInnerMessagesInner `json:"Messages,omitempty"`
}

// NewGetMetricsResponseInner instantiates a new GetMetricsResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMetricsResponseInner() *GetMetricsResponseInner {
	this := GetMetricsResponseInner{}
	return &this
}

// NewGetMetricsResponseInnerWithDefaults instantiates a new GetMetricsResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMetricsResponseInnerWithDefaults() *GetMetricsResponseInner {
	this := GetMetricsResponseInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetMetricsResponseInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMetricsResponseInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetMetricsResponseInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetMetricsResponseInner) SetId(v string) {
	o.Id = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *GetMetricsResponseInner) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMetricsResponseInner) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *GetMetricsResponseInner) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *GetMetricsResponseInner) SetLabel(v string) {
	o.Label = &v
}

// GetTimestamps returns the Timestamps field value if set, zero value otherwise.
func (o *GetMetricsResponseInner) GetTimestamps() []time.Time {
	if o == nil || IsNil(o.Timestamps) {
		var ret []time.Time
		return ret
	}
	return o.Timestamps
}

// GetTimestampsOk returns a tuple with the Timestamps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMetricsResponseInner) GetTimestampsOk() ([]time.Time, bool) {
	if o == nil || IsNil(o.Timestamps) {
		return nil, false
	}
	return o.Timestamps, true
}

// HasTimestamps returns a boolean if a field has been set.
func (o *GetMetricsResponseInner) HasTimestamps() bool {
	if o != nil && !IsNil(o.Timestamps) {
		return true
	}

	return false
}

// SetTimestamps gets a reference to the given []time.Time and assigns it to the Timestamps field.
func (o *GetMetricsResponseInner) SetTimestamps(v []time.Time) {
	o.Timestamps = v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *GetMetricsResponseInner) GetValues() []float32 {
	if o == nil || IsNil(o.Values) {
		var ret []float32
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMetricsResponseInner) GetValuesOk() ([]float32, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *GetMetricsResponseInner) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []float32 and assigns it to the Values field.
func (o *GetMetricsResponseInner) SetValues(v []float32) {
	o.Values = v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *GetMetricsResponseInner) GetStatusCode() string {
	if o == nil || IsNil(o.StatusCode) {
		var ret string
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMetricsResponseInner) GetStatusCodeOk() (*string, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *GetMetricsResponseInner) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given string and assigns it to the StatusCode field.
func (o *GetMetricsResponseInner) SetStatusCode(v string) {
	o.StatusCode = &v
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *GetMetricsResponseInner) GetMessages() []GetMetricsResponseInnerMessagesInner {
	if o == nil || IsNil(o.Messages) {
		var ret []GetMetricsResponseInnerMessagesInner
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMetricsResponseInner) GetMessagesOk() ([]GetMetricsResponseInnerMessagesInner, bool) {
	if o == nil || IsNil(o.Messages) {
		return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *GetMetricsResponseInner) HasMessages() bool {
	if o != nil && !IsNil(o.Messages) {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []GetMetricsResponseInnerMessagesInner and assigns it to the Messages field.
func (o *GetMetricsResponseInner) SetMessages(v []GetMetricsResponseInnerMessagesInner) {
	o.Messages = v
}

func (o GetMetricsResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMetricsResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if !IsNil(o.Label) {
		toSerialize["Label"] = o.Label
	}
	if !IsNil(o.Timestamps) {
		toSerialize["Timestamps"] = o.Timestamps
	}
	if !IsNil(o.Values) {
		toSerialize["Values"] = o.Values
	}
	if !IsNil(o.StatusCode) {
		toSerialize["StatusCode"] = o.StatusCode
	}
	if !IsNil(o.Messages) {
		toSerialize["Messages"] = o.Messages
	}
	return toSerialize, nil
}

type NullableGetMetricsResponseInner struct {
	value *GetMetricsResponseInner
	isSet bool
}

func (v NullableGetMetricsResponseInner) Get() *GetMetricsResponseInner {
	return v.value
}

func (v *NullableGetMetricsResponseInner) Set(val *GetMetricsResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMetricsResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMetricsResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMetricsResponseInner(val *GetMetricsResponseInner) *NullableGetMetricsResponseInner {
	return &NullableGetMetricsResponseInner{value: val, isSet: true}
}

func (v NullableGetMetricsResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMetricsResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
