/*
Pingram

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EmailComponentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailComponentResponse{}

// EmailComponentResponse struct for EmailComponentResponse
type EmailComponentResponse struct {
	EnvId        string                                    `json:"envId"`
	ComponentId  string                                    `json:"componentId"`
	Name         string                                    `json:"name"`
	Internal     string                                    `json:"internal"`
	InternalPage string                                    `json:"internalPage"`
	Html         string                                    `json:"html"`
	CreatedAt    string                                    `json:"createdAt"`
	ModifiedAt   string                                    `json:"modifiedAt"`
	ReferencedBy []EmailComponentResponseReferencedByInner `json:"referencedBy"`
	Channel      string                                    `json:"channel"`
}

type _EmailComponentResponse EmailComponentResponse

// NewEmailComponentResponse instantiates a new EmailComponentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailComponentResponse(envId string, componentId string, name string, internal string, internalPage string, html string, createdAt string, modifiedAt string, referencedBy []EmailComponentResponseReferencedByInner, channel string) *EmailComponentResponse {
	this := EmailComponentResponse{}
	this.EnvId = envId
	this.ComponentId = componentId
	this.Name = name
	this.Internal = internal
	this.InternalPage = internalPage
	this.Html = html
	this.CreatedAt = createdAt
	this.ModifiedAt = modifiedAt
	this.ReferencedBy = referencedBy
	this.Channel = channel
	return &this
}

// NewEmailComponentResponseWithDefaults instantiates a new EmailComponentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailComponentResponseWithDefaults() *EmailComponentResponse {
	this := EmailComponentResponse{}
	return &this
}

// GetEnvId returns the EnvId field value
func (o *EmailComponentResponse) GetEnvId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvId
}

// GetEnvIdOk returns a tuple with the EnvId field value
// and a boolean to check if the value has been set.
func (o *EmailComponentResponse) GetEnvIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvId, true
}

// SetEnvId sets field value
func (o *EmailComponentResponse) SetEnvId(v string) {
	o.EnvId = v
}

// GetComponentId returns the ComponentId field value
func (o *EmailComponentResponse) GetComponentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComponentId
}

// GetComponentIdOk returns a tuple with the ComponentId field value
// and a boolean to check if the value has been set.
func (o *EmailComponentResponse) GetComponentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComponentId, true
}

// SetComponentId sets field value
func (o *EmailComponentResponse) SetComponentId(v string) {
	o.ComponentId = v
}

// GetName returns the Name field value
func (o *EmailComponentResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EmailComponentResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EmailComponentResponse) SetName(v string) {
	o.Name = v
}

// GetInternal returns the Internal field value
func (o *EmailComponentResponse) GetInternal() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Internal
}

// GetInternalOk returns a tuple with the Internal field value
// and a boolean to check if the value has been set.
func (o *EmailComponentResponse) GetInternalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Internal, true
}

// SetInternal sets field value
func (o *EmailComponentResponse) SetInternal(v string) {
	o.Internal = v
}

// GetInternalPage returns the InternalPage field value
func (o *EmailComponentResponse) GetInternalPage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InternalPage
}

// GetInternalPageOk returns a tuple with the InternalPage field value
// and a boolean to check if the value has been set.
func (o *EmailComponentResponse) GetInternalPageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InternalPage, true
}

// SetInternalPage sets field value
func (o *EmailComponentResponse) SetInternalPage(v string) {
	o.InternalPage = v
}

// GetHtml returns the Html field value
func (o *EmailComponentResponse) GetHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Html
}

// GetHtmlOk returns a tuple with the Html field value
// and a boolean to check if the value has been set.
func (o *EmailComponentResponse) GetHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Html, true
}

// SetHtml sets field value
func (o *EmailComponentResponse) SetHtml(v string) {
	o.Html = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *EmailComponentResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *EmailComponentResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *EmailComponentResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetModifiedAt returns the ModifiedAt field value
func (o *EmailComponentResponse) GetModifiedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value
// and a boolean to check if the value has been set.
func (o *EmailComponentResponse) GetModifiedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedAt, true
}

// SetModifiedAt sets field value
func (o *EmailComponentResponse) SetModifiedAt(v string) {
	o.ModifiedAt = v
}

// GetReferencedBy returns the ReferencedBy field value
func (o *EmailComponentResponse) GetReferencedBy() []EmailComponentResponseReferencedByInner {
	if o == nil {
		var ret []EmailComponentResponseReferencedByInner
		return ret
	}

	return o.ReferencedBy
}

// GetReferencedByOk returns a tuple with the ReferencedBy field value
// and a boolean to check if the value has been set.
func (o *EmailComponentResponse) GetReferencedByOk() ([]EmailComponentResponseReferencedByInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferencedBy, true
}

// SetReferencedBy sets field value
func (o *EmailComponentResponse) SetReferencedBy(v []EmailComponentResponseReferencedByInner) {
	o.ReferencedBy = v
}

// GetChannel returns the Channel field value
func (o *EmailComponentResponse) GetChannel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *EmailComponentResponse) GetChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *EmailComponentResponse) SetChannel(v string) {
	o.Channel = v
}

func (o EmailComponentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailComponentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["envId"] = o.EnvId
	toSerialize["componentId"] = o.ComponentId
	toSerialize["name"] = o.Name
	toSerialize["internal"] = o.Internal
	toSerialize["internalPage"] = o.InternalPage
	toSerialize["html"] = o.Html
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["modifiedAt"] = o.ModifiedAt
	toSerialize["referencedBy"] = o.ReferencedBy
	toSerialize["channel"] = o.Channel
	return toSerialize, nil
}

func (o *EmailComponentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"envId",
		"componentId",
		"name",
		"internal",
		"internalPage",
		"html",
		"createdAt",
		"modifiedAt",
		"referencedBy",
		"channel",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailComponentResponse := _EmailComponentResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailComponentResponse)

	if err != nil {
		return err
	}

	*o = EmailComponentResponse(varEmailComponentResponse)

	return err
}

type NullableEmailComponentResponse struct {
	value *EmailComponentResponse
	isSet bool
}

func (v NullableEmailComponentResponse) Get() *EmailComponentResponse {
	return v.value
}

func (v *NullableEmailComponentResponse) Set(val *EmailComponentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailComponentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailComponentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailComponentResponse(val *EmailComponentResponse) *NullableEmailComponentResponse {
	return &NullableEmailComponentResponse{value: val, isSet: true}
}

func (v NullableEmailComponentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailComponentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
